### ISSUE TITLE
Add unsafe_hash for PEP 681

### ISSUE THREAD

**Issue by hynek** [python-attrs/attrs#1003]
I've been asked to add `unsafe_hash` as an alias for `hash` **at class level** for PEP 618 (data class transforms).

I'm not enthusiastic about the lack of symmetry between class-level and field-level hash but this is not the hill I'm dying on.

**Comment by nicktimko** [comment]
[PEP-681](https://peps.python.org/pep-0681/) not 618 if anyone's looking.
