### ISSUE TITLE
The logo in README is incompatible with dark mode

### ISSUE THREAD

**Issue by webknjaz** [python-attrs/attrs#1013]
$sbj. See the pics:

![attrs-dark-org-logo](https://user-images.githubusercontent.com/578543/185758311-e4572e4f-93db-4d18-8da1-f529cc6f95bd.png)
![attrs-dark-readme-logo](https://user-images.githubusercontent.com/578543/185758315-b16e0445-b985-4b9a-bdbc-81db8b2227de.png)

The org logo is only fixable by re-uploading it. So it requires actually repainting and coming up with a color that has enough contrast with both light and dark theme variants.

The README logo can be either fixed the same way or you could leverage GitHub's ability to display images depending on the current level of darkness as documented at https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/. The immediate downside I foresee for implementing the latter is that PyPI wouldn't differentiate the image markers and will just show both, which is unfortunate.

You can preview this stuff by toggling the appearance at https://github.com/settings/appearance. I know that some people also use https://github.com/StylishThemes/GitHub-Dark but I doubt it'll add more cases than already present it the GitHub-native themes.

The same problems in other places: https://github.com/pytest-dev/pytest/issues/8158 / https://github.com/pytest-dev/pytest/issues/8356.

**Comment by hynek** [comment]
I _think_ we could just add a white background instead of transparency?

**Comment by hynek** [comment]
ugh wait furo has a grey background. i'll have to think some more

**Comment by webknjaz** [comment]
I was thinking, maybe some light shade of gray? FWIW Furo shouldn't be a problem because it allows setting different images for its light and dark variants.

**Comment by hynek** [comment]
I think white is great, and I'll leave furo alone for now?

**Comment by hynek** [comment]
oh wait i have both colors

**Comment by hynek** [comment]
![white_logo_color_background](https://user-images.githubusercontent.com/41240/185949186-6a2df9d9-4676-4954-b189-287d56dee575.svg)
![white_logo_transparent_background](https://user-images.githubusercontent.com/41240/185949194-673447d2-c955-45bc-83d5-7f9fd2b5e21d.svg)

**Comment by hynek** [comment]
IIRC, there was something funky with the SVG tho 🤔

**Comment by webknjaz** [comment]
FWIW, I've opened the SVG used in the GH README in the browser, and using the DevTools checked that changing it to have `fill="#444"` or `fill="#555"` is much better visible in the dark mode and is still distinct on the white background. But you'd need to see for yourself.

**Comment by hynek** [comment]
I've fixed it with good-ole HTML.

I don't know what your first screenshot is showing tho, my UI looks like this:

<img width="347" alt="Screenshot 2022-08-23 at 07 52 57@2x" src="https://user-images.githubusercontent.com/41240/186080530-32d8a180-3aa5-4ff1-bcb4-f4efc9ae8ec0.png">

Some browser extension?

**Comment by webknjaz** [comment]
> Some browser extension?

Yep. https://github.com/refined-github/refined-github. I keep forgetting to disable it before screenshotting :)

But I checked that the same is happening on the org page at https://github.com/python-attrs with the extension disabled.

**Comment by hynek** [comment]
This should be fixed now. I had to leave a bit more of a space around it, because it a circle on me? Oh well.

**Comment by webknjaz** [comment]
Yes, that looks perfect now!
