### ISSUE TITLE
[bug][docs deps] Sphinx 5.2.1 breaks the docs builds

### ISSUE THREAD

**Issue by webknjaz** [python-attrs/attrs#1031]
Last success (Sphinx v5.1.1): https://github.com/python-attrs/attrs/actions/runs/3080585434/jobs/4978108196#step:5:90.
Current failures (Sphinx v5.2.1): https://github.com/python-attrs/attrs/actions/runs/3128734322/jobs/5092896008#step:5:90.

Correlation with #1029 is a coincidence. I haven't noticed anything obviously related on the Sphinx's tracker created lately. So whoever ends up debugging this would need to file an issue there, maybe.

See https://github.com/python-attrs/attrs/pull/1029#issuecomment-1259580689 + https://github.com/python-attrs/attrs/pull/1030#issuecomment-1259611491 for details.

**Comment by hynek** [comment]
Looks like sphinx started to interpret the contents of `type` declarations in docstrings.

**Comment by webknjaz** [comment]
It's been doing that for years. Maybe they've extended the supported syntax further.
