### ISSUE TITLE
Howto documentation doesn't cover hashing with @define

### ISSUE THREAD

**Issue by itamarst** [python-attrs/attrs#1037]
https://www.attrs.org/en/22.1.0/hashing.html only talks about the `@attr.s` API, not `@define`.

**Comment by hynek** [comment]
this seems like something that should be fixed along with #1003.

i don't believe there's semantical differences between ng and old-school APIs? that was one of the few breaking changes we've ever embarked iirc

**Comment by itamarst** [comment]
I eventually figured it out, yeah, but had to go through a bunch of pages to realize that.
