### ISSUE TITLE
force run validator after instantiation (no on_setattr) (wishlist)

### ISSUE THREAD

**Issue by txemi** [python-attrs/attrs#1039]
With collection attrs I can run validators (deep_iterable and deep_mapping) on instantiation or later with on_setattr, but often this collections grow with no changing attr reference to itself so I suppose on_setattr is not call. How can I force run validators for some attr later when I know these collections changed and run value_validators? I suppose there is some way to do this because implementation exists inside attrs lib but I did not find how to call it.

Thanks,

**Comment by hynek** [comment]
I think you're looking for https://www.attrs.org/en/stable/api.html#attrs.validate

**Comment by txemi** [comment]
Yes, I think it is what I am looking for.

Thank you!
