### ISSUE TITLE
Can't debug into generated code in pycharm

### ISSUE THREAD

**Issue by chaokunyang** [python-attrs/attrs#1040]
When debug attrs in pycharm, it can't step into  generated code, pycharm just say `<frame not available>`:

code:
```
@define
class Coordinates:
    x: int
    y: int


def test_attr():
    c = Coordinates(x=1,y=2)
    print(c)
```

Pycharm info:
![image](https://user-images.githubusercontent.com/12445254/196086089-49e47777-2b77-44a1-abe5-042e6a3f7cad.png)

I'm using python3.8 and PyCharm 2022.1.1 (Professional Edition) on macos Monterey 12.1. Is there something wrong?

**Comment by hynek** [comment]
Is that true only for repr or all generated methods? (Especially `__init__`)

**Comment by chaokunyang** [comment]
> Is that true only for repr or all generated methods? (Especially `__init__`)

It doesn't work for all generated methods.

**Comment by chaokunyang** [comment]
Actually I followed the implementation in https://github.com/python-attrs/attrs/blob/32fb12789e5cba4b2e71c09e47196b10763ddd7d/src/attr/_make.py#L1889 . Seems it doesn't work:
```python
def test_debug_compiled():
    code = textwrap.dedent("""
    def _debug_compiled(x):
        print(x)
        print(x)
        return x
    """)[1:]
    unique_filename = "_debug_compiled"
    compiled = compile(code, unique_filename, "exec")
    context = {}
    exec(compiled, context, context)
    linecache.cache[unique_filename] = (
        len(code),
        None,
        code.splitlines(True),
        unique_filename,
    )
    _debug_compiled = context["_debug_compiled"]
    assert _debug_compiled(2) == 2

```

**Comment by chaokunyang** [comment]
```python
def test_debug_compiled():
    code = textwrap.dedent("""
    def _debug_compiled(x):
        print(x)
        print(x)
        return x
    """)[1:]
    unique_filename = "_debug_compiled.py"
    open(unique_filename, "w").write(code)
    compiled = compile(code, unique_filename, "exec")
    context = {}
    exec(compiled, context, context)
    _debug_compiled = context["_debug_compiled"]
    assert _debug_compiled(2) == 2
```
This will work, but creating files introduce cleanup issues, which I try to avoid.

**Comment by hynek** [comment]
I have just double-checked and I absolutely can step through it in pdb and pdbpp. Could you verify that please? If so, it's problem with PyCharm that we can't do anything about.

**Comment by chaokunyang** [comment]
`pdb` works, seems it'a a bug in pycharm. I'll post this to pycharm help center. thanks, anyway
