### ISSUE TITLE
get self ref from repr callable

### ISSUE THREAD

**Issue by txemi** [python-attrs/attrs#1042]
Sometimes for correct formatting of an attribute I need knowing other attrs. The callable you can override for repr as seen in documentation has only one argument, the value itself, but no self reference is passed so I cannot achieve this I think.

Thanks,

**Comment by hynek** [comment]
I think if you have such complicated needs, the best way is to write an own `__repr__` for now. With the new APIs, you don't even have to pass `repr=False` anymore – just implement it.

**Comment by txemi** [comment]
Ok, I will do as you say, Thanks!
