### ISSUE TITLE
collections.abc is not available in Python 2

### ISSUE THREAD

**Issue by wvxvw** [python-attrs/attrs#1044]
Hello. You are publishing this wheel: attrs-22.1.0-py2.py3-none-any.wh which implies it is available for installing with Python 2, but `collections.abc` isn't available in Python 2, this is why `_compat.py` fails to import, preventing everything else from functioning.

To correct this, you need to publish this Wheel as attrs-22.1.0-py3-none-any.whl (i.e. remove the `py2` from the name). Since you are not unique in doing this, this seems to be the result of blanket-marking the binary distribution as "pure source", which then unintentionally declares it Python-2 compatible. Probably not your fault, but the fault of the tools you are using to create Wheels, still, it breaks things for people who need to deal with archaic systems.

**Comment by hynek** [comment]
This has already been fixed in https://github.com/python-attrs/attrs/commit/f7d64c01900b7050348ae8e2011e42c3514811b4

That said, the relevant compatibility indicator is not the wheel suffix, but the packaging metadata.
