### ISSUE TITLE
No matching distribution found

### ISSUE THREAD

**Issue by usmansagri** [python-attrs/attrs#1048]
I am trying to install requirements for a flask app and getting this error message.

![image](https://user-images.githubusercontent.com/32294868/198992119-4339c28c-f747-4269-b0fe-c0d604fcb920.png)

I am currently running python 3.9.7 on my windows machine, Kindly guide how to resolve this issue.

**Comment by Tinche** [comment]
What happens if you run `pip install attrs`?

**Comment by usmansagri** [comment]
Same error but with a warning message: There was an error checking the latest version of pip.
![image](https://user-images.githubusercontent.com/32294868/199011054-c6acca5e-d0a7-4786-92bd-92510b088974.png)

**Comment by Tinche** [comment]
I think it's an issue with your pip installation or your networking. Are you using a private package repository?

**Comment by usmansagri** [comment]
@Tinche  Yes I am!
<img width="502" alt="image" src="https://user-images.githubusercontent.com/32294868/199024606-65d384ce-8116-4198-8ab7-2775f7a0a31b.png">

**Comment by Tinche** [comment]
And if you remove this, I'm guessing it works? I can't really help you debug further (talk to whoever set that up), I don't think the problem is on our end.

**Comment by usmansagri** [comment]
Sure @Tinche , Thanks a lot!

**Comment by usmansagri** [comment]
Sure @Tinche , Thanks a lot!
