### ISSUE TITLE
Optional `convert`

### ISSUE THREAD

**Issue by cossatot** [python-attrs/attrs#105]
Is it, or could it be, possible to have optional type conversion using the `convert` argument, with the same logic as validation?

Something like:

``` python
@attr.s
class Thing(object):
    x = attr.ib(default=None, convert=optional(float), validator=optional(validate_x))
```

Apologies if it's already supported; I just don't see how in the docs.

**Comment by Tinche** [comment]
You can write this yourself, easily (and I have in one of my projects):
```
def opt(convert):
    """Invoke the subconverter only if the value is present."""
    def optional_converter(val):
        if val is None:
            return None
        return convert(val)
    return optional_converter
```

Now, I don't think it'd be possible to use the same callable (`optional`) as a validator factory AND a convert factory without changes to `attrs` itself.

**Comment by cossatot** [comment]
Thanks, that's exactly what i was looking for.

**Comment by hynek** [comment]
I guess it would make sense to add it to attrs?
