### ISSUE TITLE
Wrapping the `define` decorator, for example to change default arguments, breaks mypy

### ISSUE THREAD

**Issue by maxbane** [python-attrs/attrs#1052]
Imagine that, in general, the user wants a more specialized `@define` that
overrides the defaults for some subset of `@define`'s args, in order to
streamline their code and reduce boilerplate. A natural solution is to create a
partially applied wrapper around `define`, and use that in place of `@define`.
For example, see the minimal example below where I create the wrapper 
`my_define = partial(define, slots=False)`. I can then use `@my_define`
everywhere instead of `@define(slots=False)` and it totally works at runtime!

However, the mypy plugin now seems to be confused when the resulting classes use
validator/convertor decorators on their fields. I'm wondering if there is
something simple I can do to make `@my_define` play nicely with mypy.

Thanks for your consideration!

```python
from attrs import define, field
from functools import partial


@define(slots=False)
class Foo:
    tag: str = field()

    @tag.validator
    def _check_tag(self, attribute, value):
        if not isinstance(value, str):
            raise TypeError(
                f"tag must be a str-like; but got a {type(value)}: {value!r}"
            )


# synonym for @define that always sets slots=False
my_define = partial(define, slots=False)


@my_define
class Bar:
    tag: str = field()

    # ERROR: mypy complains "str" has no attribute "validator"
    @tag.validator
    def _check_tag(self, attribute, value):
        if not isinstance(value, str):
            raise TypeError(
                f"tag must be a str-like; but got a {type(value)}: {value!r}"
            )

# Example usage shows that Foo and Bar classes both behave as expected/desired:
f = Foo(tag="my tag")
print(f)
print(hasattr(f, "__slots__"))

b = Bar(tag="my tag")
print(b)
print(hasattr(b, "__slots__"))

# But if you run mypy on this file you'll get:
# scratch_attrs_mypy.py:26: error: "str" has no attribute "validator"  [attr-defined]
```

**Comment by hynek** [comment]
This is documented here: https://www.attrs.org/en/stable/extending.html#wrapping-the-decorator

**Comment by maxbane** [comment]
Wow, amazing, and I'm embarrassed I missed that! Thanks!

**Comment by maxbane** [comment]
Incidentally, is there anything similar one can do to make pylance recognize the wrapped decorator, so that it autocompletes constructor arguments and instance variables? The spec at https://github.com/microsoft/pyright/blob/main/specs/dataclass_transforms.md has a [section](https://github.com/microsoft/pyright/blob/main/specs/dataclass_transforms.md#applying-to-attrs) on how it was applied to attrs before it was incorporated upstream into attrs... should I be able to do something similar with my own wrapper function? I'm still futzing with it and might get it to work, but thought I'd ask if it's come up before.
