### ISSUE TITLE
Can't overwrite the dict representation for a attr.field

### ISSUE THREAD

**Issue by YoniMelki** [python-attrs/attrs#1054]
I have a class that has an Enum in one of its fields. I want to customize its dict representation so I only have the enum name instead of all the enum repr.

**For example**
```python
import enum

from attr import frozen


class Options(enum.Enum)
    FIRST_OPTION = enum.auto()
    SECOND_OPTION = enum.auto()


@frozen
class MyClass:
    id: str
    option: Options


my_class = MyClass("name", Options.FIRST_OPTION)
```

I want the result to be `{'id': 'name', 'option': FIRST_OPTION}` instead of `{'id': 'name', 'option': <Options.FIRST_OPTION: 2>}` when calling `attrs.asdict` without giving an argument to the `asdict` function

**Comment by pganssle** [comment]
This seems more like an issue with the repr of your enum class, unless you actually wanted your result to be `{'id': 'name', 'option': 'FIRST_OPTION'}` or something of that nature (where `'FIRST_OPTION'` is presumably the result of some function you call on your enum object)?

If it's mostly the repr you are concerned about, you can presumably customize that in the enum class, or if you are using Python 3.11+ there is this: https://docs.python.org/3/library/enum.html#enum.global_enum

**Comment by YoniMelki** [comment]
Thanks for the response @pganssle! However, I do not want to edit the repr of my enum class. I want the possibility to customize the dict repr of my `option` field.

**Comment by pganssle** [comment]
@YoniMelki The problem is that what you wrote in the "I want the result to be..." is unclear. The result of `attrs.asdict` is a dictionary, not a string, so there is no way to customize it in such a way that it gives the result you specified, so I think you need to be a bit more clear in what you are looking for.

**Comment by Tinche** [comment]
For more complex serialization cases like this you should just use cattrs, it'll let you do what you want easily.

**Comment by YoniMelki** [comment]
> @YoniMelki The problem is that what you wrote in the "I want the result to be..." is unclear. The result of `attrs.asdict` is a dictionary, not a string, so there is no way to customize it in such a way that it gives the result you specified, so I think you need to be a bit more clear in what you are looking for.

You can see that the result I want is indeed a dictionary and not a string so I don't really understand how should I rewrite the question :)

**Comment by YoniMelki** [comment]
> 

Any example/source by any chance?

**Comment by YoniMelki** [comment]
> For more complex serialization cases like this you should just use cattrs, it'll let you do what you want easily.

Any example/source by any chance?

**Comment by Tinche** [comment]
Out of the box, cattrs will use the value of the enum.

```python
from cattrs import Converter
c = Converter()

print(c.unstructure(my_class))  # {'id': 'name', 'option': 1}
```
So you can just change the enum and get the result you want:

```python
class Options(enum.Enum):
    FIRST_OPTION = "FIRST_OPTION"
    SECOND_OPTION = "SECOND_OPTION"
```

But let's say you're not willing or able to change the enum. You need an unstructure hook for this enum:

```python
c.register_unstructure_hook(Options, lambda o: o.name)
print(c.unstructure(my_class))  # {'id': 'name', 'option': 'FIRST_OPTION'}
```
And there you go.
