### ISSUE TITLE
Ability to define class member name that is part of constructor signature but *not* an attribute

### ISSUE THREAD

**Issue by mrolle45** [python-attrs/attrs#1061]
Here's a frustrating example for me.
```py
@define
class C(str):
    # The second argument is not used here
    def __new__(cls, s: str, n: int): return super().__new__(cls, s)

    n: int
```
How can I create a C with something like `c = C('foo', 42)`, such that `c.n == 42` and `str(c) == 'foo'`??

The auto generated `__init__` method has only an `n` parameter.  Thus the above constructor call will give me an error because after calling `__new__(cls, 'foo', 42)` it calls `__init__(self, 'foo', 42)`.

I am forced to define my own `__init__(self, s: str, n: int)` method, which will set the `self.n` attribute and call any conversions and validators, as well as using `object.__setattr__` if the class is frozen.

Alternatively,
* I can use `@define(init=False)` and create my own
```py
    def __init__(self, s: str = 'bar', n: int = 0):
        self.__attrs_init__(n)
```
* I have to take care to use the same default for `n` as I declared in the class; I need to use `NOTHING` if there is a default factory involved, so that `__attrs_init__` will call the factory.

I propose a `field` keyword which will mark `s` as only a parameter name.  No suggestions as to what would be a good keyword.  Thus my class would look like
```py
@define
class C(str):
    # The second argument is not used here
    def __new__(cls, s: str = 'bar', n: int = 0): return super().__new__(cls, s)

    s: str = field(xxx = True, default='bar')
    n: int = 0
```
The auto-generated `__init__' would look something like this:
```py
    def __init__(self, s: str = 'bar', n: int = 0):
        # Run __attrs_pre_init__
        # Set self.n = n, with any conversions
        # Run validators, including any defined for `s`.
        # Run __attrs_post_init__
```
That is, the same as would be without the `field(xxx=True)` but without setting `self.s`.
I think that a conversion for `s` should be illegal, because the intention is for `s` to be a `__new__` parameter, without any conversion.  A validator for `s` should use `s` without any conversion.

By the way, the order of the attributes is not important, other than mandatory attributes appearing first.  So if I had a mandatory `n` and an optional `s`, I would mention `n` before `s`.

**Comment by ambv** [comment]
The proposed solution seems more problematic than the actual problem to me. Edge cases like this one is why `attrs` supports defining your own `__init__`. Doing this isn't a workaround, it's literally following the library intent: if you want something custom to happen, make a custom method. Explicit is better than implicit in this case. Principle of least astonishment.
