### ISSUE TITLE
Some API doc entries in objects.inv have double-attr module prefixes

### ISSUE THREAD

**Issue by hynek** [python-attrs/attrs#1077]
e.g. `attr.attr.cmp_using`

cursory looking suggests it's autodoc vs manual.

**Comment by webknjaz** [comment]
Ah, I missed the dedicated issue and left the comments @ https://github.com/python-attrs/attrs/issues/1073#issuecomment-1369072401 & https://github.com/python-attrs/attrs/issues/1073#issuecomment-1369077722.
