### ISSUE TITLE
Add `type` back to `attrs.field()` for use in `attrs.make_class()`

### ISSUE THREAD

**Issue by rouge8** [python-attrs/attrs#1082]
I'm using `attrs.make_class()` to dynamically construct a class based on other attrs classes, and it would be nice to be able to specify the `type` of the fields on the generated class using `attrs.field()` instead of `attr.ib()`. In other words, this works:

```python
fields = {
    field.name: attr.ib(type=field.type)
    for field in itertools.chain.from_iterable(
        attrs.fields(t) for t in SOME_ATTRS_CLASSES
    )
    if not field.name.startswith("_")
}

MyClass = attrs.make_class("MyClass", fields)
```

but this does not:

```python
fields = {
    field.name: attrs.field(type=field.type)
    for field in itertools.chain.from_iterable(
        attrs.fields(t) for t in SOME_ATTRS_CLASSES
    )
    if not field.name.startswith("_")
}

MyClass = attrs.make_class("MyClass", fields)
```

**Comment by hynek** [comment]
Aw man yeah when I celebrated to get rid of that, I forgot about `make_class`. 🙈

**Comment by chrysle** [comment]
I'm working on the implementation.

**Comment by hynek** [comment]
Given that no type checker cares about `make_class()` as far as I can tell (I tried to get it to fail by passing wrong arguments to a make_class-borne class), would you mind sharing the utility you're getting out of this?

**Comment by hynek** [comment]
So metadata, gotcha!

I'm asking because I want to put a fat warning next to the argument.

**Comment by sscherfke** [comment]
This would also be nice for [Typed Settings](https://gitlab.com/sscherfke/typed-settings/-/blob/main/src/typed_settings/attrs/__init__.py#L496-501) :-)

**Comment by hynek** [comment]
@sscherfke well good news in #1107 ;)

**Comment by sscherfke** [comment]
woop woop \o/
