### ISSUE TITLE
`AttrsInstance` protocol in the new `attrs` namespace

### ISSUE THREAD

**Issue by tsx** [python-attrs/attrs#1089]
`AttrsInstance` protocol was added in https://github.com/python-attrs/attrs/pull/890

However [`attrs.asdict` and `attrs.astuple`](https://github.com/python-attrs/attrs/blob/main/src/attrs/__init__.pyi#L47-L67) still take `Any` as the instance. This reduces type safety for people using the "modern" API. Was there any reason for these two functions being left out of the original `AttrsInstance` change?

**Comment by Tinche** [comment]
I think we just forgot. A good opportunity for a quick PR!

**Comment by tsx** [comment]
[Opened a quick PR](https://github.com/python-attrs/attrs/pull/1090).
