### ISSUE TITLE
help parameter

### ISSUE THREAD

**Issue by jfindlay** [python-attrs/attrs#1103]
What is the recommended way to add a documentation or a description or a help string to an attribute?  I am thinking of something similar to the `argparse` [`help` keyword](https://docs.python.org/3/library/argparse.html#help).  I have not been able to find anything like this in the documentation or source.

I can always annotate each `attr.ib` with a comment where they are defined in the source code, but it seems like a field that could naturally be bundled into the attr itself.

**Comment by chrysle** [comment]
> What is the recommended way to add a documentation or a description or a help string to an attribute? 

You want to _generate_ a comment in the source code?

**Comment by webknjaz** [comment]
I think they want some way of exposing `__doc__`...?

**Comment by hynek** [comment]
There a ticket on this but I’m too much on a vacation to find it.
