### ISSUE TITLE
attr.ib converter function args issue

### ISSUE THREAD

**Issue by wandth** [python-attrs/attrs#1112]
hello, when I try to converter some class members such as that
```python
import attr

def new_converter(value):
    return " -rl " + value

@attr.s()
class Test(object):
    test_mem = attr.ib(default=None, converter = new_converter)

info = Test(test_mem="2222")

print("--->", info.test_mem)
```
that was all right 

but when I do wrote those code 
``` python
def new_converter(value):
    return " -rl " + value

@attr.s()
class Test(object):
    test_mem = attr.ib(default=None, converter = new_converter)

# info = Test(test_mem="2222")
info = Test()
info.test_mem = "2222"  # ----------> this is wrong

print("--->", info.test_mem)
```
the code was wrong
![image](https://user-images.githubusercontent.com/34237282/225871096-29368a9a-b7a7-4ed2-a3f2-e698f71c161a.png)

is that problem a requirement for code or a bug ?

**Comment by Tinche** [comment]
Your converter can't handle your default value, so it raises an exception.

You can change your default value to `""` instead of `None`, or fix your converter so it can handle `value` being `None`.

**Comment by wandth** [comment]
@Tinche thanks

**Comment by wandth** [comment]
@Tinche 
![image](https://user-images.githubusercontent.com/34237282/226224056-160e368f-2d32-4906-a65f-23c5ec02bf80.png)
also wrong

**Comment by Tinche** [comment]
You're using old-style classes (`attr.s` instead of `attrs.define`), and I believe old-style classes do not run converters on setting the attribute, only on instance construction.

What happens if you rewrite your class like this:
```
from attrs import define, field
@define
class Test:
    test_mem = field(default="", converter=new_converter)
```
?

**Comment by wandth** [comment]
Thanks，I test define function in python 3, it works well
