### ISSUE TITLE
[CI/CD] Secretless publishing to PyPI

### ISSUE THREAD

**Issue by webknjaz** [python-attrs/attrs#1113]
$sbj is now in private beta. @hynek, if you want in, enroll at https://forms.gle/XUsRT8KTKy66TuUp7. My publishing action already supports it: from day one — https://github.com/marketplace/actions/pypi-publish#publishing-with-openid-connect.

**Comment by hynek** [comment]
Thanks, I think I'll wait until it's official. I have finally a pipeline working, I don't want to break it. :)

**Comment by webknjaz** [comment]
Sure, FWIW I think it's on the stage where the UX (on my GitHub Action side) won't change and there will only be internal/cosmetic improvements — we've been improving the logging since the original implementation with zero interface changes. The feedback seems good too. The only two things that I'm waiting for personally are the support for reusable workflows and the ability to have mandatory environments for better security. This is what will happen on the Warehouse side.
I don't know when will the beta become public, though.

**Comment by hynek** [comment]
I'll look at it at the sprints!

**Comment by hynek** [comment]
Fixed by 56cbf826df6adf04dd176fdd5391cf8829a14aa5! 🎉
