### ISSUE TITLE
Pyright job is flaky and temporarily optional

### ISSUE THREAD

**Issue by hynek** [python-attrs/attrs#1121]
Presumably due to some hosting changes, nodeenv and by extension Pyright are regularly failing  now.

I've marked it as optional for now, but would like to re-activate it ASAP.

Ref https://github.com/ekalinin/nodeenv/issues/324

**Comment by webknjaz** [comment]
Instead of commenting out the job dependency, you can use an action input to mark when it's okay for a job to fail FYI

**Comment by hynek** [comment]
If you wanna open a PR, feel free. For me that was easier than reading docs. ..🤪
