### ISSUE TITLE
docs: func link to attrs.make_class broken

### ISSUE THREAD

**Issue by ikonst** [python-attrs/attrs#1135]
See link in https://www.attrs.org/en/stable/api.html#attrs.field.

I'm not sure what's broken about this syntax since I'm not familiar with this doc format.

**Comment by hynek** [comment]
Thanks – turns out that syntax doesn't belong into docstrings yet!

I couldn't find more instances of it – please lmk if I've missed it.

**Comment by webknjaz** [comment]
@hynek I think MyST folks were going to explore that, maybe through an additional extension.
