### ISSUE TITLE
Type check error with asdict (2)

### ISSUE THREAD

**Issue by dnlfm** [python-attrs/attrs#1150]
Running MyPy for the following code:
```
from typing import Any
import attr

@attr.s(auto_attribs=True, kw_only=True, slots=True)
class MyClass:
    x: int

def my_serializer(record: Any, k: attr.Attribute, v: Any) -> Any:
    return v

m = MyClass(x=1)
k = attr.asdict(m, value_serializer=my_serializer)
print(k)
```
generates the error:
```
error: Argument 1 to "asdict" has incompatible type "MyClass"; expected "AttrsInstance"
```

**Related to**: https://github.com/python-attrs/attrs/issues/987

**Versions**:
- **attrs**==23.1.0
- **mypy**==0.812

**Comment by Tinche** [comment]
Can you try Mypy 1.3.0?

**Comment by dnlfm** [comment]
@Tinche With MyPy 1.3.0 it works. Is it necessary to update MyPy to work with newer versions of attrs?

**Comment by dnlfm** [comment]
Unfortunately updating MyPy to 1.3.0 introduces other issues... I think I'll just skip it for now. Thank you anyway!
