### ISSUE TITLE
Standard Validation Exception

### ISSUE THREAD

**Issue by BEllis** [python-attrs/attrs#1152]
Currently validators seem to raise a plethora of exceptions of different types and often don't prove much structured info regarding the error.

When a validation exception is raised, I'd expect to be able to determine,

- data class type
- data class instance
- attribute (and/or path?)
- validiator instance/function
- value
- reason for the validation failure or caused by exception

So I can provide useful and structured validation errors to clients of my library/application.

This is partially covered with cattrs and the ClassValidationError exception (and related classes) perhaps porting those exceptions from cattrs or attrs would be a good start?

.

**Comment by BEllis** [comment]
I've just found valid8 that fulfills my requirement. Would be nice if this was a first-class thing but happy to close if contributors disagree.

**Comment by hynek** [comment]
This is specifically what cattrs is for. With _attrs_ we try to provide you with a toolkit that builds classes as close to what you'd write yourself and leave automation on top of our hooks and metadata to other packages – most famously cattrs. Some older bits and pieces are arguably past that line, but we're trying to keep the two planes separate.
