### ISSUE TITLE
Migrate to typing.dataclass_transform()

### ISSUE THREAD

**Issue by superbobry** [python-attrs/attrs#1157]
`attrs` type stubs seem to use a non-standard pyright extension instead of the API described in [PEP-681](https://peps.python.org/pep-0681/):

https://github.com/python-attrs/attrs/blob/4461e2ce479551eb45fae88e325a0f8480eea28b/src/attr/__init__.pyi#L106-L121

This makes it difficult for other type checkers and similar tools to consume these type stubs without mirroring the pyright extension.

Would you accept a PR replacing all usages of `__dataclass_transform__()` with `typing.dataclass_transform()`?  We can use [`typing_extensions`](https://pypi.org/project/typing-extensions/) to get `dataclass_transform()` on Python < 3.11.

**Comment by Tinche** [comment]
Don't see why not, feel free to proceed with a PR. I believe our use of `dataclass_transform` predates the PEP and the typing implementation.

**Comment by superbobry** [comment]
Yes, IIRC that feature was incubated in pyright and then proposed&accepted as a PEP. Will send a PR soon.

**Comment by hynek** [comment]
fixed by #1158
