### ISSUE TITLE
Attribute without type hint in slotted class can't be changed 

### ISSUE THREAD

**Issue by rklasen** [python-attrs/attrs#1173]
Hi, so I've just stumbled over something I assume is a misunderstanding on my part, but  I want to ask to be sure.

I have a slotted class without type hints:

```python
@define
class Scenario:
    momentum = 0.0
    trackDirectory: Path = Path()
```

From the default value of `0.0` I assumed attrs would infer the type of `momentum`, but when I try to change the value, I get an error:

```python
>>> scen = Scenario(trackDirectory=".")
>>> scen.momentum = 15.09
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Scenario' object attribute 'momentum' is read-only
>>> type(scen.momentum)
<class 'float'>
```

So the type is a `float` as expected, but I can not change the value of `momentum`.

---

But when I add a type hint:

```python
@define
class Scenario:
    momentum: float = 0.0
    trackDirectory: Path = Path()
```

All works as expected:

```python
>>> scen = Scenario(trackDirectory=".")
>>> scen.momentum = 15.09
>>> type(scen.momentum)
<class 'float'>
```

---

So, is this expected/desired behavior and I'm just misunderstanding something? Thanks in advance!

**Comment by hynek** [comment]
attrs never infers the type from a value. If you set an attribute to a value (that's not an attrs.field/attr.ib), it's ignored by attrs and it becomes a class variable that can't be changed with slotted classes.

**Comment by rklasen** [comment]
Oh, I see. So is my workflow even recommended, or should I always explicitly call

```python
@define
class Scenario:
    momentum: float = field(default=0.0)
    trackDirectory: Path = Path()
```

I do like the shorter version for readability, but I don't want to rely on intended features.

**Comment by hynek** [comment]
No, you can write `momentum: float = 0.0`, I'm sorry for being unclear.

Attrs picks up everything that is either annotated (except ClassVar) or is assigner a field.

**Comment by rklasen** [comment]
Okay, good to know I can keep the short version. Thanks for the help!
