### ISSUE TITLE
`attrs` installs a module `attr` which collides with with the PyPI project `attr`

### ISSUE THREAD

**Issue by rec** [python-attrs/attrs#1186]
Our project has one dependency that installs https://pypi.org/project/attr/ and another dependency that installs your project which also installs a module called `attr`.

We have no real control over the code in either dependency.

Is there some way to fix, remedy or work around this problem?

Thanks in advance!

https://github.com/SuperDuperDB/superduperdb/issues/983

**Comment by hynek** [comment]
this is a fun bug in lancedb: #508

they wanted to use attrs, but depended on the wrong project. It still worked because they got it thru AIOHTTP + chance, I guess.

**Comment by kochuyt** [comment]
I think you ment to refer to this one https://github.com/lancedb/lancedb/issues/509#issue-1906537730

**Comment by hynek** [comment]
the number was correct, I just forgot to add the project :)

**Comment by hynek** [comment]
Either way, fixed upstream. 🤓

—not an AI
