### ISSUE TITLE
Typing error when using `resolve_types` inside class method

### ISSUE THREAD

**Issue by MicaelJarniac** [python-attrs/attrs#1194]
> Value of type variable "_A" of "resolve_types" cannot be "type[Foo]"  [type-var] - mypy(error)

I'm working on a lib that's supposed to support Python >= 3.9.
On 3.9, the following example works and has no typing errors.
On >= 3.10, however, I get these typing errors.

I'm using `from __future__ import annotations`, and I'm also inspecting the types of some fields at runtime, so I need to resolve types inside these methods, otherwise they're just strings.

The code actually works, despite the typing errors.

```py
import attrs


@attrs.define
class Foo:
    def bar(self) -> None:
        cls = type(self)
        attrs.resolve_types(cls)
        # Value of type variable "_A" of "resolve_types" cannot
        # be "type[Foo]"  [type-var] - mypy(error)

    @classmethod
    def baz(cls) -> None:
        attrs.resolve_types(cls)
        # Value of type variable "_A" of "resolve_types" cannot
        # be "type[Foo]"  [type-var] - mypy(error)
```

I believe the problem is that the type checker doesn't see the `@attrs.define` decorator when it's inspecting these methods, so it doesn't know this class will become a `type[AttrsInstance]`.

I'm not sure if there's a good solution to this, and it might actually be a Mypy problem, not attrs'.

https://github.com/python-attrs/attrs/blob/c849440ac93d5f33578e9e0d1b1d8f26fbd590ae/src/attr/__init__.pyi#L478-L484

https://github.com/python-attrs/attrs/blob/c849440ac93d5f33578e9e0d1b1d8f26fbd590ae/src/attr/__init__.pyi#L77

Here's a more complete example of my use-case:
```py
from __future__ import annotations

import attrs


@attrs.define
class Range:
    lower: float = float("-inf")
    upper: float = float("inf")

    enabled: bool = True


@attrs.define
class Sanity:
    temperature: Range = Range(-100, 300)
    frequency: Range = Range(0, 200)

    def toggle_all(self, *, enabled: bool) -> None:
        cls = type(self)
        attrs.resolve_types(cls)
        for field in attrs.fields(cls):
            if (typ := field.type) is not None and issubclass(typ, Range):
                getattr(self, field.name).enabled = enabled
```

I suppose for my use-case I could skip resolving types altogether, and just iterate over field names, doing `getattr` on all of them, and comparing the actual types of the fields at runtime, something like:
```py
for field in attrs.fields(type(self)):
    value = getattr(self, field.name)
    if isinstance(value, Range):
        ...
```
This would avoid the typing error I believe.

**Comment by Tinche** [comment]
Your example works on attrs main and Mypy 1.6, maybe it fixed itself? Or am I running it wrong?

**Comment by MicaelJarniac** [comment]
Indeed, there's no longer a typing error after installing the latest code available on this repo.

Thanks, and sorry for not checking it earlier myself.

**Comment by Tinche** [comment]
No worries. I wonder what fixed it :p
