### ISSUE TITLE
Support for generic type variables in loc, iloc, __getitem__, ...

### ISSUE THREAD

**Issue by olivercoleman-switchdin** [python-attrs/attrs#1205]
I was surprised to discover that generic type variables for `Frame`s and `Series` do not extend to the `loc`, `iloc`, `__getitem__`, etc interfaces. Is this on the roadmap?

**Comment by hynek** [comment]
I'm sorry, but I have absolutely no idea what you're talking about. Could you please state your problem in the context of this project?

**Comment by olivercoleman-switchdin** [comment]
Apologies, somehow posted this to the wrong project.
