### ISSUE TITLE
Docs say converters only run on initialization, but they also affect attribute setting

### ISSUE THREAD

**Issue by ariebovenberg** [python-attrs/attrs#1208]
As @Tinche himself remarked [here](https://discuss.python.org/t/pep-712-adding-a-converter-parameter-to-dataclasses-field/26126/43). It doesn't seem to be fixed since then, so I created this issue so this isn't forgotten.

example (from the discussion thread linked above):

```python
>>> from attrs import define, field
>>> @define
... class C:
...     x: int = field(converter=int)
...
>>> c = C("10")
>>> c
C(x=10)
>>> c.x = "20"
>>> c
C(x=20)
```

Wrong docs in questions [here](https://www.attrs.org/en/stable/examples.html#conversion):

> Please note that converters only run on initialization.

**Comment by hynek** [comment]
It has been fixed, but we haven’t published a new version since then, so the stable docs still contain the error.

It’s fixed in latest: https://www.attrs.org/en/latest/examples.html#conversion
