### ISSUE TITLE
import attr from attrs imports wrong package

### ISSUE THREAD

**Issue by radekzc** [python-attrs/attrs#1210]
2023-12-13 19:48:09.894 [info]     from lsprotocol import types as lsp
  File "/home/svobora/.vscode-server/extensions/ms-python.pylint-2023.10.1/bundled/libs/lsprotocol/types.py", line 14, in <module>
    import attrs
  File "/home/svobora/.vscode-server/extensions/ms-python.pylint-2023.10.1/bundled/libs/attrs/__init__.py", line 3, in <module>
    from attr import (
ImportError: cannot import name 'AttrsInstance' from 'attr' (/usr/lib/python3/dist-packages/attr/__init__.py)

It imports attr package from system python folder (Ubuntu 22.04). What to do?

**Comment by hynek** [comment]
OK, I'm sorry, but how are we supposed to help you with that? It seems to be a packaging issue, caused by a VS Code extension that seems to _bundle_ attrs!? My best suggestion is to reinstall `ms-python.pylint` whose installation seems to be corrupted.

**Comment by hynek** [comment]
There's also this: https://github.com/microsoft/vscode-pylint/issues/386

**Comment by radekzc** [comment]
For the starters do not name your packages the same as already existing packages, especially if those are installed as part of mainstream operating systems.

**Comment by hynek** [comment]
What package would that be?

**Comment by radekzc** [comment]
attr (not attrs) and removing import attr from your package

**Comment by radekzc** [comment]
https://pypi.org/project/attr/ 

Attrs should shadow it with its own attr package but it is not working. I suggest not naming a package with a same name as another package in pip.

**Comment by hynek** [comment]
Have you double-checked it's actually that package?

On Ubuntu it is not:

```
$ egrep '(title|author)' /usr/lib/python3/dist-packages/attr/__init__.py
__title__ = "attrs"
__author__ = "Hynek Schlawack"
```
