### ISSUE TITLE
Can't pickle a slotted class with missing attributes

### ISSUE THREAD

**Issue by oremanj** [python-attrs/attrs#1211]
I was surprised by this behavior today: (attrs 23.1.0, CPython 3.11.6)
```
>>> import attrs
>>> @attrs.define
... class A:
...   x = attrs.field(init=False)
...
>>> A()
A(x=NOTHING)
>>> import pickle
>>> pickle.dumps(A())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/venvs/versioned/atlvenv3-1.0.15/lib/python3.11/site-packages/attr/_make.py", line 933, in slots_getstate
    return {name: getattr(self, name) for name in state_attr_names}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/venvs/versioned/atlvenv3-1.0.15/lib/python3.11/site-packages/attr/_make.py", line 933, in <dictcomp>
    return {name: getattr(self, name) for name in state_attr_names}
                  ^^^^^^^^^^^^^^^^^^^
AttributeError: 'A' object has no attribute 'x'
```
If I use `@attrs.define(slots=False)` then it works fine.

In general I'm not sure what attrs' position is on unset attributes in attrs instances. They work fine in `repr()`, and you provide `init=False` which makes it easy to create them, but they crash `__getstate__` for slotted classes, as well as `asdict`/`astuple` for any attrs class whether slotted or dicted. It would be great to get either a consistent behavior here or at least some documentation of the inconsistencies.

**Comment by hynek** [comment]
This seems like a very edgy edge case, so I've added it to the list of slotted class caveats. Thank you for reporting!
