### ISSUE TITLE
New attrs release with Python 3.12 support

### ISSUE THREAD

**Issue by Jamim** [python-attrs/attrs#1212]
Hello @hynek,

Thank you for all your work on this fundamental project! 🙇🏻‍♂️

It's been a while since Python 3.12 support [was declared](https://github.com/python-attrs/attrs/commit/d538cba50cac2a4ec93ed24a835e043cd50fe21e#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R24). Python 3.12 was released recently, so it would be great to have a new version of `attrs` with official support for 3.12 available on [PyPI](https://pypi.org/project/attrs/).
I'll be happy to help if there are any blockers, just let me know.

Thanks in advance!

**Comment by hynek** [comment]
I'll try to get a release out before new year, but 3.12 support is only a matter of metadata. I'm running attrs on 3.12 in prod just fine. :)

**Comment by hynek** [comment]
attrs 23.2.0 is on PyPI – happy new year's eve everybody! 🤓
