### ISSUE TITLE
Feature request: Option for "soft" frozen classes in attrs?

### ISSUE THREAD

**Issue by ShaiAvr** [python-attrs/attrs#1219]
I recently discovered this library and it looks awesome. However, there is a pattern I use quite often that doesn't seem to be supported easily with *attrs*. I often need an immutable slotted class that will be used very often in my code base for calculations like a `Color` class with `r`, `g`, `b`, and `a` attributes and a bunch of methods to convert to and from different color formats and make calculations related to colors or a `Vector` class with `x`, `y`, `z` attributes with a bunch of vector operations. I think classes like these should be slotted because the user could create a dozen instances and access their attributes very often, so the performance benefits of a slotted class are really handy, and they should be immutable because it makes them much easier to deal with.

Without *attrs* I'd usually use "soft" immutability. In other words, I'd define the attributes as "private" and provide properties to access them. Something like this:
```python
class Color:
    __slots__ = ("_r", "_g", "_b", "_a")

    _r: float
    _g: float
    _b: float
    _a: float

    def __init__(self, r: float, g: float, b: float, a: float = 1.0) -> None:
        self._r = r
        self._g = g
        self._b = b
        self._a = a

    @property
    def r(self) -> float:
        return self._r

    @property
    def g(self) -> float:
        return self._g

    @property
    def b(self) -> float:
        return self._b

    @property
    def a(self) -> float:
        return self._a
```
In my opinion, if the user really wants to break immutability, I am not going to stop him. I did my job by declaring the attributes with a leading underscore which signals to the user that he shouldn't mess with these attributes. No matter how many security layers I put to prevent the object's mutation, it's always possible to break them in Python if the user tries hard enough, so I might as well give up the hassle and just inform the user that he shouldn't do that. A user who tries to mutate an object despite my warnings is the sole responsible for anything that happens in his code. This is also the reason I prefer a single leading underscore as opposed to double leading underscores.

In *attrs*, I'd use:
```python
from attrs import define


@define(slots=True, frozen=True)
class Color:
    r: float
    g: float
    b: float
    a: float = 1.0
```
Obviously, much more concise than a handwritten class. My problem with this is that according to the [docs](https://www.attrs.org/en/stable/how-does-it-work.html#immutability), *attrs* implements immutability by overriding the `__setattr__` method and raise an error from there. This is quite reasonable until you realize it requires some hacks to instantiate an object in the first place. In the case of a slotted class, it resorts to using `object.__setattr__()` to instantiate objects which according to the same doc is (still) slower than a plain assignment. The doc goes on to summarize that I should avoid instantiating lots of frozen slotted classes in performance-critical code. This is very disappointing for me because I think the whole idea of immutable slotted classes is to have light, easy to create and easy to replace objects that I can instantiate lots of without worrying about performance (basically a much better alternative to `namedtuple`).

As I said before, I usually like to just mark the attributes with a leading underscore and provide properties to read them instead of trying really hard to force immutability and I think it's a good solution for most cases, especially since it doesn't compromise on performance. I think we should add the ability to create such classes when requesting `frozen=True` instead of overriding `__setattr__` and using hacks to instantiate objects. Perhaps we could add a flag to `define` called `soft_frozen` which implements this soft immutability with properties and attributes with a leading underscore when set to `True` and uses the original `__setattr__` technique when set to `False`. Setting its default value to `False` will preserve compatibility and allow the users to explicitly request soft immutability for performance-critical code.

**Comment by hynek** [comment]
I mean if you're fine with typing-level freezing, maybe just do <https://threeofwands.com/attra-iv-zero-overhead-frozen-attrs-classes/>?

**Comment by ShaiAvr** [comment]
@hynek That's a nice idea, but I still think there should be *some* freezing in runtime. I'd really appreciate it if my class told me that I shouldn't assign its attributes even if it tells me by convention.

**Comment by hynek** [comment]
The question is whether your properties/descriptors don't destroy much more performance than the usage of `__setattr__` in `__init__`. I'm unconvinced that trade-off would be worth it.

**Comment by ShaiAvr** [comment]
I just tested it with these two classes:
```python
from attrs import define

class ManualColor:
    __slots__ = ("_r", "_g", "_b", "_a")

    _r: float
    _g: float
    _b: float
    _a: float

    def __init__(self, r: float, g: float, b: float, a: float = 1.0) -> None:
        self._r = r
        self._g = g
        self._b = b
        self._a = a

    @property
    def r(self) -> float:
        return self._r

    @property
    def g(self) -> float:
        return self._g

    @property
    def b(self) -> float:
        return self._b

    @property
    def a(self) -> float:
        return self._a


@define(slots=True, frozen=True)
class AttrsColor:
    r: float
    g: float
    b: float
    a: float = 1.0


c1 = ManualColor(0.5, 0.8, 1)
c2 = AttrsColor(0.5, 0.8, 1)
```
The results are:
```
%timeit ManualColor(0.5, 0.8, 1): 170 ns ± 1.89 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
%timeit AttrsColor(0.5, 0.8, 1): 495 ns ± 4.49 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

%timeit c1.r: 65.9 ns ± 0.961 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
%timeit c2.r: 17.1 ns ± 0.321 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)
```
The first two results are quite similar to the results in the docs, and accessing an attribute of an *attrs* frozen slotted class seems to be approximately 3 times faster than accessing a property of a manual written class. I guess the question is which operation is more frequent: Do we create and throw away many of these objects or do we access their individual attributes a lot?

I am actually not sure what is better in the long term. For my use case, I am making a little graphics engine, so I have a hot game loop that runs every frame to update the graphics and render them to the screen. I imagine that vector and color calculations are going to be very frequent in such a loop, and I don't know what is the best approach to achieve maximum performance.

**Comment by hynek** [comment]
If performance is paramount, your best approach is to enforce these kinds of contracts not at runtime, hence the link I gave you. It has literally zero overhead.

I’m gonna close this because as you noticed yourself there’s no clear answer and it’s definitely not a case to reimplement immutability based on descriptors. Feel free to ask more questions tho.
