### ISSUE TITLE
asdict does not call value_serializer on attrs objects in containers

### ISSUE THREAD

**Issue by dbramel** [python-attrs/attrs#1225]
**Bug Report**

When calling `asdict` recursively with a custom `value_serializer` function, the custom serializer is not called on attrs types that reside in any container type field. This is inconsistent, as the serializer is called on attrs types that are themselves fields of an attrs type. I.e. if you have an attrs type with two fields, one of which is an attrs type and one which is a list of attrs types, the custom serializer will be called on the non-list field but not on the objects in the list.

This is also inconsistent with the way non-attrs types are handled, as the custom serializer will be called on them regardless of whether they are direct fields or held within container fields.

**To Reproduce**

Create an attrs type that contains other attrs types both directly and in a container. Create a custom serializer function that tracks which objects were passed to it:

```
import attrs
from typing import Any

@attrs.frozen
class MyAttrsType:
    name: str

    def serializer_was_called(self) -> None:
        print(f"Serializer func was called on Attrs type {str(self)}")

    def __str__(self) -> str:
        return f"MyAttrsType[{self.name}]"

@attrs.define
class HasContainer:
    part: MyAttrsType
    non_attrs_thing: str
    parts_list: list[Any] = attrs.field(factory=list)

    def __str__(self) -> str:
        parts_str = [str(part) for part in self.parts_list]
        parts_str.append(str(self.part))
        return f"Container{parts_str}"

attrs_objects_that_serializer_was_called_on = set()

def val_serializer_func(inst, attr, val) -> Any:
    try:
        val.serializer_was_called()
        attrs_objects_that_serializer_was_called_on.add(val)
    except AttributeError:
        print(f"Serializer func was called on non-attrs {str(val)}")
        pass
    return val

def test_attrs_bug():
    attrs_obj_A = MyAttrsType("a string A")
    attrs_obj_B = MyAttrsType("a string B")
    attrs_obj_C = MyAttrsType("a string C")

    cont = HasContainer(attrs_obj_A, "a string D")

    cont.parts_list.append(attrs_obj_B)
    cont.parts_list.append("a string E")
    cont.parts_list.append(attrs_obj_C)

    print(f"Calling asdict on {str(cont)}")
    attrs.asdict(cont, recurse=True, value_serializer=val_serializer_func)

    assert attrs_objects_that_serializer_was_called_on == {
        attrs_obj_A,
        attrs_obj_B,
        attrs_obj_C,
    }
```

**Expected behavior:**

When calling `asdict` recursively with the custom serializer we expect that all objects will be passed to the serializer as values. I.e. the assertion in the above `test_attrs_bug` should pass

**Actual behavior:**

Attrs objects within a container field are not passed to the serializer as values. The assertion in `test_attrs_bug` fails because `attrs_obj_B` and `attrs_obj_C` are not present.

**Environment:**

python 3.10.13
attrs 23.2.0
GNU/Linux

**Comment by Tinche** [comment]
> Attrs objects within a container field are not passed to the serializer as values.

That's correct, the `value_serializer` hook won't get passed each list element as a `val`; it'll get passed in the entire list. Then later, each list elements get passed in as the `inst` parameter (with their own field values as `val`). Note that the [documentation](https://github.com/python-attrs/attrs/blob/3e868366adc984b34962f9c669c5d89d3c0c4c63/src/attr/_funcs.py#L37) states the `value_serializer` will get called for _attrs_ classes and _dicts_ only.

So the chain of invocations here is:

```
1. HasContainer(part=MyAttrsType(name='a string A'), non_attrs_thing='a string D', parts_list=[MyAttrsType(name='a string B'), 'a string E', MyAttrsType(name='a string C')])
Attribute(name='part', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class '__main__.MyAttrsType'>, converter=None,
kw_only=False, inherited=False, on_setattr=None, alias='part')
MyAttrsType(name='a string A')
2. MyAttrsType(name='a string A')
Attribute(name='name', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'str'>, converter=None, kw_only=False,
inherited=False, on_setattr=None, alias='name') a string A
3. HasContainer(part=MyAttrsType(name='a string A'), non_attrs_thing='a string D', parts_list=[MyAttrsType(name='a string B'), 'a string E', MyAttrsType(name='a string C')])
Attribute(name='non_attrs_thing', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'str'>, converter=None,
kw_only=False, inherited=False, on_setattr=None, alias='non_attrs_thing') a string D
4. HasContainer(part=MyAttrsType(name='a string A'), non_attrs_thing='a string D', parts_list=[MyAttrsType(name='a string B'), 'a string E', MyAttrsType(name='a string C')])
Attribute(name='parts_list', default=Factory(factory=<class 'list'>, takes_self=False), validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}),
type=list[typing.Any], converter=None, kw_only=False, inherited=False, on_setattr=None, alias='parts_list')
[MyAttrsType(name='a string B'), 'a string E', MyAttrsType(name='a string C')]
5. MyAttrsType(name='a string B')
Attribute(name='name', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'str'>, converter=None, kw_only=False,
inherited=False, on_setattr=None, alias='name') a string B
6. None None a string E
7. MyAttrsType(name='a string C')
Attribute(name='name', default=NOTHING, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'str'>, converter=None, kw_only=False,
inherited=False, on_setattr=None, alias='name') a string C
```

That looks ok to me.

Note: if you need advanced serialization, look at https://catt.rs. It's a related project from the same organization.

**Comment by dbramel** [comment]
I guess that's fair, as the documentation does say:
>     :param Optional[callable] value_serializer: A hook that is called for every attribute or dict key/value. 
and my repro example uses a list.

But if you replace 'list' with 'dict' (and make appropriate changes) you'll find the same thing happens. `value_serializer` is NOT called for dict values that are attrs classes, which is definitely in contravention of the docs. This happens [for the same reason](https://github.com/python-attrs/attrs/blob/3e868366adc984b34962f9c669c5d89d3c0c4c63/src/attr/_funcs.py#L135) it happens with list items: `_asdict_anything` shortcuts back to `asdict` for any value that is an attrs class without calling `value_serializer`.

Whether or not it's in contravention of the docs, I'd argue this behavior makes the `value_serializer` basically useless as you have to invoke all kinds of crazy logic involving field type and manual container unrolling to get a consistent serialization path.

**Updated repro:**
```
import attrs
from typing import Any

@attrs.frozen
class MyAttrsType:
    name: str

    def serializer_was_called(self) -> None:
        print(f"Serializer func was called on Attrs type {str(self)}")

    def __str__(self) -> str:
        return f"MyAttrsType[{self.name}]"


@attrs.define
class HasContainer:
    part: MyAttrsType
    non_attrs_thing: str
    parts_dict: dict[str, Any] = attrs.field(factory=dict)

    def __str__(self) -> str:
        parts_str = {str(k): str(v) for k,v in self.parts_dict.items()}
        return f"Container{parts_str} + {str(self.part)}"


attrs_objects_that_serializer_was_called_on = set()


def val_serializer_func(inst, attr, val) -> Any:
    try:
        val.serializer_was_called()
        attrs_objects_that_serializer_was_called_on.add(val)
    except AttributeError:
        print(f"Serializer func was called on non-attrs {str(val)}")
        pass
    return val


def test_attrs_bug():
    attrs_obj_A = MyAttrsType("a string A")
    attrs_obj_B = MyAttrsType("a string B")
    attrs_obj_C = MyAttrsType("a string C")

    cont = HasContainer(attrs_obj_A, "a string D")

    cont.parts_dict["B"] = attrs_obj_B
    cont.parts_dict["E"] = "a string E"
    cont.parts_dict["C"] = attrs_obj_C

    print(f"Calling asdict on {str(cont)}")
    attrs.asdict(cont, recurse=True, value_serializer=val_serializer_func)

    assert attrs_objects_that_serializer_was_called_on == {
        attrs_obj_A,
        attrs_obj_B,
        attrs_obj_C,
    }
```

**Comment by hynek** [comment]
> Whether or not it's in contravention of the docs, I'd argue this behavior makes the `value_serializer` basically useless as you have to invoke all kinds of crazy logic involving field type and manual container unrolling to get a consistent serialization path.

You're right on the money here. The problem with `addict`, at this point, is that it exists in some kind of grey area between the simple original purpose and full-on serialization – and we noticed the problem too late.

Whenever someone bumps into the edges of its capabilities, the natural reaction is to add "just this one more thing". Unfortunately, it turned out the number of "just one more things" is virtually infinite, as you can see if you count the numbers of cattrs. This topic is extremely complex and we should've never added `value_serializer` etc in the first place.

*attrs* exists in this field of tension between a class toolkit it wants to be and just enough serialization everyone would like to have.

Either way I'm sorry, and the answer to more elegant code is right here in the *attrs* org: https://github.com/python-attrs/cattrs
