### ISSUE TITLE
pyreverse with attrs.org

### ISSUE THREAD

**Issue by txemi** [python-attrs/attrs#1231]
I am using pyreverse for drawing charts on python dependencies, unfortunately attrs.org class data members are not recognized by pyreverse as they are not declared as expected. Has anybody noticed on this and found some workarround? It is a pity not enjoying this feature.

Thanks,

Link to same issue on pyreverse site:
https://github.com/pylint-dev/pylint/issues/9407

**Comment by hynek** [comment]
I see you've opened an issue on pylint/pyreverse too, which seems the correct place. I'll close this but if they need any assistance they can open a specific issue, of course.
