### ISSUE TITLE
Private field is not understood by VScode.

### ISSUE THREAD

**Issue by pinkfrog9** [python-attrs/attrs#1239]
Given the following code,
```
@define
class X:
  _foo:int
```

The following initialization code will run without error, 
```
x = X(foo=3)
```.

However, Vscode does not understood `foo` is valid in `X(foo=3)`. It will auto complete with `X(_foo)` instead.

**Comment by hynek** [comment]
Unfortunately, we have no influence on what VS Code / Pylance / Microsoft do. You might have some luck by aliasing the field name explicitly using the *alias* argument: https://www.attrs.org/en/stable/init.html#private-attributes-and-aliases

**Comment by pinkfrog9** [comment]
yes, using "alias" worked. thanks.

**Comment by pinkfrog9** [comment]
I am curious since instructing with an "alias" field works. 

Can we do some control on the "@define" alone, so that the pylance can understand the transformation of private fields (removing the prefixing _)?

**Comment by hynek** [comment]
Sadly, no. This is something that has to implemented on the Pyright/Pylance side and generally speaking, they only want to implement whatever is officially defined for dataclass transforms. Which is true for _alias_: https://peps.python.org/pep-0681/#field-specifier-parameters
