### ISSUE TITLE
Is it possible to validate all attribute types by default?

### ISSUE THREAD

**Issue by paketb0te** [python-attrs/attrs#1254]
Sorry if this is a dumb question, I have read the [docs section on validators](https://www.attrs.org/en/stable/init.html#validators) and searched the github issues, but did not find an answer...

Is there a way to make a class use the `instance_of` validator on all its attributes, without specifying the validator separately for each attribute?

So instead of doing this:

```py
@define()
class Foo:
    bar: str = field(validator=instance_of(str))
    baz: int = field(validator=instance_of(int))


foo = Foo(bar=False, baz=123)
# TypeError: ("'bar' must be <class 'str'> (got False that is a <class 'bool'>).", ...)
```

Is there something like this:

```py
@define(validate_attribute_types=True)
class Foo:
    bar: str
    baz: int


foo = Foo(bar=False, baz=123)
# TypeError: ("'bar' must be <class 'str'> (got False that is a <class 'bool'>).", ...)
```

The first example obviously works just fine and does exactly what one would expect, I just imagine that there are a lot of cases where people want the `instance_of` validator on all attributes, and since `attrs` is all about removing boilerplate, I guess I am not the first one who would have a "validate types by default" option :)

In any case, thanks a lot for this great library!

**Comment by hynek** [comment]
No it's not and this is a special case of the popular genre "why does attrs not just use type annotations". :) Unfortunately, it's much more complicated once you move past str/int so we recommend [cattrs](https://catt.rs/en/stable/) for that.

**Comment by paketb0te** [comment]
> special case of the popular genre "why does attrs not just use type annotations"

Now that you mention it, yeah...

OT: New video when? ;)

**Comment by hynek** [comment]
> OT: New video when? ;)

oh man i'm just desperately catching up with FOSS, so don't hold your breath. 🙈 it's probably gonna be something on the simpler side (avoiding "shorter" on purpose) so it's out before xmas 🤪
