### ISSUE TITLE
Define defaults for subclass that uses validator of parent class?

### ISSUE THREAD

**Issue by my1e5** [python-attrs/attrs#1259]
I am trying to create subclasses of a parent class which have their own default values but use the validator defined in the parent class. Is this possible? Here is a simple working example:

```py
from attrs import define, field, validators

@define(kw_only=True)
class Vehicle:
    num_wheels: int = field(validator=validators.instance_of(int))

    @num_wheels.validator
    def validate_num_wheels(self, attribute, value) -> None:
        if value <= 0:
            raise ValueError("Must be greater than 0")
```
And here are some subclasses which I know don't work - but hopefully illustrate what I want to do.
```py
@define
class Car(Vehicle):
    num_wheels: int = field(default=4) #! This doesn't work


@define
class Motorbike(Vehicle):
    @num_wheels.default #! This doesn't work either
    def default_num_wheels(self) -> int:
        return 2
```

I basically want to protect against a user doing `Car(num_wheels=3.14)` or `Car(num_wheels=-1)` accidently. And also have this work for `Motorbike` etc. But I want `Car()` and `Motorbike()` to return default values defined in the subclass. Is this possible?

**Comment by hynek** [comment]
I have answered in https://stackoverflow.com/a/78158263/476759 – tl;dr: #637, but you might get around it.
