### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by Tinche** [python-attrs/attrs#127]
I've built myself CPython 3.6rc2 on my Linux box. Good news, all tests pass!

3.6 has some new and interesting features which we might want to support or utilize in some way. Let's use this issue to comment on them.

Looking at https://docs.python.org/3.6/whatsnew/3.6.html, two immediately jump out:

* The class attribute definition order is now preserved. (https://docs.python.org/3.6/whatsnew/3.6.html#whatsnew36-pep520) Maybe we can skip using Counting attributes on 3.6? Unsure if any gains are worth the increase in complexity or if there are edge cases, but it may be possible.

* syntax for variable annotations (https://docs.python.org/3.6/whatsnew/3.6.html#pep-526-syntax-for-variable-annotations) means this is now possible:

    ```
    @attr.s
    class A(object):
        """A trivial class."""
        a: int = attr.ib()
    ```

    The type annotation is available in `A.__annotations__` but I feel like it should be in the `Attribute` object for a, too. Either in the attribute metadata, or we can have an optional 'annotation' attribute on `Attribute` instances, available only on 3.6+.

**Comment by bluetech** [comment]
`typing.NamedTuple` does something like this since Python 3.6: https://docs.python.org/3/library/typing.html#typing.NamedTuple

Quoting the link:

```python
class Employee(NamedTuple):
    name: str
    id: int
```

This is equivalent to:

```python
Employee = collections.namedtuple('Employee', ['name', 'id'])
```

**Comment by Infernion** [comment]
Actually I played with variable annotations a little bit https://github.com/Infernion/annots

**Comment by hynek** [comment]
So I’m not enthusiastic about dropping CountingAttr due to the unnecessary complexity but since Python is starting to have typing baked into the language, attrs should follow suite.   Maybe open a new ticket to track that and close this one?

**Comment by Tinche** [comment]
Ok, I'll make a new issue for annotations. Another thing that occured to me was maybe using f-strings for the repr, if it's significantly faster. I'll have to benchmark it.

**Comment by Tinche** [comment]
Some quick benchmarks show that f-strings are ~40% faster than str.format, but I don't think it'd make a big difference since our repr generation does a lot of work regardless. So let's disregard this for now.
