### ISSUE TITLE
modulenotfounderror: no module named attrs for version 21.2.0 

### ISSUE THREAD

**Issue by mkdsfm** [python-attrs/attrs#1283]
Unable to obtain attrs library version 21.2.0. No mention of this version not working was found in the documentation. Only version 21.1.0 was mentioned. The modulenotfounderror error only occurs with version 21.2.0

**Comment by hynek** [comment]
*attrs* 21.2.0 is right there: https://pypi.org/project/attrs/21.2.0/

You seem to have some issues with your packaging that we cannot affect.
