### ISSUE TITLE
Unpack List[<some attrs class>]

### ISSUE THREAD

**Issue by emmeowzing** [python-attrs/attrs#1298]
I'm trying to get code like the following to work on [a PR](https://github.com/premiscale/premiscale/blob/e4686a66524c7a25b9eb973f9ed1d7704a99506e/src/premiscale/hypervisor/qemu_data.py#L103) (also, https://github.com/premiscale/premiscale/pull/202) in one of my projects and it doesn't seem to unpack the dict into a `List[<attrs type>]`.

```python
@define
class vCPU:
    """
    A dataclass for storing CPU statistics.
    """
    state: int

@define
class Net:
    """
    A dataclass for storing network interface statistics.
    """
    name: str

@define
class DomainStats:
...
    # vCPU
    vcpu: List[vCPU]
...
    # net
    net: List[Net]
...
```

I thought the following would work ~

https://www.attrs.org/en/stable/api.html#attrs.resolve_types

to resolve the types properly, but it doesn't appear to work this way by default. Is there an established pattern for unpacking into nested dataclasses when they may be encapsulated in iterable types (like `List[]`, `Tuple[]`, etc.).

**Comment by hynek** [comment]
I'm somewhat confused what you expect to happen. Could you give me a short example
[_Short, Self Contained, Correct, Example_](http://sscce.org) of what's happening and what's confusing about it?

**Comment by emmeowzing** [comment]
Sure! Sorry about that, I opened this Issue last night when I badly needed sleep.

```python
from typing import List
from attrs import define
from cattrs import structure, unstructure


@define
class A:
    x: int
    y: int


@define
class B:
    a: A
    b: List[A]


b = B(
    a=A(
        x=1, 
        y=2
    ),
    b=[
        A(
            x=3,
            y=4
        ),
        A(
            x=5,
            y=6
        )
    ]
)

#
print(b)

b_dict = {
    'a': {'x': 1, 'y': 2},
    'b': [
        {'x': 3, 'y': 4},
        {'x': 5, 'y': 6}
    ]
}

#
print(
    B(**b_dict)
)

#
print(
    structure(
        b_dict, 
        B
    )
)

#
print(b_dict)


# B(a=A(x=1, y=2), b=[A(x=3, y=4), A(x=5, y=6)])
# B(a={'x': 1, 'y': 2}, b=[{'x': 3, 'y': 4}, {'x': 5, 'y': 6}])
# B(a=A(x=1, y=2), b=[A(x=3, y=4), A(x=5, y=6)])
# {'a': {'x': 1, 'y': 2}, 'b': [{'x': 3, 'y': 4}, {'x': 5, 'y': 6}]}
```

I think I see what I'm doing wrong. I.e., I'm passing a dict like `**b_dict`, when I need to use `cattrs` like

```python
print(
    structure(
        b_dict, 
        B
    )
)
```
