### ISSUE TITLE
Composition of validators

### ISSUE THREAD

**Issue by cyli** [python-attrs/attrs#13]
I was going to write some composition validators, like `all` (all the given validators have to match), but the more I thought about it the more I basically want all the compositional elements in http://testtools.readthedocs.org/en/latest/for-test-authors.html#matchers.

I was wondering how you felt about adding a validator that took said matchers?  It would make it really easy for users to do custom validation, and [`testtool.matchers`](http://testtools.readthedocs.org/en/latest/for-test-authors.html#matchers) has pretty nice error reporting.

**Comment by hynek** [comment]
you mean like an adapter that takes and uses them?  sure why not.

**Comment by PsyMar** [comment]
yes!  I was just looking for this.  I was going to call it something like "and" but "all" is probably better.

**Comment by hynek** [comment]
So we have `and_()` (and syntactic sugar of just passing a list) now.  I feel like that’s enough for the official repo to have.  There’s a ton of validation frameworks and I really don’t want to commit to/bless any of them.

Closing for now.
