### ISSUE TITLE
Remove "enableExperimentalFeatures = true" from pyright config

### ISSUE THREAD

**Issue by erictraut** [python-attrs/attrs#1341]
I noticed that the pyproject.toml used in attrs contains the following:

```
[tool.pyright]
# We need epexrimental features for converters.
enableExperimentalFeatures = true
```

This comment was previously true, but this is no longer necessary. Now that the converters functionality is officially incorporated into the typing spec, it is no longer considered experimental. All versions of pyright from 1.1.373 onward support this functionality without setting the "enableExperimentalFeatures" flag to true.

I noticed that this configuration flag was enabled because I'm implementing some new experimental features in pyright, and the regression tests that I run on attrs triggered usage of the new experimental feature.

**Comment by hynek** [comment]
thanks for letting us know
