### ISSUE TITLE
converters are not executed during fields assignment for classes created by attrs.make_class

### ISSUE THREAD

**Issue by ngchihuan** [python-attrs/attrs#1375]
Hi @hynek,
I run into this problem with using converters for classes made by attrs.make_class.
Better explained with the following code.
Let me know if you need more information!

Python: 3.10
attrs version: 24.2.0

```python
C = attrs.make_class("C",{"x": attrs.field(default=0, converter=int)})
C(x="0")
type(x) == int
``` 

However, converter is not applied when fields are assigned after the initialization.
```python
C = attrs.make_class("C",{"x": attrs.field(default=0, converter=int)})
c= C()
c.x = "0"
type(c.x) == str
```

**Comment by hodgestar** [comment]
Just noting that one can work around this by specifying `on_setattr` explicitly:
```python
>>> from attrs import setters
>>> C = attrs.make_class("C",{"x": attrs.field(default=0, converter=int)}, on_setattr=DEFAULT_SETATTR)
>>> c = C("0")
>>> c.x
0
>>> c.x = "5"
>>> c.x
```
Although it took me a bit of digging in the source code to find that.

**Comment by hynek** [comment]
Unfortunately, that's not something we can change now anymore, so we'll improve the docs.

**Comment by ngchihuan** [comment]
Thanks @hynek for your reply. 
@hodgestar workaround suggestion works fine for us.

**Comment by hodgestar** [comment]
Thanks, @hynek. The documentation update looks great.
