### ISSUE TITLE
Cannot get attrs.Converter() with takes_self pass through mypy

### ISSUE THREAD

**Issue by nyoxi** [python-attrs/attrs#1378]
I've been playing with the `attrs.Converter()` but I am unable to get it type-checked with mypy when using `takes_self`. Now I am not considering (the obvious) `Unsupported converter, only named functions, types and lambdas are currently supported` error. What I am struggling with is how to annotate the self. The following code:

```
def str2int(s: str|int, self_: "C") -> int:
    return int(s)

@attrs.define
class C:
    x: int = attrs.field(
        converter=attrs.Converter(str2int, takes_self=True)
    )
```

Leads to the following error:

```
error: No overload variant of "Converter" matches argument types "Callable[[str | int, C], int]", "bool"  [call-overload]
note: Possible overload variants:
note:     def [In, Out] Converter(self, converter: Callable[[In], Out]) -> Converter[In, Out]
note:     def [In, Out] Converter(self, converter: Callable[[In, AttrsInstance, Attribute[Any]], Out], *, takes_self: Literal[True], takes_field: Literal[True]) -> Converter[In, Out]
note:     def [In, Out] Converter(self, converter: Callable[[In, Attribute[Any]], Out], *, takes_field: Literal[True]) -> Converter[In, Out]
note:     def [In, Out] Converter(self, converter: Callable[[In, AttrsInstance], Out], *, takes_self: Literal[True]) -> Converter[In, Out]
```

Is this just my own ignorance or an issue with attrs or mypy?

I am using:
* attrs 24.2.0
* mypy 1.13.0

**Comment by nyoxi** [comment]
I just noticed that the check passes with mypy 1.12.1 which may suggest a regression in mypy.

**Comment by nyoxi** [comment]
I forgot to circle back here. After playing a bit more with converters and validators I figured that the solution is actually pretty simple and straightforward:

```python
def str2int(s: str|int, self_: attrs.AttrsInstance) -> int:
    if not isinstance(self_, C):
        raise TypeError(f"Converter does not know how to work with {type(self_)}")
    # Now the type of `self_` is properly inferred as `C`
    return int(s)

@attrs.define
class C:
    x: int = attrs.field(
        converter=attrs.Converter(str2int, takes_self=True)
    )
```

I am closing the issue. If anyone things this is worth documenting I can prepare a pull request for that.

**Comment by filbranden** [comment]
Also possible to use [`typing.cast`](https://docs.python.org/3/library/typing.html#typing.cast) here.
