### ISSUE TITLE
type hinting with programmatically defined classes 

### ISSUE THREAD

**Issue by gvoysey** [python-attrs/attrs#153]
say i have a dict of things i'd like to become attributes, and i want to use the `make_class` feature to do so: 

```python3
adict = {'x':[1,2,3],
              'foo' : 'bar'}

some_instance  = attr.make_class(name='DictClass', attrs=adict)()
```

I'd like to have my IDE (in this case, pycharm) be able to provide the same sort of class memeber inspection that would be available if i had done:

```
@attr.s
class DictClass(object):
    x = attr.ib(default=[1,2,3])
    foo = attr.ib(default='bar')
```

Is this sort of thing possible?

**Comment by hynek** [comment]
You’d have to ask JetBrains I guess.

**Comment by hynek** [comment]
Closing since this is beyond our power.  Maybe class hints/mypy will help with that eventually tho.
