### ISSUE TITLE
Metaclass lost with slots=True 

### ISSUE THREAD

**Issue by YevIgn** [python-attrs/attrs#154]
Hello.

Using a metaclass with slots=True, e.g.
```
@attr.s(slots=True)
class A(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def f(self):
        pass
```
Will lead to `A` being instantiable and `type(A)` being `<class 'type'>` (unlike the case with slots=False), as for slots to work the new class is generated in [_make.py](https://github.com/python-attrs/attrs/blob/master/src/attr/_make.py#L365) with:

`cls = type(cls.__name__, cls.__bases__, cls_dict)` [1]

This doesn't happen if this line is changed to:

`cls = type(cls)(cls.__name__, cls.__bases__, cls_dict)` [2]

With this change `type(A)` is `<class 'abc.ABCMeta'>` and A is no longer instantiable.
Can the class generation for slots be changed to something like [2] to avoid losing metaclasses or it is intentionally written as it is now and I am missing something?

**Comment by Tinche** [comment]
It's not intentional, it just hasn't come up until now. :)

Could you try applying the change, and if the tests pass contribute a PR? It'd be nice to add a test for this as well.

**Comment by YevIgn** [comment]
Opened PR. Tests pass on my machine. Sorry for the mess with commits (used wrong git config at first).
