### ISSUE TITLE
Attribute deprecation

### ISSUE THREAD

**Issue by sils** [python-attrs/attrs#166]
Might be nice to be able to deprecate members and actually whole classes in some way: `new = attr.ib(..., deprecates={'old': lambda old: old+'newstuff!'}`

**Comment by hynek** [comment]
That seems like a pretty fringe requirement to add to attrs’s API proper.

I’m having ideas about simplifying properties in attrs; maybe you’ll be able to build something on top of that.  Until then, I believe you can  implement something like that using the metadata API.
