### ISSUE TITLE
Add "list_of(type)" and "dict_of(key_type, val_type)" validators

### ISSUE THREAD

**Issue by sscherfke** [python-attrs/attrs#168]
`x = attr.ib(validator=instance_of(list))` is IMO not a very useful check, but `x = attr.ib(validator=list_of(type))` would be.

In a similar fashion we could also add a `dict_of(key_type, val_type)` validator. 

I can create a pull request if you like this idea.

**Comment by hynek** [comment]
We’re getting this request regularly.  You may want to look into the discussion around #158 to what I’m envisioning if you’d like to supply a solution.
