### ISSUE TITLE
Add support for converting back when using `astuple` or `asdict`.

### ISSUE THREAD

**Issue by ojii** [python-attrs/attrs#179]
attrs makes it very easy and convenient to build lightweight object mappers for databases etc, but when using certain types like enums, it can be a bit annoying/tricky to use `astuple` and `asdict`.

To convert an Enum from a datasource to an attrs attribute, you can simply use something like this:

```python
class Flags(Enum):
    on = auto()
    off = auto()

@attr.s
class Model:
    flag = attr.ib(convert=Flags)
```

With this example, `Model(Flags.on.value)` (as you would get from a database) would work, but `attr.asdict(Model(Flags.on.value))` has `Model.flag` set to the `Enum`, which can't be serialized by most things. It would therefore be very helpful if we could specify an `unconvert` that is used when you call `asdict` or `astuple`, so the model would look like:

```python
@attr.s
class Model:
    flag = attr.ib(convert=Flags, unconvert=lambda x: x.value)
```

Would such a feature be appropriate in attrs? I think I could implement it and provide a patch if this feature request is accepted.

**Comment by hynek** [comment]
This is the oldest open ticket on attrs: #12 

You may also be interested in [cattrs](https://cattrs.readthedocs.io/en/latest/index.html).

**Comment by ojii** [comment]
I tried to search but failed. Sorry for the duplicate and will have a look at cattrs.

**Comment by hynek** [comment]
no worries
