### ISSUE TITLE
set_run_validators really ought to be a context manager

### ISSUE THREAD

**Issue by glyph** [python-attrs/attrs#188]
`decimal.Decimal("99.999999999999999999999999999999999999999999")` percent of the time (avoiding floating-point for precision here) when you disable validators you should only be doing it for a little while.  Therefore the primary interface to disable validation should be something like:

```python
with attr.validators.disabled():
    ...
```

to avoid accidentally disabling validation for an entire program lifetime.

**Comment by matthayes** [comment]
Similarly it would be useful to be able to disable automatic validation that currently runs in `__init__`, perhaps as another flag alongside `frozen` and `slots`.  I have a situation where I need to do this and I had to end up writing a separate validation method outside of `attrs`.

**Comment by matthayes** [comment]
I added a PR for my suggestion: #233

**Comment by hynek** [comment]
Fixed in #859!
