### ISSUE TITLE
17.1.0 breaks passing `default` to `Attribute` by keyword

### ISSUE THREAD

**Issue by exarkun** [python-attrs/attrs#194]
txaws has some code that constructs `Attribute` directly (it is public, after all).  It does so by passing a value for the default parameter by keyword (it is public, after all).

https://github.com/twisted/txaws/blob/8127b45978aa7b91e65eae15546a63440932b57f/txaws/client/_validators.py#L46-L54

This worked prior to 17.1.0 but no longer does.

**Comment by Tinche** [comment]
Hm, I think this can be reverted.

**Comment by Tinche** [comment]
I pushed a fix for this into #193.

**Comment by hynek** [comment]
In our defense, the docs excplitly says you should never instantiate it yourself.  :-|

But yeah we'll fix it.

**Comment by exarkun** [comment]
Please don't make me read a big pile of docs just to find out that `x.Y` in your package isn't actually public even though it follows the public naming convention. :/  If I did that I wouldn't have any time left in my life to do any other things.

**Comment by hynek** [comment]
Serious question: how do you designate something to be public to read/inspect but private to create/write in an other way than docs?

**Comment by exarkun** [comment]
Make the constructor private.  So, for example, have `IAttribute` (self-evidently public) telling people what they can read from a thing and have an `_Attribute` (self-evidently private) type that implements it.

**Comment by hynek** [comment]
fixed in #193
