### ISSUE TITLE
Custom __init__ with frozen=True requires object.__setattr__

### ISSUE THREAD

**Issue by jtratner** [python-attrs/attrs#196]
Context, I have a class like this:

```
@attr.s(init=False)
class SomeConfig(object):
    basedir = attr.ib()
    name = attr.ib()

    def __init__(self, basedir, name=None):
        self.basedir = os.path.normpath(basedir)
        self.name = name or os.path.basename(self.basedir)
``` 

I'd like to make it frozen so it can be hashable; however, to do that requires using `object.__setattr__` as stated in #120.

Would you folks be open to a doc note about this just for clarity to users?

(I wasn't sure whether to comment on #120 or open up something separate, but since this is somewhat distinct, I figured I'd open a separate one.)

**Comment by hynek** [comment]
I’ve added a note to the docs, does that look good enough for you?

**Comment by jtratner** [comment]
yeah looks good - maybe just add something about `__init__` there so it's nicely googleable?

Thanks for responding so quickly! :)
