### ISSUE TITLE
Allow repr (+ str?) to take callables

### ISSUE THREAD

**Issue by Julian** [python-attrs/attrs#212]
It would be useful to be able to pass in a callable to do `repr`'ing of attributes.

For me this happens if I want to present a value in the repr differently than just `repr(foo)`, which is sometimes useful, especially if the "different way" is to use e.g. `reprlib.repr` to do auto-truncation of long values.

Being able to pass in callables to the `repr` argument seems at first glance like a reasonably easy way to do that.

E.g.

`attr.ib(repr=reprlib.repr)`

and

`attr.ib(repr=lambda value: repr(value) * 12)`

You could preserve backwards compatibility by having True be equivalent to `repr`, and False be a sentinel (which you need anyways).

I think this could also satisfy #41, if you do the same to `attr.s`, and then provide an `attr.simple_repr`, so you'd do `attr.s(repr=attr.simple_repr)` and get the normal bracket repr instead of the eval one.

**Comment by blueyed** [comment]
See https://github.com/python-attrs/attrs/issues/224#issuecomment-319078193 for a patch to support a callable with `repr`.

**Comment by Tinche** [comment]
This is an interesting idea.

I think our repr support can be improved in any case; we're doing more work in the method that is generally needed, so it can be sped up by eval-ing a tailored function. Part of this work can be changing the `Attribute.repr` type to essentially be `Union[bool, Callable[[], str]` (so, either a boolean or a callable) and applying the callable when `__repr__`-ing.

**Comment by The-Compiler** [comment]
Another use case where this is useful are numbers which you'd like to show in hexadecimal (`modifiers = attr.ib(repr=lambda mod: hex(int(mod)))`, or PyQt (not Python) enum values where you want to get a human-readable value instead of an int.

**Comment by nvgoldin** [comment]
Another use case I have is when you have  a list attribute and you'd like `__repr__` to print out only the list length (for example in cases where it is extremely large).

Would be happy to know if there is another way to do it.

**Comment by gimbo** [comment]
I've created a small extension which provides callable reprs and allows titles to be overridden too (e.g. for the length case cited above): [attrs_flexible_reprs.py](https://gist.github.com/gimbo/19f1fede170090fdf029a4f3f5c7fece)

Input/feedback welcomed.

**Comment by hynek** [comment]
@gimbo I think your flexible repr doesn’t take into account our recursion handler?

***

Re earlier comments, I wouldn’t make this issue depend on transforming our repr generator to code generation. It would be nice to have, but not required for fixing this particular issue.

**Comment by gimbo** [comment]
@hynek I'm sure you're right - it's very simplistic, just the simplest thing I came up with that scratched the itch I had.

I haven't delved into the code of `attrs` at all - when you say "recursion handler" I'm guessing you mean something to handle the case where a class `A` has a field also of type `A`? Certainly my code doesn't handle that gracefully, it seems. Perhaps I'll take a look at what `attrs` does by default and try to upgrade. :-) Thanks!

**Comment by hynek** [comment]
Glyph has recently taught our repr to detect loops in definitions so it doesn’t run into max recursion error. You'd have to look at the current code and shoehorn the callable thing into it.

**Comment by wbolster** [comment]
This is similar (identical?) to #567, and #568 adds support for this.

**Comment by hynek** [comment]
Took only two years!!!1!

**Comment by blueyed** [comment]
@hynek 
Almost like good wine!
