### ISSUE TITLE
make __repr__ consistent with __init__

### ISSUE THREAD

**Issue by kurtbrose** [python-attrs/attrs#213]
repr should where possible round-trip to re-create the same object

currently, repr() of an attrs object with underscore prefixed fields gives you something that cannot round-trip

maybe there is a good reason it is this way, I'm raising the issue in case it was an oversight

```
>>> import attr
>>> @attr.s
... class Foo(object): 
...    _bar = attr.ib()
...    _baz = attr.ib()
... 
>>> Foo(bar=1, baz=2)
Foo(_bar=1, _baz=2)
>>> Foo(_bar=1, _baz=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument '_baz'
```

**Comment by adrientetar** [comment]
This is like my one nitpick with attrs thus far, fixing it would make things consistent indeed.

**Comment by hynek** [comment]
It’s not something we can fix in hindsight tho (it is on purpose fwiw).  This is sort of a sub-problem of #212 that probably should be taken into account there.

**Comment by adrientetar** [comment]
> (it is on purpose fwiw)

Do you mean showing the underscore in the repr is a feature? Why shouldn't it be consistent with ctor? (i.e., why would you remove the underscore from ctor but not from repr?) From a user perspective that makes a lot more sense, unless I'm missing something.

**Comment by hynek** [comment]
The argument could be summed as: there’s no such thing as a private argument but there totally is a thing as a private attribute.

Which is to say that the whole repr thing needs some re-thinking anyways, because maybe private attributes shouldn’t be shown at all?

**Comment by adrientetar** [comment]
Sometimes you want to have a custom read-only property that is set from ctor, like the path on disk of a data object. e.g. I wrote objects that open a font:

~~~python
font = Font(path="/here/it/is")
font.path
font.path = "foo" # error
font.__repr__() # Font(_path="/here/it/is") <--- the underscore here doesn't match ctor

font.save(newPath) # this will save and set the _path attribute
~~~

code is basically like this:

~~~python
class Font:
    _path = attr.ib()

    @property
    def path(self):
        return self._path
~~~

So I tend to think private attributes should be optionally shown in repr.

**Comment by kurtbrose** [comment]
A ton of objects have this great property where `eval(repr(foo)) == foo` which means you can copy + paste the object from one REPL to another, or notebook output back to a code cell.  Kind of a rough-and-ready pickle.

`attr` already recursively includes the `repr` of its children, it is really close to having this property.

Also, it is consistent with the standard library:

```
>>> eval(repr(1))
1
>>> eval(repr("cat"))
'cat'
>>> import collections
>>> nt = collections.namedtuple("nt", ('a', 'b'))
>>> eval(repr(nt(1, "cat")))
nt(a=1, b='cat')
```

**Comment by wsanchez** [comment]
Obviously this can't always be correct. For example:

```python
class Counter(object):
    _count: int = attribute()

    def count(self):
        self._count += 1
        return self._count
```

Here the generated repr would emit `Counter()` regardless of the state of the counter.  I think in these cases it's fine to have to write your own repr to emit `<Counter: 12>` or whatever.

**Comment by adrientetar** [comment]
The issue in #12 seems related to the same root cause: ctors remove underscores in arguments but asdict() keeps them in, meaning a class instance w them cannot be reconstructued from the generated dict.

IMO the underscores "removal" is useful feature but should be applied more consistently throughout.

**Comment by hynek** [comment]
Thanks to #212 everyone can have it their way now. We have different tickets for the underscore business.
