### ISSUE TITLE
Ability to tweak default comparison operations?

### ISSUE THREAD

**Issue by cournape** [python-attrs/attrs#216]
Because I write a lof ot py2/py3 code, I like to have my classes' comparison to raise a `TypeError` when comparing instances of different classes. Python 3 does that automatically if both side return `NotImplemented`, but python 2 does not. Would it make sense to allow people to opt-in for python3-like behaviour even on python 2 ? Or a more generic hook on generated comparison functions ?

**Comment by hynek** [comment]
Ooof very late, I'm super sorry. On the bright side: I don't think I want to add new Python 2.7 features in 2021. 😇
