### ISSUE TITLE
Allow to convert attribute value in `repr`

### ISSUE THREAD

**Issue by blueyed** [python-attrs/attrs#224]
For attributes like `UUID`, it would be nice to use `str` instead of `repr` for them in the generated `__repr__`.

It looks to be similar to the existing `convert`, which is used in the `__init__` method.

For Django models I am using the following (`convert_repr` being a new callback):
```
@attr.attributes(these={
    'id': attr.ib(),
    'uuid': attr.ib(convert_repr=str),
    …
}, init=False, cmp=False)
```

**Comment by blueyed** [comment]
Maybe `repr` could be a callback optionally?
`repr=True` would use `repr`, but you could use `repr=str` or any other callback then.

```diff
diff --git i/src/attr/_make.py w/src/attr/_make.py
index b22a3f8..3788bb6 100644
--- i/src/attr/_make.py
+++ w/src/attr/_make.py
@@ -537,7 +537,7 @@ def repr_(self):
 
         return "{0}({1})".format(
             class_name,
-            ", ".join(a.name + "=" + repr(getattr(self, a.name))
+            ", ".join(a.name + "=" + (repr if a.repr is True else a.repr)(getattr(self, a.name))
                       for a in attrs)
         )
     cls.__repr__ = repr_
```

**Comment by hynek** [comment]
Looks like a dupe of #212 ?

**Comment by blueyed** [comment]
Indeed.
