### ISSUE TITLE
cannot receive _id as __init__ parameter

### ISSUE THREAD

**Issue by sebastiandev** [python-attrs/attrs#227]
Im working with MongoDB and CouchDB and they have this _id field. I cant seem to find a way of allowing attrs to receive that field, since it automatically strips the underscore from the definition

```python
_id = attrib(default=str(uuid4()))
```

Is there a way of allowing params to include an underscore or by pass the automatic striping? it is very useful to be able to build entities like:

```python
doc = db.find_one(.....)
e = Entity(**doc)
```

**Comment by hynek** [comment]
Regardless of what attrs does about this in the future, I would recommend to have a factory method that *you* control.

Like: `e = Entity.from_db(doc)`

**Comment by Tinche** [comment]
You can also take a look at cattrs, it'll let you register a structure hook for loading your entities.

**Comment by sebastiandev** [comment]
Yea i ended up with a factory method. I'll check cattrs as well, thanks guys
