### ISSUE TITLE
__attrs_post_init__ is missing from API docs

### ISSUE THREAD

**Issue by akaptur** [python-attrs/attrs#228]
`__attrs_post_init__` does not have an entry on attrs.readthedocs.io - there's only a mention in the examples and a few asides in the API section. It would be great to have first-class treatment, including the signature (`self`), when it's called (after the object is fully initialized) and the problem that it's trying to solve.

**Comment by hynek** [comment]
Yes, that's absolutely something that's bothered me for a while!  Sadly I'm not sure *how* to do that since it's not our API so there's no RST/Sphinx primitives for it.  😞

I believe it's explained in the Examples section but I just couldn't find a good angle on it in the API section.
