### ISSUE TITLE
Easy way to close class to new attributes (perhaps with attr.evolve syntactic sugar)

### ISSUE THREAD

**Issue by wkretzsch** [python-attrs/attrs#231]
I'm not sure this is a feature or bug in `attrs`, but like all python classes, `attrs` classes are open to creation of new attributes:

```
import attr

@attr.s
class Test(object):
    pass

test = Test()
test.a = "bla"
test
# Test()
test.a
# 'bla'
```

## Problem

It would be nice to be able to close a class to new attributes for two reasons:

1. Sometimes I like to pass around data structures in my scientific analyses.  I use classes for that purpose and I find it very helpful to have one place where all possible attributes of the class are defined.
2. It is a common error mode of mine that I misspell an attribute when I assign to it, and then I'm off bug hunting for a while until I find the typo.  Sure, modern IDE's like Pycharm will highlight these kinds of mistakes, but it would be nice to be able to use a basic editor on some python code without having the feeling that I'm walking on a tightrope without a net...

Currently I use this code to close a class to new attributes:

```
class FrozenClass(object):
    __isfrozen = False

    def __setattr__(self, key, value):
        if self.__isfrozen and not hasattr(self, key):
            raise TypeError("Cannot set {}: {} is a frozen class".format(key, self))
        object.__setattr__(self, key, value)

    def _freeze(self):
        self.__isfrozen = True
```

## Other considerations

1. I realize that `attrs` has a `frozen=True` option, but that also closes an object to reassigning attributes.  Sure, I could use something like `i1 = attr.evolve(i1, y=3)` for attribute assignment, but that's quite clunky.  I guess what I'm asking for is a class initialization flag that wraps all attribute assignments of a frozen class with `attr.evolve`?
2. There is another feature request (https://github.com/python-attrs/attrs/issues/133) to freeze individual attributes, but that feature is orthogonal to what I am proposing.

**Comment by wkretzsch** [comment]
In  regards to point 1. of "Other considerations", it looks like assigning to `self` inside a method [does not do what I hoped it would](https://stackoverflow.com/questions/1216356/is-it-safe-to-replace-a-self-object-by-another-object-of-the-same-type-in-a-meth) -,-. That is, `self = attr.evolve(self, name=value)` would not work...

**Comment by wkretzsch** [comment]
How about something a long the lines of this?

```
class A:
    def __setattr__(self, name, value):
        if name in __dict__:
            # set attribute here
            # Not sure how to do that in attr
        else:
            raise ClosedInstanceError('{} is closed to new attributes'.format(self.__class__.__name__))
```

**Comment by hynek** [comment]
That honestly sounds more like a separate decorator?  Your implementation for example doesn’t need access to the attributes at all?

**Comment by wkretzsch** [comment]
Good point! I'll have a go at that.

**Comment by wkretzsch** [comment]
In case anyone else would like to do the same thing, I modified [this code](https://stackoverflow.com/a/29368642/528691) to get:

```python
import attr
from functools import wraps

def closed_to_new_attrs(cls):
    cls.__frozen = False

    def frozensetattr(self, key, value):
        if self.__frozen and not hasattr(self, key):
            raise TypeError("Class {} is closed to new attributes. Cannot set {} = {}"
                            .format(cls.__name__, key, value))
        else:
            object.__setattr__(self, key, value)

    def init_decorator(func):
        @wraps(func)
        def wrapper(self, *args, **kwargs):
            func(self, *args, **kwargs)
            self.__frozen = True

        return wrapper

    cls.__setattr__ = frozensetattr
    cls.__init__ = init_decorator(cls.__init__)

    return cls
```

and it appears to work if I use it like this:

```python
@closed_to_new_attrs
@attr.s
class C(object):
    a = attr.ib()

c = C(a = "foo")
c.b = "bar"
# Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File "<stdin>", line 6, in frozensetattr
#TypeError: Class C is closed to new attributes. Cannot set b = bar

**Comment by Tinche** [comment]
Could you just use a slot class instead?

**Comment by wkretzsch** [comment]
I have not really used slots before, but it appears that you are correct!

```
>>> import attr
>>> @attr.s(slots=True)
... class C(object):
...     a = attr.ib()
... 
>>> a = C("bla")
>>> a
C(a='bla')
>>> a.b = 'blarb'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'C' object has no attribute 'b'
>>> 
```

**Comment by wkretzsch** [comment]
This should only work for classes that don't inherit from non-slot classes, but that's good enough for me at this point.
