### ISSUE TITLE
__slots__ and extra (non-attr.ib) attributes

### ISSUE THREAD

**Issue by aldanor** [python-attrs/attrs#242]
It'd be nice if it was possible for code like this to work:

```python
@attr.s(slots=True)
class Foo:
    x = attr.ib()

    def __attrs_post_init__(self):
        self.y = x + 42  # this would fail since @attr.s sets __slots__ = ['x']
```

... maybe something like `@attr.s(slots=['extra', 'slots'])`, in addition to just accepting `True` / `False`?

**Comment by RonnyPfannschmidt** [comment]
@aldanor wouldnt an `x = attr.ib(init=False)` already solve your problem ?

**Comment by aldanor** [comment]
You mean `y = attr.ib(init=False)`? Actually it does, yea! Closing then.
