### ISSUE TITLE
Old documentation versions unavailable

### ISSUE THREAD

**Issue by willvousden** [python-attrs/attrs#243]
The attrs.org site doesn't provide access to documentation for older versions of attrs.  I just get "permission denied":

http://www.attrs.org/en/16.3.0/

Similarly, the Read the Docs popup in the bottom-right doesn't list anything except the "latest" and "stable" versions:

![attrs](https://user-images.githubusercontent.com/152388/30202223-857c0fba-9475-11e7-8026-18b72c4a2e05.png)

Finally, the Github links in this popup are also broken, leading to 404 pages.

I can access older versions of the docs through the tags on Github, but this is a bit inconvenient (and the Sphinx references aren't correctly resolved when viewing on Github).

**Comment by hynek** [comment]
I think I've fixed it?

**Comment by willvousden** [comment]
Just saw this. Yep, it's fixed. Thanks!
