### ISSUE TITLE
attributes based on properties

### ISSUE THREAD

**Issue by blueyed** [python-attrs/attrs#245]
```python
import attr


@attr.s
class Line:
    line = attr.ib()
    counts = attr.ib(default=None)
    _parsed_line = None

    @property
    def counts(self):
        if not self._parsed_line:
            self._parsed_line = (1, 2)
        return self._parsed_line[0]


line = Line('foo')

print(line)
print(line.counts)
```

Currently this prints:
```
Line(line='foo')
1
```

But I like for it to print:
```
Line(line='foo', counts=1)
1
```

I.e. it should use the property in the `__repr__` output.

Is this possible already maybe?

**Comment by RonnyPfannschmidt** [comment]
as far as i can tell this crippled example hides the real use-case

please describe the real use-case, because this example is just horrifying

**Comment by RonnyPfannschmidt** [comment]
also note that due to how python works, attrs doesnt see the counts "attribute", only the property is visible

**Comment by blueyed** [comment]
My use case is to have attributes (that get reflected in `__repr__`, but I want to build them lazily, based on some other attributte).
I could use an validator for this maybe, but it should get done lazily.

**Comment by blueyed** [comment]
What is so horrifying about the example btw?  (it is a trimmed down example after all)

**Comment by blueyed** [comment]
I know that the property overwrites the attribute, it is just meant to illustrate the use case.
I think attr might provide support for some callback that is then used as a property or something similar.

**Comment by hynek** [comment]
Sounds like #212 all over again?

**Comment by blueyed** [comment]
Yes, or at least it is related somewhat in the end after all.

**Comment by zuckerruebe** [comment]
Could someone explain how to use https://github.com/python-attrs/attrs/issues/212 or https://github.com/python-attrs/attrs/pull/568, respectively, to include a "computed field" aka property in the generated `repr`, please? I can't see it...
