### ISSUE TITLE
Calling evolve without changes on an object with a dict attribute results in a shallow copy

### ISSUE THREAD

**Issue by jlitzingerdev** [python-attrs/attrs#250]
This is as much a question as a potential issue, but I didn't see a mailing list or alternate forum so I opted for an issue, apologies if that's wrong, feel free to close and redirect me elsewhere!

I have a use case where I needed to clone an object, `attr.evolve` looked like a good candidate for this.  My initial usage called evolve without any arguments, which led to a surprise when one of the attributes was a dictionary.
**attrs version**: 17.2.0
**Expectation**:  Calling evolve with an instance creates a new instance, regardless of specified changes.
**Observation**: Calling attr.evolve on an object with a dictionary attribute without specifying changes returned a new object using the same underlying attribute dictionary.

A (contrived) example is a little clearer:   Below, I was expecting a, b, and c to be unique, independent instances regardless of how evolve was called, was my expectation wrong?

```
import attr

@attr.s
class Foo(object):
    bar = attr.ib(default=attr.Factory(dict))

a = Foo()
a.bar[1] = 2

b = attr.evolve(a)
c = attr.evolve(a, bar={5:6})

assert a == b
assert c != a

b.bar[3] = 4

print("a={!r}".format(a))
print("b={!r}".format(b))
print("c={!r}".format(c))

assert c != a
assert a != b, "Curse ye, b changed a! a={!r}, b={!r}".format(a, b)
```

Output
```
a=Foo(bar={1: 2, 3: 4})
b=Foo(bar={1: 2, 3: 4})
c=Foo(bar={5: 6})
Traceback (most recent call last):
  File "evolve.py", line 25, in <module>
    assert a != b, "Curse ye, b changed a! a={!r}, b={!r}".format(a, b)
AssertionError: Curse ye, b changed a! a=Foo(bar={1: 2, 3: 4}), b=Foo(bar={1: 2, 3: 4})
```

**Comment by jlitzingerdev** [comment]
To clarify, while I do expect `a == b` after calling `evolve`, I assume value (not referential) semantics.  The "is" condition is that `a.bar and b.bar` are the same instance.  For example, if one adds:

```
assert b.bar is not a.bar
```
After the call to `evolve`, the assertion will fail.

Cheers!

**Comment by wsanchez** [comment]
Evolve did create a new instance, but they both reference the same mutable object, so changing that object indirectly effects both `a` and `b`.

Your stated expectation that each is a unique, independent instance is not incorrect.  However, your unstated expectation that evolve should make a (deep) copy of every attribute is not.

I tend to think that `replace`, as used in the `datetime` class, may have been a clearer name than `evolve`.

**Comment by jlitzingerdev** [comment]
@wsanchez  Sorry about that, my expectation was indeed not worded properly.

I expected a new instance (which was created) with attributes that were deep copies of the original instance's attributes (which didn't happen).

Is this working as intended then?

**Comment by wsanchez** [comment]
This is working as intended, yes.

Consider, for example, if `a` is a `Foo` instead of a `dict`.  How do you make a deep copy?  Note that event `dict.copy` will only make a shallow copy of the `dict`.

**Comment by jlitzingerdev** [comment]
Thanks for the clarification!
