### ISSUE TITLE
attr.NOTHING seems likely like it should be private

### ISSUE THREAD

**Issue by Julian** [python-attrs/attrs#254]
Is there a reason this is exposed? Seems like it's just attrs' internal fix for Python's no missing arg wart.

(I just found some [external] code that checks for whether a field default is `NOTHING`, which would have been more obviously wrong to the person who wrote it if it wasn't a thing they should have been touching).

**Comment by hynek** [comment]
Well it appears all over the API so I think it's correct to be public?  It gives us a language and people can use it to conditionally set attribute values…

**Comment by Julian** [comment]
Hmm interesting, so there's a reason an external user would want to touch that? What's conditionally setting attribute values?

**Comment by Tinche** [comment]
If you're inspecting the attributes for whatever reason, you need to know about attr.NOTHING, so it should be public. Inspecting the attributes is a very interesting use case; cattrs does it for sure.

**Comment by hynek** [comment]
That, and with conditionally I meant something like: `attr.ib(default=whatever or NOTHING)`.  You simply may want to be able to explicitly set a field to “not set”.

Closing now, feel free to discuss further once you arrive in Cape Town. :D
