### ISSUE TITLE
Apply convert/validator also when setting attributes later

### ISSUE THREAD

**Issue by blueyed** [python-attrs/attrs#256]
Based on the doc example:
```python
In [2]: import attr
In [3]: @attr.s
   ...: ... class C(object):
   ...: ...     x = attr.ib()
   ...: ...     y = attr.ib()
   ...: ...     @x.validator
   ...: ...     def name_can_be_anything(self, attribute, value):
   ...: ...         if value < 0:
   ...: ...             raise ValueError("x must be positive")
   ...: ...     @y.default
   ...: ...     def name_does_not_matter(self):
   ...: ...         return self.x + 1
   ...:     
In [5]: c = C(1)
In [6]: c.x = -1
```

I would like the `c.x = -1` to also get validated.

My use case at hand is invalidating a cache in case an attribute gets changed, and I've tried `validator` and `convert` for this, but both seem to only get applied at `__init__` time?!

**Comment by blueyed** [comment]
For my use case it is good to use `__setattr__`:
```python
    def __setattr__(self, name, value):
        if name == 'foo':
            self._foo_data = None
        super(Bar, self).__setattr__(name, value)
```

But it still feels weird that validators / converters are skipped when setting an attribute later?!

**Comment by hynek** [comment]
This is related to #233.  Long story short, when I’ve implemented validators, I didn’t want to fuzz with `__setattr__` although I already had it working.  That ship has sailed after we implemented frozen classes, but someone has to take the time to implement this whole thing properly (see my thoughts on #233).

**Comment by blueyed** [comment]
Great, closing it in favor of #233 then.
