### ISSUE TITLE
guidance on init / post-init processing

### ISSUE THREAD

**Issue by Dowwie** [python-attrs/attrs#258]
Is there a way to accommodate the following type of design in attrs?

```python

class Test:
    def __init__(self, context: dict, varA: str):
        self.do_stuff_with_context(context)
        self.varA = varA
```

I'm aware of ```__attrs_post_init__```, but that function seems to be limited to obtaining state from self.  In the example here, though, I wouldn't want to bind context to Test but rather take from it what is needed and no more.

If ```__attrs_post_init__``` were passed the same arguments as those to ```__init__```, I could work with that. 

Thoughts?

**Comment by RonnyPfannschmidt** [comment]
without surrounding context i believe this is an example of the messes attrs aims to avoid, if you want to have them use plain python classes without attrs support or go for named constructors as in

```
@attr.s
class test(object):
   @classmethod
   def from_context(cls, context, ...):
      pixiedust = magic(context)
      return cls(pixiedust, ...)
```

**Comment by hynek** [comment]
Yes what Ronny said.  `__init__` should only care about what your class needs, not in what form you currently have it.  Making `__init__` dependent on context also couples it to it forever.  Classmethod factories (or just functions FWIW) solve this a lot more elegantly.

**Comment by Dowwie** [comment]
ok, thanks for the design tips and the quick response

I'll follow these recommendations
