### ISSUE TITLE
release attrs 17.3.0?

### ISSUE THREAD

**Issue by toumorokoshi** [python-attrs/attrs#259]
Hi,

Now that type annotations are supported in attrs, is it possible to release a 17.3.0?

I'm doing a bit of work on [cattrs](https://cattrs.readthedocs.io/en/latest/) right now, and it would help to utilize the standard type syntax instead of cattrs.typed.

If a new attrs can be shipped, I can submit a patch to support the type parameter in cattrs.

Thanks!

**Comment by hynek** [comment]
I would *love* to release 17.3.0 but I really want to get the slots-like-creation-for-dict-classes ball rolling first.  It's gonna take a while to roll them out with deprecations and everything so I don't want to wait for a full new release cycle.

**Comment by toumorokoshi** [comment]
What's the ticket / PR for that? or rather, is there a part of that that needs help? I can volunteer some time if it'll help the release.

**Comment by hynek** [comment]
I have just pushed initial work to #260 but I have to stop for today.  Feel free to review/help over there. :)

**Comment by hynek** [comment]
It’s out.  🎉

**Comment by toumorokoshi** [comment]
Woo, thank you!
