### ISSUE TITLE
Add option to collect annotated fields

### ISSUE THREAD

**Issue by hynek** [python-attrs/attrs#262]
Since I’m sick of hearing that “[PEP 557](https://www.python.org/dev/peps/pep-0557/) is like attrs, but using variable annotations for field declarations”, I’d like to have an option to collect annotated fields that have no attr.ib definition.

ie.

```python
@attr.s(collect_bare=True)
class C:
    x: int
```

should be equivalent to:

```python
@attr.s
class C:
    x: int = attr.ib()
```

I’m open to better/shorter names.

Volunteers?  @chadrik maybe? :)

**Comment by Tinche** [comment]
Hm I'd actually be ok with doing this by default?

**Comment by Tinche** [comment]
A turn off switch would be nice, just default collect_bare to true? Is this a compatibility issue?

**Comment by hynek** [comment]
I’d love to but that is technically backward incompatible.

**Comment by Tinche** [comment]
Durn it.

**Comment by hynek** [comment]
We could run it thru a deprecation cycle I guess?

**Comment by wsanchez** [comment]
`s/collect_bare/automatic_attributes/`

**Comment by hynek** [comment]
Maybe just `auto_attribs`?

**Comment by hynek** [comment]
So I gave this a lackluster shot and I’ve run into a problem:

```python
    def test_auto_attribs(self):
        """
        If *auto_attribs* is True, bare annotations are collected too.
        """
        @attr.s(auto_attribs=True)
        class C:
            x: typing.List[int]
            b = attr.ib()
            y: int

        assert "C(x=1, b=2, y=3)" == repr(C(1, 2, 3))
```

`x` and `y` are defined in `__annotations__` while `b` is defined in `__dict__`.  It there a way to determine their order?

***

To me it looks like all we can do is to allow either 100% annotations or 100% `attr.ib`s which only makes sense once we have something like this:

```python
@attr.s(auto_attribs=True, check_types=True)
class Point:
    x: float
    y: float
```

or am I missing something?  (since we can’t attach any more meta data to the fields, this has to be something that happens in `@attr.s`)

This kind of smells like a `record = attr.s(auto_attribs=True, check_types=True, frozen=True, slots=True)` which is certainly useful

***

Or am I missing something?.

**Comment by hynek** [comment]
Ah OK: we just have to enforce that all fields are annotated.  That’s not that bad.

**Comment by Tinche** [comment]
Hm isn't class.__dict__ ordered in 3.6+?

**Comment by Tinche** [comment]
Ah, I see. `x` and `y` are *only* in `__annotations__`?

**Comment by hynek** [comment]
Yep.

**Comment by hynek** [comment]
You basically have two dicts and no idea how they intertwine.
