### ISSUE TITLE
Run attribute validator only after __attrs_post_init__ ends

### ISSUE THREAD

**Issue by ZhukovGreen** [python-attrs/attrs#267]
I have a code:
```python
@attr.s
class Example:
    number = attr.ib(validator=attr.validators.instance_of(int), init=False)

    def __attrs_post_init__(self):
        self.number = 'string'
        print('It seems, validation was running before:(')


t = Example()
```
The documentation says, that `...validators runs after the instance is initialized...` (http://www.attrs.org/en/stable/examples.html#callables), but example shows different behaviour.

**Comment by hynek** [comment]
I have answered your question on [StackOverflow](https://stackoverflow.com/questions/46730153/run-attribute-validator-only-after-attrs-post-init-ends/46823824#46823824).  Let me know if something else is unclear.

**Comment by ZhukovGreen** [comment]
@hynek Thanks
