### ISSUE TITLE
slots=True do not play nice with __init_subclass__

### ISSUE THREAD

**Issue by malinoff** [python-attrs/attrs#269]
A class annotated with `attr.s(slots=True)` can't call `super().__init__subclass__` within its own `__init_subclass__` method - a `TypeError: super(type, obj): obj must be an instance or subtype of type` is raised.

Reproducible example (tested on 16.3.0, 17.2.0 and f7f53d4) is here: https://repl.it/Mmkb/0

**Comment by hynek** [comment]
Uh is that another thing with cells?  Is it fixable?  And more importantly, is this something we’re breaking with #260 for dict classes too? :|

**Comment by Tinche** [comment]
I'll take a look. This is a 487 thing I see, Python 3.6+.

**Comment by Tinche** [comment]
It's fixable. I can push a commit to the replace-class branch a little later.

**Comment by Tinche** [comment]
So I'm sitting here trying to write a test for this and for some reason, the test I've written is passing even when I comment out the fix.

Turns out CPython will actually reuse closure cells sometimes. So if a class has a normal method that needs to be rewritten, the problem will not manifest. 😱

**Comment by hynek** [comment]
JFTR @malinoff, you prevented us from making a huge mistake and release it – in the last minute!  So many thanks for that!

**Comment by malinoff** [comment]
@hynek my pleasure!
