### ISSUE TITLE
attr.ib

### ISSUE THREAD

**Issue by steven-murray** [python-attrs/attrs#273]
Hi, 

First of all, thanks for this cool library. I'm creating some (apidoc) Sphinx docs with some classes that are ``@attr.s`` classes. However, all the attributes I set show up as Attributes in the docs (and don't look very nice):

![image](https://user-images.githubusercontent.com/1272030/31810296-d7dcec94-b5ad-11e7-87f4-a3698cb2673f.png)

(It's the dvdr, f, and g I'm talking about). They get into the constructor doc nicely, so I'd rather not have them display at all here. Any obvious way of omitting them? 

I know this might be more a sphinx question, so forgive me if so!

**Comment by hynek** [comment]
Next release won’t have he attributes on the body so that may solve your problem?  Would you mind checking current master?

**Comment by steven-murray** [comment]
Yup, it seems like the current master does the trick. Awesome, thanks!

**Comment by blueyed** [comment]
Yay for fixes!

@steven-murray 
Let's close it then?!
