### ISSUE TITLE
attr.s' these argument takes a dict but doesn't handle ordering

### ISSUE THREAD

**Issue by Julian** [python-attrs/attrs#279]
The `these` argument is a bit weird when you mix in defaults. E.g.,

```
import attr


@attr.s(
    these={
        "bar": attr.ib(default=3),
        "foo": attr.ib(),
    }
)
class Foo(object):
    pass
```

depending on hash randomization, will sometimes work and sometimes tell you things like

```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    class Foo(object):
  File "/Users/Julian/.local/share/virtualenvs/dev/site-packages/attr/_make.py", line 340, in wrap
    _transform_attrs(cls, these)
  File "/Users/Julian/.local/share/virtualenvs/dev/site-packages/attr/_make.py", line 215, in _transform_attrs
    .format(a=a)
ValueError: No mandatory attributes allowed after an attribute with a default value or factory.  Attribute in question: Attribute(name='foo', default=NOTHING, validator=None, repr=True, cmp=True, hash=None, init=True, convert=None, metadata=mappingproxy({}))
```

It seems like either `these` should specifically say it needs an ordered mapping type, or that it should be sorting the mapping it gets in a way that doesn't raise `attr`'s internal error.

**Comment by Julian** [comment]
Hm, and playing a bit further, even an `OrderedDict` doesn't seem to work, because attrs *is* doing some sort of sorting, just not one that's compatible with the original one. Trying to figure out what/why.

**Comment by Julian** [comment]
OK, I think the latter is the result of `attr.ib` having global state on when it's been called, rather than trusting the order that it's provided in, but will have to dig in later after popping some yaks.

**Comment by hynek** [comment]
attr.ib has an internal counter because before 3.6 we we need it to establish attribute order on class bodies if that’s what you mean

**Comment by Julian** [comment]
Yeah sorry, I know about needing to do it for class bodies -- for this behavior specifically I was expecting it should ignore that and use some other order (basically it seems like any time you have an `attr.ib` anywhere other than in a class body, or anytime you reuse one, you're gonna need some other signal of ordering).

**Comment by Julian** [comment]
Ohhhhh sorry, now I think I understand the thrust of your comment, and also the current behavior here -- attrs does nothing special for the `these` case, so it still treats it as if it's the class body case and uses the ordering of when you call `attr.ib`.

OK, I see.

Still seems like this will break some expected semantics though -- in my case often when I use `these` I want to actually re-use subsets of attribs, and I've never noticed before that that has any relationship to their positional order.

Any interest in a patch to make this work, or is it not something that anyone else is doing?

**Comment by hynek** [comment]
In general yes, but double check your approach with us before implementing it first please. :)

**Comment by Julian** [comment]
OK I think internally we managed to work around this, which means I doubt I'm gonna have a chance to get back to it that quickly :/.

Closing this myself for now, but I suspect we'll run into it again at which point yeah will follow up about a PR.
