### ISSUE TITLE
Typo on Homepage

### ISSUE THREAD

**Issue by juancarlospaco** [python-attrs/attrs#283]
http://www.attrs.org

`Yes, we’ve heard about nametuples!` should be `Yes, we’ve heard about namedtuples!`.

:smile_cat:

**Comment by hynek** [comment]
Ugh, not gonna make a release but that is embarrassing.  I think I’m gonna do some RTD magic which I’ll forget before next release and wonder why the docs don't update…

**Comment by hynek** [comment]
Ugh, not gonna make a release but that is embarrassing.  Let’s see if I can do some weird RTD magic…

Thanks!

**Comment by hynek** [comment]
Ah now GitHub is punishing me with not-posting-then-double-posting too. *screams into the void*
