### ISSUE TITLE
Allow using attrs without ctypes

### ISSUE THREAD

**Issue by inklesspen** [python-attrs/attrs#284]
#226 introduced the use of `ctypes`. I use attrs in a Google App Engine application. The app runs in a sandbox which limits the use of certain modules. `ctypes` is one of those libraries.

I can peg my app to use only attrs 17.2.0, but it would be nice to have a fail-gently approach where, if ctypes is unavailable, attrs keeps working, though the behavior allowed by #226 of course would not work.

**Comment by hynek** [comment]
Now, that’s unfortunate!  Making the support unconditional is gonna be easy, the big question is how to document/communicate the behavior it to the user. 🤔

**Comment by Tinche** [comment]
Probably log a warning? Hopefully in a way that's visible.

**Comment by Tinche** [comment]
Also, we won't need ctypes in CPython 3.7 right?

**Comment by hynek** [comment]
I don’t think a log is necessary; we’ll just put it into our docs.
