### ISSUE TITLE
17.3.0 changes the order how inherited class attributes are defined if they have the same base class

### ISSUE THREAD

**Issue by Emantor** [python-attrs/attrs#285]
Minimal working example:
```
import attr

@attr.s()
class A:
    name = attr.ib()
    cookie = attr.ib(default="Cookie")

@attr.s()
class B:
    cake = attr.ib(default="Cake")
    cereal = attr.ib(default="Cereal")

@attr.s()
class C(B, A):
    breakfast = attr.ib(default="All")

@attr.s()
class D(A):
    food = attr.ib(default="food")
    melon = attr.ib(default="melon")

@attr.s()
class E(D, C):
    apple = attr.ib(default="apple")
```
This works with attrs==17.2.0 and breaks with attrs==17.3.0. In 17.3.0 the list of non_super_names in base.py: `['cake', 'cereal', 'breakfast', 'name', 'cookie', 'food', 'melon', 'apple']` breaks because attr is trying to create a non-default attribute in between default attributes.

**Comment by jluebbe** [comment]
When looking at what _transform_attrs is doing for class E, we see what's going wrong. The MRO for E is E, D, C, B, A.
It first collects all attributes from D.__attrs_attrs__ in reverse order: melon, food, cookie, name. Then it looks at C.__attrs_attrs__ and collects the attributes which are not yet defined: breakfast, cereal, cake.
When reversing this again, the name attribute ends up in the middle.
It seems that this should work if it only looked at the locally defined attributes when iterating over the MRO, as A.name would be processed last.

**Comment by jluebbe** [comment]
As a minimal workaround, this change fixes the order for our usecase:
``` diff
@@ -278,7 +278,9 @@
             # list in the end and get all attributes in the order they have
             # been defined.
             for a in reversed(sub_attrs):
-                if a.name not in taken_attr_names:
+                if a.name in super_cls.__super_names__:
+                    continue
+                elif a.name not in taken_attr_names:
                     super_attrs.append(a)
                     taken_attr_names.add(a.name)
 
@@ -354,6 +356,7 @@
         self._has_post_init = bool(getattr(cls, "__attrs_post_init__", False))
 
         self._cls_dict["__attrs_attrs__"] = self._attrs
+        self._cls_dict["__super_names__"] = self._super_names
 
         if frozen:
             self._cls_dict["__setattr__"] = _frozen_setattrs
```
The downside is obviously cluttering the generated classes with the ``__super_names__`` attribute. Perhaps each Attribute could keep a reference to the class where it was defined.
That would allow ``_transform_attrs`` to filter out those defined on other super classes and only handle them later where they were actually defined.

**Comment by hynek** [comment]
I think it’s simpler.  The problem is that it’s possible to overwrite attribute definitions now and that’s exactly what’s happening here.  The bug is that I didn’t take into account such hierarchies that introduce the same attribute multiple times.

#286 should fix that, would you mind checking it out?

**Comment by jluebbe** [comment]
Yes, #287 fixes our test suite. Thanks!
