### ISSUE TITLE
Possible to add a "field_names" helper function?

### ISSUE THREAD

**Issue by laike9m** [python-attrs/attrs#290]
In a specific use case, I need to get all field names that are defined in an attrs class, which is as simple as
```
[f.name for f in attr.fields(MyClass)]
```
Do you think it's OK to add a public API for this?

**Comment by hynek** [comment]
Hm, I was rather thinking about exposing fields as a dict, because I needed string access to attributes.

That would give us:

- `attr.fields_dict(MyClass)[name]` for me
- and `attr.fields_dict(MyClass).keys()` for you

**Comment by laike9m** [comment]
That's sounds good to me.
