### ISSUE TITLE
__hash__ works only on attribute values

### ISSUE THREAD

**Issue by hynek** [python-attrs/attrs#295]
Currently our `__hash__` methods returns the hash of a tuple with all attribute values but without taking type information into account:

```pycon
>>> @attr.s(hash=True)
... class C:
...     x = attr.ib()
>>> hash(C(1)) == hash((1,))
True
```

Oopsies!

**Comment by Tinche** [comment]
Does our `__eq__` take into consideration the classes? Because if it does I think not taking the class into account is actually fine.

**Comment by hynek** [comment]
I believe it returns NotImplemented if classes don’t match.
