### ISSUE TITLE
Attrs 17.3.0 breaks when combined with abc.abstractproperty

### ISSUE THREAD

**Issue by mattsb42-aws** [python-attrs/attrs#303]
In the course of fixing [an issue](https://github.com/awslabs/aws-encryption-sdk-python/issues/29) surfaced by attrs 17.3.0, I discovered a strange conflict between `attrs` and `abc` that used to work pre-17.3.0.

When a parent class has `abc.ABCMeta` as a metaclass and a child class inherits from it and is an `attrs` class, something in the generated code breaks.

```
Python 3.6.2 (default, Jul 17 2017, 16:44:45) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import abc
>>> 
>>> import attr
>>> attr.__version__
'17.3.0'
>>> import six
>>> 
>>> @six.add_metaclass(abc.ABCMeta)
... class Parent(object):
...     @abc.abstractproperty
...     def required_attribute(self):
...         pass
... 
>>> @attr.s(hash=False)
... class Child(Parent):
...     required_attribute = attr.ib()
... 
>>> Child(required_attribute=8)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<attrs generated init bcae434d90e3ab868abca1ee5aaff71fbe20a93b>", line 2, in __init__
AttributeError: can't set attribute
```

This behavior is not seen with 17.2.0:
```
Python 3.6.2 (default, Jul 17 2017, 16:44:45) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import abc
>>> 
>>> import attr
>>> attr.__version__
'17.2.0'
>>> import six
>>> 
>>> @six.add_metaclass(abc.ABCMeta)
... class Parent(object):
...     @abc.abstractproperty
...     def required_attribute(self):
...         pass
... 
>>> @attr.s(hash=False)
... class Child(Parent):
...     required_attribute = attr.ib()
... 
>>> Child(required_attribute=8)
Child(required_attribute=8)
```

**Comment by hynek** [comment]
This looks like a dupe of #293.  Please refer to my longer explanations & demonstrations, there but the gist is, that it only worked because attrs used to attach the attribute definitions to class bodies which prevented abc to work properly.

IOW: it shouldn’t have ever worked.  As said on the other ticket, I’m deeply sorry and if someone has any suggestions for a proper way to help y’all writing abstract properties, we’re all ears.

**Comment by mattsb42-aws** [comment]
Hmm, I agree, that sounds like the same problem; I neglected to search closed issues. Closing this issue since this is intentional, and I'll update back here with whatever we decide on to work around this for reference.
