### ISSUE TITLE
Equality by comparing tuples is not always correct

### ISSUE THREAD

**Issue by hynek** [python-attrs/attrs#305]
Another Hynek-didn’t-quite-fully-understand-Python bug: while I maintain that establishing order using tuples makes totally sense, Hypothesis just taught me about an invariant in container equality I wasn’t fully aware of:

```python
>>> from math import nan

>>> nan == nan
False

>>> (nan,) == (nan,)
True
```

The problem here is that tuples compare by identity first and by value second.  And nan is identical but unequal.

I’ve noticed this when I tried to implement our `__eq__` using a string of `and` s instead of building two tuples which I’m sure is faster.

My first gut instinct was to use tuples again.  My second one is that we’re probably masking some bugs somewhere by this behaviour.  And it totally is a bug in attrs.

What to do?

**Comment by hynek** [comment]
Obligatory ping to @ericvsmith since they seem to do it the same way in data classes.

**Comment by ericvsmith** [comment]
I think the conflict is unresolvable. As long as you define the behavior, the user has to live with the results of depending on it. Using nans as keys in a dict or in sets has the same issue. And it's all made worse by float('nan') returning a new nan:
```
>>> s = {nan}
>>> nan in s
True
>>> float('nan') in s
False
>>> float('nan') == nan
False
>>> float('nan') is nan
False
```
I do agree it's unfortunate that changing to `and` chaining might be prevented by the wacky nan behavior.

Do you have any numbers on `and` chaining speed vs. tuple creation? I might change `dataclasses` to define comparison by `and` chaining if it's demonstrably faster.

**Comment by Tinche** [comment]
My initial reaction: f*** floats (not helpful, I know). Is the chain of ands approach faster?

**Comment by ericvsmith** [comment]
I sort of agree: I don't think you should do anything special for anything where `is` is `True`, but `==` is `False`. nan is the only thing that falls in this category that I know of.

There are many instances of this being raised on bpo. Here's an interesting one https://bugs.python.org/issue4296 with a quote by Mark Dickinson: 

> But in general I don't think the fact that NaNs are weird
should get in the way of optimizations.  In other words,
I'm not sure that Python should be asked to guarantee
anything more than "b == b" returning False when b is
a NaN.  It wouldn't seem unreasonable to consider
behaviour of nans in containers (sets, lists, dicts)
as undefined when it comes to equality and identity
checks.

Although he seems to walk back part of his comment, so I don't know where it stands in the end, unfortunately. Also, it's old.

**Comment by hynek** [comment]
So I did a quick benchmark:

ands:

```
pyperf timeit --rigorous -s "from t import c1, c2" "c1 == c2"
.........................................
Mean +- std dev: 549 ns +- 20 ns
```

tuples:

```
pyperf timeit --rigorous -s "from t import c1, c2" "c1 == c2"
.........................................
Mean +- std dev: 533 ns +- 21 ns
```

So looks like ands are even slower for some reason!

**Comment by hynek** [comment]
OK I think it’s fine to not change anything so far.  At some point we maybe should document this a bit.
