### ISSUE TITLE
Generated methods like __init__ lack the __module__ attribute

### ISSUE THREAD

**Issue by Stewori** [python-attrs/attrs#309]
This issue was initially reported in https://github.com/Stewori/pytypes/issues/18.
Applying ``__module__`` on e.g. the ``__init__`` function generated by attrs raises a ``KeyError``. For more information please refer to the link above.

Being able to retrieve the module for a given function/method is relevant to locate the function or method in the class hierarchy from perspective of a decorator or profiler. Searching a module top-down for a function/method is often the only way to access its enclosing class, including nesting structure of classes.

A workaround that sometimes worked but not in this case is to get the module via ``__code__.co_filename``. However, any valid approach for identifying the corresponding module and/or location in class hierarchy for a generated function would be fine.

Please apologize if I should overlook some approach that is already viable.

**Comment by hynek** [comment]
We probably should try to set it to the module where the class is defined?

This problem will also appear with `__eq__` and `__hash__` with the next release.

**Comment by Stewori** [comment]
> We probably should try to set it to the module where the class is defined?

Yes that's right.
Does the generated method show up as member of a class if the class is inspected using ``dir`` or the ``inspect`` module or ``__dict__``? If not, it would be good to insert ``__qualname__`` as well, if that's not already done. (Sorry I don't know attrs well, so apologize if the ``__qualname__`` thing is already resolved. I'm just trying to early-prevent then next issue on this path...)

**Comment by devdave** [comment]
@hynek Already spent a good amount of time learning how _make fits together.  With make.py:_make_init could add a 4th argument (cls) and then inside copy cls.__module__ to globs.  Either there or just setattr after  _make_init?
