### ISSUE TITLE
Add stubs to typeshed

### ISSUE THREAD

**Issue by chadrik** [python-attrs/attrs#319]
As per [the typshed contribution docs](https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#adding-a-new-library), this issue is to request permission to add `attrs` to the python typeshed.  Also, it doubles as a way to let you know that @euresti and I are ready for you to review https://github.com/python-attrs/attrs/pull/238.

**Comment by hynek** [comment]
> This gives them the opportunity to consider adopting type hints directly in their codebase (which you should prefer to external type stubs).

That...doesn’t really make sense in mypy‘s current Modus operandi, does it?

**Comment by chadrik** [comment]
> That...doesn’t really make sense in mypy‘s current Modus operandi, does it?

I believe that is correct.  Mypy searches for stubs within a list of paths defined by MYPYPATH,  ignores PYTHONPATH, and explicitly advises against pointing MYPYPATH at site-packages.  So for all intents and purposes, python's package distribution (i.e. pip) and PEP484 stubs are at odds with each other.    Until PEP 561 is complete (slated for 3.7) we have the typeshed.

**Comment by hynek** [comment]
Well, yolo away then.

**Comment by chadrik** [comment]
You only YOLO once ;)

**Comment by wsanchez** [comment]
Agreed on typeshed being the next step here.

**Comment by hynek** [comment]
Can this be closed?

**Comment by euresti** [comment]
All @chadrik needs is for this to say that the maintainers give permission to put it in typeshed.  Closing is probably ok.

**Comment by hynek** [comment]
Permission is granted.
