### ISSUE TITLE
Auto-detect user-written methods

### ISSUE THREAD

**Issue by hynek** [python-attrs/attrs#324]
Currently, if you want to implement a method yourself, you have to remember to do two things:

```python
@attr.s(repr=False)
class C:
    def __repr__(self):
        return "whatever"
```

I’ve seen quite a few people be confused/frustrated by that.

***

I think unless `these` is set, it would be kind of cool if we detected that the current class (and not some super class) has a user-written method and set the flag to false automatically such that

```python
@attr.s
class C:
    def __repr__(self):
        return "whatever"
```

does what you’d expect.

Opinions?

**Comment by euresti** [comment]
Same with `__init__`?  (I ask because the mypy plugin will have to deal with that too.)

**Comment by hynek** [comment]
The idea is to support it for all of them.  It gets a bit hairy when we get to comparison because it’s several ones.  Would we stop completely?  Or just not replace one of them?

**Comment by wsanchez** [comment]
With comparison methods, perhaps [total_ordering](https://docs.python.org/3/library/functools.html#functools.total_ordering) could provide guidance; if you provide enough for `total_ordering` to work, we apply it or do something similar?

It's a bit of feature creep, but it feels in line with the developer doing as little work related to attributes as necessary and we take care of the rest.

**Comment by hynek** [comment]
The more I think about it the more I think we should just skip methods that have been defined and be done with it.  That allows people to customise their classes even better.
