### ISSUE TITLE
Documentation shows old __hash__ method

### ISSUE THREAD

**Issue by RazerM** [python-attrs/attrs#327]
I was reading [Why not...](http://www.attrs.org/en/stable/why.html#hand-written-classes) and noticed the equivalent `__hash__` is wrong since #296.

Admittedly the point of the example isn't to document `__hash__`, but since it's a page for prospective users of attrs it seems wise to change the implementation rather than leave new users with the wrong impression of what a generated `__hash__` would do.

**Comment by hynek** [comment]
I have changed it a bit to be closer to what we do, however adding all the optimisations would probably be slightly too much and dilute the point we’re trying to make. :)
