### ISSUE TITLE
Multiple assignments confuse argument ordering.

### ISSUE THREAD

**Issue by euresti** [python-attrs/attrs#328]
While working on the mypy plugin I wrote the following code snippet:

```
import attr
@attr.s
class A(object):
    x = y = z = attr.ib()

A(1,2,3)
```

On python3.6 I get `A(x=1, y=2, z=3)`  but in python 2 I get `A(y=1, x=2, z=3)`

Maybe it should be disallowed completely?

**Comment by hynek** [comment]
Hm well, what happens here is that all attributes get the same attr.ib() with the same internal counter and the order depends on the dict order on the Python version.  I’m pretty sure it would break software if we took active measure against it, but we don’t support it.

**Comment by euresti** [comment]
Maybe I'll have mypy emit an error/warning for that then.  

I assume you're ok with 

```
@attr.s
class A(object):
   x, y, z = attr.ib(), attr.ib(), attr.ib()
```
?

Since that's at least consistent.

**Comment by hynek** [comment]
Sure, that’s ugly syntax but perfectly fine semantics.

**Comment by euresti** [comment]
Ok I've made a warning in the mypy plugin.  Hopefully that will let people know that it's gonna cause problems down the line.

**Comment by hynek** [comment]
Cool. I’m gonna close this now, since I think we’ve resolved the issue.
