### ISSUE TITLE
keyword-only attrs

### ISSUE THREAD

**Issue by asvetlov** [python-attrs/attrs#335]
It would be nice to support keyword-only constructor parameters, e.g.
```
@attr.s
class A:
    a = attr.ib()
    b = attr.ib(keyword=True)

A(1, 2)  # forbidden
A(1, b=2)  # passed
```
Should be allowed for Python 3 only. 
Well, attrs should have no Python 3 specific code -- compilation of `__init__` function with keyword-only arguments generates `SyntaxError` on Python 2, maybe enough.

I don't know what name is better: `keyword`, `kw_only`, `keyword_only`.

**Comment by hynek** [comment]
Theere is a half-finished PR for this #281 but nobody came around to fix it into a mergeable shape.

**Comment by asvetlov** [comment]
Looks like we are in opposite situation. 
I have no time to work on the issue, the feature doesn't kick my ass yet.
You have no time for working on aiohttp and family problems for the same reason I guess.

**Comment by hynek** [comment]
Heh exactly. 😂 I didn’t mean it accusingly, just wanted to point out there’s some work.

**Comment by asvetlov** [comment]
Anyway thank you for raising issues. We have client tracing support by aiohttp client finally for example.
