### ISSUE TITLE
make_class does NOT keep the order of the `attrs` args when creating a class

### ISSUE THREAD

**Issue by pombredanne** [python-attrs/attrs#339]
If I use `make_class` and I pass an OrderedDict of name/attribs, the created class does not have these created in the original order. 

Somehow `make_class` ends up using some plain dicts for attrs (whether this is originally a list or an Ordered mapping) and my attributes order is lost... which means that down the road my serialization order is also lost and that eventually the order of the arguments is not entirely clear.
As it is this creates classes with a pseudo-random attributes order (as it depends on the Python hash function used in the dict)

**Comment by pombredanne** [comment]
Actually what happens is that the order of the attributes is the order of their creation. This is something in my case on which I have no control as this is eventually based on the import order of arbitrary plugins.
Here is the skinny:
```
Python 2.7.13 (default, Jun 16 2017, 16:03:08) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import attr
>>> @attr.s
... class A(object):
...     z = attr.ib(default=None)
... 
>>> car = attr.ib(default=None)
>>> posture = attr.ib(default=None)
>>> zillow = attr.ib(default=None)
>>> 
>>> 
>>> from collections import OrderedDict
>>> attribs = OrderedDict([
...     ('zillow', zillow),
...     ('posture', posture),
...     ('car', car)
... ])
>>> 
>>> B=attr.make_class(name='B', attrs=attribs, bases=(A,))
>>> 
>>> for f in attr.fields(B):
...     print f
... 
Attribute(name='z', default=None, validator=None, repr=True, cmp=True, hash=None, init=True, metadata=mappingproxy({}), type=None, converter=None)
Attribute(name='car', default=None, validator=None, repr=True, cmp=True, hash=None, init=True, metadata=mappingproxy({}), type=None, converter=None)
Attribute(name='posture', default=None, validator=None, repr=True, cmp=True, hash=None, init=True, metadata=mappingproxy({}), type=None, converter=None)
Attribute(name='zillow', default=None, validator=None, repr=True, cmp=True, hash=None, init=True, metadata=mappingproxy({}), type=None, converter=None)
>>> attr.asdict(B(), dict_factory=OrderedDict)
OrderedDict([('z', None), ('car', None), ('posture', None), ('zillow', None)])

```

My order: zillow, posture, car is not respected as the _CountingAttribute are always resorted by "creation" time ordering. (It could never be respected anyway since the sorting always occurs and ordered mappings are ignored.)

**Comment by pombredanne** [comment]
Not that in contrast if I use multiple bases and multiple inheritance each with their own attributes and use this instead of passing a mapping of attributes, I can get properly ordered attributes... So there are cases where "multiple inheritance" can be good things ;)

**Comment by pombredanne** [comment]
@hynek so which approach would you suggest such that `make_class` can be used and respect the provided order of attributes rather than only consider their creation order? The `_CountingAttr` wrapper seems to make this impossible (short of rebuilding new attributes in the right creation sequence from the received attributes and prior to calling make_class).

**Comment by pombredanne** [comment]
note that I cannot call attr.evolve on an attrib. It fails. I could update the `.counter` value of each attribute, but that would be highly hackish, would it?

**Comment by pombredanne** [comment]
So for now I made an ugly hack https://github.com/nexB/scancode-toolkit/blob/787-new-plugin-architecture/src/scancode/cli.py#L703
and I update the `.counter` of attributes.... not proud of this ;)

**Comment by hynek** [comment]
So this has been reported recently but I can’t find it. 🤔

Yes, attr.ib() (aka _CountingAttribs) are ordered by creation order; we just don’t do anything special about it when passed to make_class – it's the same code as when used on classes.

I guess we could add some special support if

1. `these` is passed and
2. it's ordered (ie.: OrderedDict or Python 3.6+)

**Comment by pombredanne** [comment]
Whatever works would be great! per the link above, I made a quick hack to workaround this short term by re-setting the `_CountingAttribs.counter` to a value that matches my order. I could have used multiple bases instead to get a more deterministic attributes order too, but that would a real abuse of multiple inheritance...

Alternatively I could eschew the whole problem in my case by having my plugins NOT contributes `attr.ib`'s but instead an object of mine (possibly based on an `attr.s` class that would hold the args to create `attr.ib`'s that I would create only just before a `make_class` call.)
The mild benefit would be that it insulates my external public plugin API from `attr` which could be a good thing for decoupling? (though I am already tied to so many other APIs that it likely does not matter )

**Comment by pombredanne** [comment]
Now, just as a side note, I am also eyeing @Tinche [cattrs](https://github.com/Tinche/cattrs) as I may want my plugins to declare the whole/full data structure/schema that they are contributing and not just a simple, single-level attr.ib
