### ISSUE TITLE
single executable file frozen by py2xe raise AttributeError on runtime

### ISSUE THREAD

**Issue by marunguy** [python-attrs/attrs#341]
Single executable file frozen by py2exe(bundle_files=1) raise AttributeError on runtime.
Windows 8.1 64bit, Python 2.7.14 32bit, attrs 17.4.0, py2exe 0.6.10a1

if bundle_files is 2, my app works well.

> bundle dlls in the zipfile or the exe. Valid values for bundle_files are: 3 = don't bundle (default) 2 = bundle everything but the Python interpreter 1 = bundle everything, including the Python interpreter 

I prefer single executable file.
Is it possible that singe executable file(bundle_files=1) works well ?

* error message
```
Traceback (most recent call last):
  ...
  File "attr\__init__.pyo", line 5, in <module>
  File "zipextimporter.pyo", line 74, in load_module
  File "attr\filters.pyo", line 7, in <module>
  File "zipextimporter.pyo", line 74, in load_module
  File "attr\_compat.pyo", line 139, in <module>
  File "attr\_compat.pyo", line 131, in make_set_closure_cell
  File "ctypes\__init__.pyo", line 379, in __getattr__
  File "ctypes\__init__.pyo", line 384, in __getitem__
AttributeError: function 'PyCell_Set' not found
```
* error position - "attr\_compat.pyo", line 131, in make_set_closure_cell
```python
def make_set_closure_cell():
    """
    Moved into a function for testability.
    """
    if PYPY:  # pragma: no cover
        def set_closure_cell(cell, value):
            cell.__setstate__((value,))
    else:
        ctypes = import_ctypes()
        if ctypes is not None:
            set_closure_cell = ctypes.pythonapi.PyCell_Set # <<<< here
            set_closure_cell.argtypes = (ctypes.py_object, ctypes.py_object)
            set_closure_cell.restype = ctypes.c_int
        else:
            set_closure_cell = just_warn
    return set_closure_cell
```

**Comment by hynek** [comment]
This is going to work in the next release thanks to #334 (feel free to test with master) however the question is whether or not it will cause other problems.

In your case it shouldn’t matter since you’re using Python 2 and that doesn’t need the cell anyways.
