### ISSUE TITLE
List[str] attr.ib element aggregates over multiple instantiations

### ISSUE THREAD

**Issue by bedge** [python-attrs/attrs#347]
The following code illustrates the case. The element `ll` should be newly created for each class instance. However it aggregates the values together and is sharing a single ll instance for all instantiated classes:

from typing import List

```python
from typing import List
​
@attr.s
class TT(object):
    name: str = attr.ib()
    ll: List[str] = attr.ib(default=[])
    def __attrs_post_init__(self):
        self.ll.append(['a','b','c'])
​
tt1 = TT(name='1')
tt2 = TT(name='2')
print(tt1,tt2)
TT(name='1', ll=[['a', 'b', 'c'], ['a', 'b', 'c']]) TT(name='2', ll=[['a', 'b', 'c'], ['a', 'b', 'c']])```
```
I don't believe that the ll element should be a static class level element and rather should be an instance element.

If I change the code as follows, the problem goes away:
from typing import List

```python
from typing import List
​
@attr.s
class TT(object):
    name: str = attr.ib()
    ll: List[str] = attr.ib(default=[])
    def __attrs_post_init__(self):
        self.ll=[]
        self.ll.append(['a','b','c'])
​
tt1 = TT(name='1')
tt2 = TT(name='2')
print(tt1,tt2)
TT(name='1', ll=[['a', 'b', 'c']]) TT(name='2', ll=[['a', 'b', 'c']])
```

Adding an initializer for ll resets it with each invocation, but IMO this shouldn't be necessary and is counter intuitive.

**Comment by asvetlov** [comment]
That's how Python works with mutable defaults, nothing special for `attrs`.
To fix your code use `ll = attr.ib(default=attr.Factory(list))`

**Comment by bedge** [comment]
Fix confirmed, thank you.
