### ISSUE TITLE
core API reference misnames attr.s() argument

### ISSUE THREAD

**Issue by PsyMar** [python-attrs/attrs#348]
The core API reference (as viewed at http://attrs.readthedocs.io/en/stable/api.html#core ) lists the last argument of attr.s()'s function signature as "str", which seems like a bad idea.  Later the auto_attribs argument is explained, but this argument is missing from the function signature per the API.

This is probably a simple fix but I am unfamiliar enough with the project's inner workings that I don't want to touch anything.

**Comment by hynek** [comment]
Yeah, that has been fixed in master (you can double check by choosing “latest” docs version).
