### ISSUE TITLE
Can't use attr.filters.exclude if the class has a field with a default value that uses Factory

### ISSUE THREAD

**Issue by tonnydourado** [python-attrs/attrs#352]
When a class has a field, that has a default value, that is defined with Factory, trying to convert an instance of it to a dict using `asdict` fails, if you try to also filter some fields out. Example:

```python
from attr import attrs, attrib, asdict, filters, fields, Factory

@attrs
class Thing(object):
    foo = attrib()
    things = attrib(default=Factory(list))

thing = Thing(foo="bar")
print(asdict(thing, filter=filters.exclude(fields(Thing).things)))  # raises TypeError
```

This will raise a `TypeError` because filters.exclude will perform an `in` check of the `things`'s `Attribute` instance against a `frozenset` of `Attribute` instances. When it does that, it will try to get the hash of `things`'s `Attribute` instance, but that will fail, because one of it's attributes is a `Factory` instance, that is not hashable.

Making `Factory` hashable does seem to do the trick, but I'm not sure if it could affect something else:

```python
from attr import attrs, attrib, asdict, filters, fields, Factory

@attrs(slots=True, init=False, hash=True)
class HashableFactory(Factory):
    def __hash__(self):
        return id(self)

@attrs
class WorkingThing(object):
    foo = attrib()
    things = attrib(default=HashableFactory(list))

working_thing = WorkingThing(foo="bar")
print(asdict(working_thing, filter=filters.exclude(fields(WorkingThing).things))) # prints {'foo': 'bar'}
```

**Comment by hynek** [comment]
What version are you running? Factory has been hashable since 17.3 and your example indeed works for me.

AFAICT only 17.1 and 17.2 had that bug.

**Comment by tonnydourado** [comment]
Oh, it might be the version, I think we haven't updated our dependencies in a while. I'll check with the latest version when I get back to my computer.

**Comment by tonnydourado** [comment]
It does indeed work on 17.4, we didn't update our requirements in a while. Sorry about that, gonna close this. Also, thank y'all for the lib, it's pretty cool and useful =)
