### ISSUE TITLE
Conditional initialization of attributes

### ISSUE THREAD

**Issue by roganov** [python-attrs/attrs#354]
While trying to use attrs with sqlalchemy, I came across an issue that in some cases it's needed to initialize an attribute _only_ if it was passed to constructor.

Basically, this code
```python
@attr.attrs
class A:
   a = attr.ib(initialize_if_given=True)
```

should translate to this
```python
CONDITIONAL_INIT = object()

class A:
    def __init__(a=CONDITIONAL_INIT):
        if a is not CONDITIONAL_INIT:
            self.a = a
```

**Comment by hynek** [comment]
Aren’t you asking for a magic default value? Uninitialized attributes are basically time bombs.

**Comment by RonnyPfannschmidt** [comment]
@roganov can you state the actual use case instead of the proposed solution?

**Comment by wsanchez** [comment]
I this the described behavior would have no attribute `a` on class `A` if no corresponding argument is given to the initializer.  I don't think that's feasible, since we have the class attribute, and I also don't think that `attrs` should support every odd thing you can do in Python, so I think I'm with Hynek here.

@RonnyPfannschmidt is right though; without explaining the use case, it's hard to know whether this is an oversight of some sort.

**Comment by roganov** [comment]
@hynek  It is already possible to create a 'time bomb':
```python
@attr.s
class A:
    a = attr.ib(init=False)

a = A()
a.a  # AttributeError
```
Or is it a bug?

**Comment by wsanchez** [comment]
I believe what @hynek was trying to express was that if you have an uninitialized attribute after you initialize your instance, that this is bad juju.  So I'd say your example above is a bug in the program; I do think it's generally unsafe to have `init=False` and no `default` unless you are doing something in, say, `__attrs_post_init__` to rectify that.

**Comment by RonnyPfannschmidt** [comment]
so the basic gist is that you have pairs of attributes that are managed by a 3rd party library,
and whats really needed is not conditional initialization, but something more like sqlalchemy mapper awareness

aka a attrs_sqlalchemy addon

**Comment by RonnyPfannschmidt** [comment]
@hynek this use case also directly shows a weakness of the codegen approach, at mapper declaration time the class declaration is done and one is unable to fix the generated code by then

**Comment by hynek** [comment]
You call it a weakness, I call it the biggest strength. :)

And yes, this calls for an add-on that wraps `@attr.s`, sets unconditionally `init=False` and then generates the necessary ``__init__``.

That said: I don’t know the ORM bits of SQLAlchemy well enough, but I’m gonna claim that it would be cleaner/nicer to be able to write:

```python
UNSET = object()

@attr.attrs(cmp=False, auto_attribs=True)
class Child:
    id: int
    parent_id: t.Optional[int] = UNSET
    parent: t.Optional[Parent] = UNSET
```

Than doing voodoo with getattr/hasattr. That gives you much better introspection.

Are you sure it’s impossible?

**Comment by RonnyPfannschmidt** [comment]
@hynek correct mapper handling needs integration with real descriptors for stuff like lazy loading of dependencies or deferred loading of properties - i dare to claim that attrs biggest "strength" makes it fundamentally incompatible with reasonable orm's

**Comment by roganov** [comment]
@hynek 
Could you clarify what this `UNSET` thing helps to achieve? Also it won't typecheck.
