### ISSUE TITLE
attr.ib does not return a value?

### ISSUE THREAD

**Issue by wsanchez** [python-attrs/attrs#362]
There is one case in Klein where the latest `mypy` thinks that `attr.ib` does not return a value.

See https://github.com/twisted/klein/pull/241#issuecomment-374326118 for details.

Is there something in our new type hints that can make `mypy` think this, or this is a bug in `mypy`, or is this (perhaps more likely) pilot error on my part?

**Comment by euresti** [comment]
Definitely something in our type hints.  Let me investigate more.

**Comment by euresti** [comment]
Found it.  In mypy `-> None` means doesn't return.  The type hints was seeing 

`attr.ib(None, validator=...)` and basically making it `-> None`   

But thankfully reordering the overloads will make it work correctly.  (Basically the check for None happened after the check for a validator set.  Oops)

**Comment by wsanchez** [comment]
OK cool.  Thanks for digging into this.

**Comment by euresti** [comment]
Fix is in: https://github.com/python/typeshed/pull/1980

But not released yet.

**Comment by euresti** [comment]
This is fixed in mypy 0.590
