### ISSUE TITLE
mypy error when Factory is given takes_self=True

### ISSUE THREAD

**Issue by wsanchez** [python-attrs/attrs#366]
I've got this error:

```console
src/ims/application/_main.py:69:17: error: Argument 1 to "Factory" has incompatible type "Callable[[Any], APIApplication]"; expected "Callable[[], APIApplication]"
```

Which is in reference to [this code](https://github.com/burningmantech/ranger-ims-server/blob/78ffabd70efaa6a9f05a11420b6560eb5338ec32/src/ims/application/_main.py#L69).

Here's the call to `Factory`:

```python
Factory(
    lambda self: ExternalApplication(config=self.config),
    takes_self=True,
)
```

Looks like our type hints don't handle the case where `takes_self=True`.

**Comment by euresti** [comment]
Bug in `typing` will send a PR for it.

**Comment by euresti** [comment]
@chadrik I'm looking at the pyi file and I don't why it says:
`# Work around mypy issue #4554 by using an overload vs a Union.`

The easy fix for this is to make it a Union. 
The fix if we want to keep the overload is:

```
@overload
def Factory(factory: Callable[[], _T]) -> _T: ...
@overload
def Factory(factory: Callable[[Any], _T], takes_self: bool = ...) -> _T: ...
```
But then you can't write `Factory(f, True)`
Do you remember what the problem with `Union` was?

**Comment by chadrik** [comment]
My change was a backport of your change to the typeshed:  https://github.com/python/typeshed/pull/1914

If you can get all of the tests to pass on `pyi_stubs` branch using `tox -e stubs,docs` (minus the known issue with `int` as a converter) then I'm fine with using a `Union`.
