### ISSUE TITLE
Question: Validators for the Entire Class?

### ISSUE THREAD

**Issue by fxfitz** [python-attrs/attrs#377]
Quick question that I couldn't find easily: it seems like when validators are run, they are per-attribute.  Is there a way to essentially validate the entire class, and therefore get a "list" of attributes/exceptions that have failed validation?

**Comment by hynek** [comment]
You could do something like that in `__attrs_post_init__`. We almost merged something dedicated in #372 but then decided that such validators would be too ineffective…

**Comment by fxfitz** [comment]
Got it, I'll take a look!  Thanks for the quick response!

Overall, what I'm looking to do is tell the end-user all of attributes that are failing and why, instead of "one at a time".
