### ISSUE TITLE
Python reserved word as an attribute

### ISSUE THREAD

**Issue by rougeth** [python-attrs/attrs#381]
Hello people, I have class that must have a `from` attribute. Using `attrs`, I would first try the code below:

```python
@attr.s()
class Message:
    from = attr.ib()
    # ...
```

But since `from` is a reserved word, I got a `SyntaxError`. Can I customize the name of the field? Something like this:

```python
@attr.s()
class Message:
    _from = attr.ib('from')
    # ...
```

I couldn't find anything on the docs and this example comes from Django model fields.

Thank you!

**Comment by RonnyPfannschmidt** [comment]
Imho This makes no sense, as it wouldn't be usable sanely

**Comment by hynek** [comment]
The Django example IIRC maps the DB column `from` to the field `_from` so that you never access it using the reserved keyword `from` in your code. You cannot have an attribute `from` in Python, with or without `attrs`. The question is what you're *really* trying to achieve.

**Comment by rougeth** [comment]
@RonnyPfannschmidt why?

@hynek I was thinking about using attrs/cattrs as an object serialization (classes from json), at first it seems to be the way.

**Comment by hynek** [comment]
Yeah that sounds like a serialization issue, not attrs. You should look at cattrs and if such renaming isn't supported, open an issue there.

**Comment by rougeth** [comment]
Thank you @hynek.

**Comment by imaurer** [comment]
@rougeth , There is renaming support in `related` which is built on top of attrs. It supports nested classes and does key renaming.

Library:
https://github.com/genomoncology/related

Example Unit test for doing renaming:
https://github.com/genomoncology/related/blob/master/tests/ex05_field_names/test_renamed.py

**Comment by rougeth** [comment]
Thank you @imaurer! I'm testing `schematics`, it seems to have everything I need right now.

**Comment by wsanchez** [comment]
@rougeth Link? Should we add `schematics` to https://github.com/python-attrs/attrs/wiki/Extensions-to-attrs ?

**Comment by hynek** [comment]
I think what he’s saying is that he abandoned `attrs`. 🙃

**Comment by rougeth** [comment]
Kind of, `schematics` isn't an extensions for `attrs`. But, I'm still using it, `attrs` helped me a lot. Thank you @hynek and all the contributes for the awesome lib. 😄
