### ISSUE TITLE
Add 'filter' kwarg to Attribute __init__

### ISSUE THREAD

**Issue by smcveigh-phunware** [python-attrs/attrs#384]
Rather than always having to define a filter function, why not add to `_make.py`

```python
class Attribute(object):
    __slots__ = (
        "name", "default", "validator", "repr", "cmp", "hash", "init",
        "metadata", "type", "converter", "filter"
    )

    def __init__(self, name, default, validator, repr, cmp, hash, init
                 convert=None, metadata=None, type=None, converter=None, filter=False):
        # ...
        bound_setattr("type", type)
        bound_setattr("filter", filter)
```

and to `_funcs.py` (`asdict` for example):

``` python
def asdict(inst, recurse=True, filter=None, dict_factory=dict,
           retain_collection_types=False):
    attrs = fields(inst.__class__)
    rv = dict_factory()
    for a in attrs:
        v = getattr(inst, a.name)
        if a.filter:
            continue   # attribute takes precedent
        elif filter is not None and not filter(a, v):
            continue
        # ...
```
The purpose being to simplify serialization/deserialization to/from JSON or YAML, i.e.  `json.dumps(attr.asdict(...))`

**Comment by Tinche** [comment]
Conceptually that's wrong though, filtering (or not) is a property of the serialization pipeline, not the actual class itself.

I can see the problem with nested classes though. The solution there is for more intelligent serialization libraries, not more fields in attrs :)

**Comment by RonnyPfannschmidt** [comment]
@smcveigh-phunware still a job for the serialization pipelines, not for the class

**Comment by hynek** [comment]
Yeah that looks like a separation of concerns violation to me.

If you want to define serialization metadata while defining your classes, we have `metadata` just for that. Then you could define a filter function that works on that data and you have what you want. 

Shoehorning a functionality like this into attrs’ core APIs is too invasive and arbitrary.
