### ISSUE TITLE
The module name "attr" is different from project name "attrs"

### ISSUE THREAD

**Issue by draplater** [python-attrs/attrs#388]
When I distribute my package, some people run "pip install attr" and complain there is something wrong. It's really confusing to have a different module name.

I think we can add an alias module name "attrs".

**Comment by wsanchez** [comment]
Well, the current module is [`attrs`](https://pypi.org/project/attrs/) in PyPI.  I don't know if you can add aliases, but there is already another module called [`attr`](https://pypi.org/project/attr/), so I think this is a non-starter, sorry.

**Comment by hynek** [comment]
Dupe of #131
