### ISSUE TITLE
no validating collection attributes

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [python-attrs/attrs#39]
currently its not possible to declare an attribute that's something like a `list of Elements` or a `mapping of string to integer`

**Comment by hynek** [comment]
I guess `list_of()`, `dict_of()` validators may be useful.

**Comment by PsyMar** [comment]
This is fairly easy to do if you just write your own validator.  There will almost always be a need to do that for when you have a dict from string to dict from int to dict from string to double, or similar horribleness (which I don't do as much now that I have attrs, but still)

**Comment by exarkun** [comment]
A `testtools_matches` along with the various matchers at http://testtools.readthedocs.io/en/latest/for-test-authors.html#combining-matchers would also address this.

**Comment by erikseulean** [comment]
Is this still something that's worth adding ? I was thinking of something like:

```
list_of((int, string))
```
The argument would be a tuple of types, since `isinstance` works with tuples. 
I have an implementation for this in one of the codebases that I'm working on and would be easy to add it here.

**Comment by hynek** [comment]
The overall problem is that while those validators look useful, in practice you usually need more sophisticated validation and end up using a true validation framework anyway (that can be used from within attrs just fine).

So I'm not sure this is really worth adding and whether we should get on the slippery slope of growing an inadequate validation framework that will just lead to people asking for more features and yet us never reach the power of something like [voluptuous](https://pypi.org/project/voluptuous/)?

**Comment by erikseulean** [comment]
@hynek is this something that's worth having as a separate library, eventually added here https://github.com/python-attrs/attrs/wiki/Extensions-to-attrs that would provide validators to containers ? We have a version currently that allows you to create validators for containers (`list_of`, `set_of`, `dict_of`) plus a generic function that allows you to implement your own container validators at my workplace and I'm willing to open source it, if you consider it could bring some potential value. 

Does it makes sense to have this alongside the typing capabilities specified here ? 
http://www.attrs.org/en/stable/types.html

**Comment by hynek** [comment]
I'm fine with adding anything that's useful to the wiki!  So far I had no reason to remove anything.

--- 

That said, I believe this ticket has been already fixed in #425! Yeah, I can be inconsistent too. 🙈
