### ISSUE TITLE
Pylint not-an-iterable error when specifying type

### ISSUE THREAD

**Issue by lbenka** [python-attrs/attrs#398]
Hello there and thanks for the awesome project. I have a small issue when running pylint.

Having following code
````
from typing import List

import attr

@attr.s
class Child(object):
    name: str= attr.ib()

@attr.s
class Parent(object):
    children: List[Child] = attr.ib()

    def do_work():
        for c in children:
            print(c)
````

and running `pylint --reports no --persistent no <project_root>`

I am getting this output:
`E: 16,17: Non-iterable value self.children is used in an iterating context (not-an-iterable)
`
 http://www.attrs.org/en/stable/examples.html#types 

However when changing things up to different type notation.
```
@attr.s
class Parent(object):
    children = attr.ib(type=List[Child])
```

I am no longer getting this error. Am I doing something wrong?  I like the first annotation more but I am still being annoyed by pylint.

Thanks for the help.

**Comment by RonnyPfannschmidt** [comment]
at first glance this looks like yet another false positive of pylint

**Comment by hynek** [comment]
Yeah please open an issue on pylint’s tracker and see what they have to say.

It’s also better to use mypy for these kinds of checks I think.
