### ISSUE TITLE
auto converting attributes names when serialize attrs object to json

### ISSUE THREAD

**Issue by omershelef** [python-attrs/attrs#402]
when I work with attrs in my web server, I would like to pass the object as a JSON response.
there is no problem for me to serialize the object using `asdict` function. my problem is regarding the naming conventions differences between javascript in python.

for example the following object:
```
@attr.s
class A(object):
     my_var = attr.ib(converter=int)
```

and the asdict function will return:
```
{
    "my_var": 5
}

```

where the javascript/JSON naming conventions are as the following:
```
{
    "myVar": 5
}

```

is there any builtin solution for that problem? or any best practice to solve it?

**Comment by hynek** [comment]
Check out https://github.com/python-attrs/attrs/wiki/Extensions-to-attrs – some of the projects might help there? You may also want to have a look at [glom](https://glom.readthedocs.io/en/latest/).
