### ISSUE TITLE
validator of instanceof should have an option to allow None?

### ISSUE THREAD

**Issue by omershelef** [python-attrs/attrs#403]
Usually when working with static typed languages, when I have a variable of some type, it can be only from that type **or** null value. in attrs when I add a validator it does not allow None value.
for example:

```
    @attr.s
    class B(object):
        pass

    @attr.s
    class A(object):
        var_b = attr.ib(default=None, validator=validators.instance_of(B))
```

do I have any option to allow var_b to be only of the type B but still allow None value? I would prefer not writing my own custom validator.

**Comment by hynek** [comment]
Yes wrap it in attr.validators.optional()

**Comment by omershelef** [comment]
Perfect! thank you!
