### ISSUE TITLE
override generated __eq__ to work with numpy fields

### ISSUE THREAD

**Issue by chobeat** [python-attrs/attrs#409]
I would like to know how to override generated methods in attrs. From the documentation is not clear.

My problem is that if I put some numpy arrays as values, the regular "==" operator fails because `np.array_equal` should be used instead.

The error is the following:

```
    def __eq__(self, other):
        if other.__class__ is not self.__class__:
            return NotImplemented
        return  (
            self.raw,
            self.processed,
        ) == (
            other.raw,
>           other.processed,
        )
E       ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by hynek** [comment]
I’m afraid you’ll have to disable attrs’ __eq__ and write it yourself. This is a super edgy edge case so I don’t think it makes a lot of sense to add special hooks for it. Are you aware of the reason why numpy arrays don't allow for comparison using `==`?

**Comment by chobeat** [comment]
Yes, there's a very explicit error message if you try do it and it makes sense: for the way they make use of python syntax, a == would be ambigous if used to compare 2 arrays, so they offer numpy.array_equal.

>I’m afraid you’ll have to disable attrs’ eq and write it yourself.

Can you explain me how? Just writing a __eq__ method in my class doesn't work because I believe attrs __eq__ is generated afterward.

**Comment by hynek** [comment]
Your approach might work in the future (see #324) until then you'll have to pass  `@attr.s(cmp=False)`.

**Comment by chobeat** [comment]
Oh, perfect, thank you very much
