### ISSUE TITLE
Filter list of objects by attributes values

### ISSUE THREAD

**Issue by avoine** [python-attrs/attrs#444]
Would is possible to add a mecanism to filter objects like it is for asdict and astuple but that returns
matching objects instead of attributes and values?

**Comment by orsinium** [comment]
```python 
filter(operators.attrgetter('name'), objects) 
```
Is this what you want?

**Comment by hynek** [comment]
It’s unclear to me what you want exactly but the filter argument of asdict/astuple. It’s called with the Attribute as the first argument and the value as the second argument.

**Comment by wsanchez** [comment]
@avoine Gonna bounce this out of the queue on the assumption that one of the above suggestions works for you.  Please describe the specific use case and re-open if you disagree.
