### ISSUE TITLE
Add new feature to adapt values (improved converter)

### ISSUE THREAD

**Issue by tds333** [python-attrs/attrs#445]
Hi,
I have used attrs for lot of stuff and it is very useful package. Thx.
But sometimes I had the need to do a little bit more in a converter.
A converter takes only the value and the return value is assigned to the attribute.
I needed something like adaptor where the function receives the class, Attribute, value and the return value is assigned to the attribute.

```
def my_adapter(cls, attribute, value):
...
Result is assigned to the instance attribute
```

I missused the validator to do what I want. But I think it is not the right way to do it.

Full example of use case, where I missuse a validator to do the work:
```
from functools import partial
import attr


def default_typer(inst, attribute, value):
    if value is None:
        value = attribute.default
    value = attribute.type(value)
    setattr(inst, attribute.name, value)


cfg_attr = partial(attr.ib, validator=default_typer)


@attr.s
class FeatureConfig:
    a = cfg_attr(default=False, type=bool)
    b = cfg_attr(default=11, type=int)


def main():
    default_fc = FeatureConfig()
    print(default_fc)

if __name__ == '__main__':
    main()
```

**Comment by piccolbo** [comment]
Same here. Another use case: a class with data.frame as first attribute, a column of the dataframe as the second. The column can be specified as an integer position or as a name. If integer it has to be converted to a name. To do that, one needs access to the first attribute, the data.frame.

**Comment by vlcinsky** [comment]
I had similar need as @piccolbo and ended up fixing the values in `__attrs_post_init__`.

One of use cases is a class, having an attribute with `init=False` which is complex object built from other attributes to `__init__`. An example could be class with `protocol`, `host`, `port` and `path` `__init__` parameters and building internal `uri` parameter built from all those parts:

```python
import attr

@attr.s
class NiceUri(object):
    proto = attr.ib()
    host = attr.ib()
    port = attr.ib()
    path = attr.ib()
    uri = attr.ib(init=False)

    def __attrs_post_init__(self):
        self.uri = f"{proto}://{host}/path"
```

Anyway, if we go the "instance value converter" way, we get an extra complexity for code reader and there is also question about order of execution. If we have attributes `a`, `b` and `c` and `a` instance value converter attempts to use `self.b` - what is expected content of `self.b`? The value passed into `__init__`? The converted value? Is it already available when converting the `self.a`?

I am concerned about readability.

With instance value converter:
- pros:
  - shorter code?
  - the class attribute describes all (nice to read about the input and later instance value on one place)
- cons:
  - surprises in case the converter would try to access attribute which is not yet fully converted
  - if the `attr.ib` line gets longer, the readability suffers anyway

When using `__attrs_post_init__`:
- pros:
  - simpler to understand
  - the `__attrs_post_init__` has full control of execution order
- cons:
  - need to write the `__attrs_post_init__`
  - the input value and instance attribute value are described on two places

So personally I am currently slightly in favour of not adding "instance value converter" feature to keep the `attrs` simple.

**Comment by vlcinsky** [comment]
@tds333 the adapter should not use `cls` but `self` as we need an access to the instance (and it allows to reach class too).

**Comment by vlcinsky** [comment]
@piccolbo thanks for showing how to create tolerant functions.

I would like to remind the purpose of `attrs` as stated in documentation:

> attrs is the Python package that will bring back the **joy** of **writing classes** by relieving you from the drudgery of implementing object protocols (aka dunder methods).
>
> Its main goal is to help you to write **concise** and **correct** software without slowing down your code.

Regardless of possible `validator` and `converter` modifications, few things must be made clear to a programmer using `attrs`:
- is validator applied on input value or on value resulting from applied converter?
- which operations are assigning attribute values to `self`. Such operations are:
  - generated `__init__`
  - converter
  - validator
  - `__attrs_post_init__`
- in what order are operations such as `__init__`, `conver` and `validate` applied
- what is expected order of processing `covert` and `validate` in regards to number of used attributes (can we rely in processing to preserve order of attributes in the class?)

**Comment by piccolbo** [comment]
Yes a little pedantic on my side, sorry, I edited it out. I just wanted to make the point that it doesn't require any awful hack. Most people knew that already. As far as your points, how are they related to the proposal of the OP? The answer to all of your points is "no change is proposed as part of this issue", or I am missing something. What is discussed here is the signature of a converter. If you feel the documentation is insufficient on the order topic, that deserves its own issue.

**Comment by vlcinsky** [comment]
@piccolbo Relation of my comments to OP are:
- OP is proposing changes, which
  - add converter access to class instance
  - promote using converter in non-trivial scenarios modifying class attributes
- such a change may have usability consequences, which might not be obvious at very first glance.

My concern is not about problems to achieve requested results technically, but about possible risk of damaged usability of the `attrs` package.

@hynek is the core contributor and has probably the best sense of what is good for mission of this great package and what is not. I would appreciate his point of view.

**Comment by tds333** [comment]
> @tds333 the adapter should not use `cls` but `self` as we need an access to the instance (and it allows to reach class too).

Cls was used by intention. Because an adapter is called when init is not really done and the state of the instance (self) not ready processed. So Provide only the class to get addtitional information.
Another possible solution could be a converter not only receiving the value but additionally receiving the attribute instance. So the converter can make use of attribute information.

**Comment by tds333** [comment]
In my use case post_init is not really the way to go because I had to provide it for every instance. In post_init the iterate over all attributes and do additional work. This is slower, more fragile and not really elegant way to do it. But also another possibility to solve it.

**Comment by wsanchez** [comment]
Yeah we think that's best addressed outside of attrs.  Maybe like https://github.com/Deepwalker/trafaret

**Comment by hynek** [comment]
You may also want to have a look at https://github.com/hynek/environ_config both for configuration and inspiration how to expand attrs for DSL-like purposes.
