### ISSUE TITLE
Consider inline type definitions or a stubs package

### ISSUE THREAD

**Issue by llchan** [python-attrs/attrs#449]
With the 18.2.0 release, a few new arguments were added to e.g. `attr.s`, and those are not reflected in the typeshed repo yet. The stance in the typeshed repo is to avoid version-specific signatures (see https://github.com/python/typeshed/issues/153), but rather to defer that to inline pyi files in the package itself or stub packages (see [PEP 561](https://www.python.org/dev/peps/pep-0561/)).

Would we be open to including attrs type definitions in pyi files here? If not, perhaps we could package them into a attrs-stubs package? Either way, I think it would be beneficial to include the files in this repo so that the changes are version controlled together.

**Comment by hynek** [comment]
Attrs does that already as of 18.2?

**Comment by llchan** [comment]
Yikes, now I feel silly. My apologies for now looking first! I searched for an attrs-stubs package but didnt look in site-packages for the pyi. Must be something with my mypy setup, I'll debug on my own. Sorry for the spam!
