### ISSUE TITLE
Inheritance does not set typing of generics

### ISSUE THREAD

**Issue by wakemaster39** [python-attrs/attrs#452]
I came up with a simple example below, basically when you have inheritance with a generic, the field type does not get updated with the generic.

This typically isn't an issue but when using cattrs library that depends on the annotations this cause breaking issues. 

Is there a way to force the update in some dunder method?

```
T = TypeVar('T')

@attr.attrs(auto_attribs=True)
class A(Generic[T]):
    a: T

@attr.attrs(auto_attribs=True)
class B(A[int]):
    pass

print(attr.fields(B))

Output:
(Attribute(name='a', default=NOTHING, validator=None, repr=True, cmp=True, hash=None, init=True, metadata=mappingproxy({}), type=~T, converter=None, kw_only=False),)
```

**Comment by euresti** [comment]
Sadly this is not possible without somehow getting rid of "Generic type erasure"  https://www.python.org/dev/peps/pep-0484/#instantiating-generic-classes-and-type-erasure

**Comment by wakemaster39** [comment]
@euresti thanks for this. I will look and read this closer at the PEP for the reasoning. What is the consequence of the below code, it gives me the result I am looking for. I know it is contrived, so other fields would still get inherited, but the one generic field I am having issues with gets overridden.

```
@attr.attrs(auto_attribs=True)
class B(A[int]):
    a: int
```

**Comment by euresti** [comment]
That only sort of works.  The order of the fields (and consequently `__init__`) gets changed (at least it did when I just ran it)

```
from typing import TypeVar, Generic
import attr

T = TypeVar("T")

@attr.attrs(auto_attribs=True)
class A(Generic[T]):
    a: int
    b: T
    c: str

@attr.attrs(auto_attribs=True)
class B(A[int]):
    b: bool

print(A(5, True, "hi"))  # A(a=5, b=True, c='hi')
print(B(5, True, "hi"))  # B(a=5, c=True, b='hi')
```

Thankfully mypy catches this error.
foo.py:20: error: Argument 2 to "B" has incompatible type "bool"; expected "str"
foo.py:20: error: Argument 3 to "B" has incompatible type "str"; expected "bool"

**Comment by hynek** [comment]
I gather this isn’t an attrs issue?

**Comment by wakemaster39** [comment]
@euresti Thanks for the info. I use keyword args for pretty much all of the constructors so this side effect is more than fine for me. I'll close this out since there really isn't much that can be done related to this.
