### ISSUE TITLE
Easier auto-speccing for tests

### ISSUE THREAD

**Issue by Aegdesil** [python-attrs/attrs#462]
What is the recommended way to create a mock instance of a class that is using attrs?

When I'm writing tests for my code, I often mock complex objects to avoid the hassle of instantiating all the required arguments and breaking most of my tests when one object constructor changes. The `unittest` library provides such tools, but unfortunately prevents instance attributes from being detected (see https://docs.python.org/3/library/unittest.mock.html#autospeccing).

The "best" solution to this problem given in the docs is to add class attributes, which I don't like because they add some duplication between the constructor and the class, and can lead to some bugs (forgetting to set it in the constructor makes it shared between all instances...). My solution is to write getters and setters with properties for all public attributes, which can be auto-specced but create a lot of boilerplate code and duplication.

`attrs` seemed to be the perfect tool to remove all this duplication, but attributes are removed from the class since 17.3.0, for the some of the reasons I mentioned. I know it is possible to retrieve them using `__attrs_attrs__` or `attr.fields(MyCls)`, but this does not help me with auto-speccing.

Would it be possible to add a parameter to have something like `attr.s(delete_attributes=False)`, which would override `self._delete_attribs` in the `_ClassBuilder` and revert to the old behavior for people who manually set this option? Or maybe instead of creating public attributes in the constructor, use properties everywhere (but that would obviously be a much bigger change)?

Any thoughts on this?

**Comment by Tinche** [comment]
Uh you could just write a class decorator for yourself that puts the attributes back on the class object yourself, getting them via fields(). A cleaner solution would be creating an autospec-attrs adapter, but I don't know enought about autospeccing to know how feasible that would be.

**Comment by hynek** [comment]
Yeah what Tin said. The information is available to you via `__attrs_attrs__` and `fields()`. It shouldn’t be too hard to implement whatever you need without making core APIs more complex. You should keep in mind, that the reason why we delete those attributes is that it lead to some weird/unexpected behaviors.

**Comment by Aegdesil** [comment]
Yeah, I guess that works. Another solution would be to create a method that wraps `create_autospec` and adds the fields as class attributes just before mocking the class, so that there is no weird behavior when  running the code, just in the tests. This is enough for me so I'll close the issue.

**Comment by noklam** [comment]
@Aegdesil Sorry to comment on an old issue, what does your own version of `create_autospec` looks like?

**Comment by noklam** [comment]
@Aegdesil This, unfortunately, doesn't work for me, probably because one of the missing attributes is some other `class` but not python datatype.
