### ISSUE TITLE
Request: Add auto_converter

### ISSUE THREAD

**Issue by fwannmacher** [python-attrs/attrs#463]
A good feature could be the addition of an auto_converter flag which paired with auto_attrib would use the type of the attribute as its converter.

**Comment by fwannmacher** [comment]
I think that iterables should have only their content converted. That way we should assume that a iterable was given. For more complex types or abstract ones we could just inform that this feature requires a instantiable class with 1 parameter on its constructor.

Folowing my pull request with what I think should be the approach:
https://github.com/python-attrs/attrs/pull/464

**Comment by Tinche** [comment]
I don't think this can work in the general case since the annotations are generally types, not classes, and the logic there would be large (i.e. the entire cattrs project). How do you handle the conversion of Union[str, int], for example?

Also you could use just a library like cattrs, today.

**Comment by fwannmacher** [comment]
> I don't think this can work in the general case since the annotations are generally types, not classes, and the logic there would be large (i.e. the entire cattrs project). How do you handle the conversion of Union[str, int], for example?
> 
> Also you could use just a library like cattrs, today.

I didn't know about cattrs. I think it already has solved the problem :-)

**Comment by wsanchez** [comment]
Cool.  Closing.
