### ISSUE TITLE
Decorator API with auto_attribs=True doesn't work.

### ISSUE THREAD

**Issue by ckutlu** [python-attrs/attrs#466]
When I try to use attribute decorators via auto attributes style, I get an error saying that the name doesn't exist.  This doesn't happen if I initiate attributes with attr.ib().  Is this expected behavior?

Here is an example that fails:
```
@attr.s(auto_attribs=True)
class A:
    x: float

    @x.validator
    def _check_x(self, attrib, value):
        print("Validator called.")
        print(self, attrib, value)
a = A(5)
```
gives

```
Traceback (most recent call last):
  File "test.py", line 5, in first
    @attr.s(auto_attribs=True)
  File "test.py", line 9, in A
    @x.validator
NameError: name 'x' is not defined
```

**Comment by ckutlu** [comment]
I understand, thanks for the prompt response.  That's a bummer, but I guess using attr.ib() for only attributes with validators isn't that much of an ugly workaround.

**Comment by AndydeCleyre** [comment]
This should be mentioned in the Validators section of the examples page, and in my opinion the existing notice in the Validators section of the init page is insufficiently clear, and should explicitly mention that it won't work when using the `@attrs(auto_attribs=True...` decorator.

**Comment by jimcushing-natgeo** [comment]
It might help to note that this still works:

```
@attr.s(auto_attribs=True)
class A:
    x: float = attr.ib()
```

So you still can use type annotations, validators, and `auto_attribs`.

**Comment by alexchandel** [comment]
attrs should provide a workaround for this.  Like

```python

@attr.s(auto_attribs=True)
class A:
    x: float

    @attr.validator
    def _check_x(self, attrib, value):
        print("Validator x called.")
        print(self, attrib, value)

    y: float
    z: float

    @attr.validator_for('y')
    def _check_y(self, attrib, value):
        print("Validator y called.")
        print(self, attrib, value)


a = A(5, 6, 7)
```

I think the first case requires python >= 3.7 `dict`s remembering order insertion.

**Comment by nandoflorestan** [comment]
Almost 7 years later, the following page still contains example code that fails immediately:
https://www.attrs.org/en/stable/init.html#validators

**Comment by hynek** [comment]
> Almost 7 years later, the following page still contains example code that fails immediately: https://www.attrs.org/en/stable/init.html#validators

Would you mind sharing which one? Given we strive to test all our examples with doctest, I find that surprising.
