### ISSUE TITLE
Fields as class attributes

### ISSUE THREAD

**Issue by altendky** [python-attrs/attrs#467]
At some point I got it in my head that `attrs` used to store fields as class attributes with the field's name, but testing back a ways suggests that is not the case (at least not within any `attrs` I would have been exposed to).  This seems a sometimes useful thing when referring to fields is common within a program.  Despite being a thing someone really asked for and that I really wrote for them as an example, I would consider the example below 'contrived'.  Still, specifically of interest is the `@attr_fields` functionality which allows you to reference fields like `Person.age` rather than `attr.fields(Person).age`.

A real solution would have to account for inheritance and the like and perhaps a 'real' scenario would be desired to justify the feature but I though I'd mention it in the meantime in case for some reason this is just a bad idea.  I would expect a real implementation to be an `@attr.s()` parameter.

https://repl.it/@altendky/FrenchFirmSpellchecker-1
```python3
import attr


def attr_fields(cls):
    for field in attr.fields(cls):
        setattr(cls, field.name, field)
    
    return cls


@attr_fields
@attr.s
class Person:
    name = attr.ib()
    age = attr.ib()


@attr.s
class Filter:
    attribute = attr.ib()
    value = attr.ib()

    def __call__(self, other):
        return getattr(other, self.attribute.name) == self.value


people = [
    Person(name='me', age=42),
    Person(name='you', age=37),
]

my_filter = Filter(
    attribute=Person.age,
    value=37,
)

print([person for person in people if my_filter(person)])
```

Output:
```
Python 3.6.1 (default, Dec 2015, 13:05:11)
[GCC 4.8.2] on linux
[Person(name='you', age=37)]
```

**Comment by wsanchez** [comment]
I wouldn't just say it's a bad idea, but blatting names of instance variables onto the class namespace isn't necessarily without some consequences.

Without an actual use case describing what the need is, implementing a solution to an un-described problem isn't generally a good idea.  For one thing, it's impossible to know we've actually addressed the problem, or whether there are better ways to achieve the desired result than the proposed solution here.

I'm going to close this as a result, but if you have such a use case, please describe that in a new ticket, or re-open this one if you think the above solution really us the more appropriate for the problem.

**Comment by altendky** [comment]
@wsanchez, if you have time, what consequences do you have in mind?  If such a feature were added I would presume it would default to disabled if for no reason other than backwards compatibility.

**Comment by wsanchez** [comment]
Scribbling into a namespace always has the potential for side-effects.  I don't think I can anticipate those, but I have to assume that any visible changes to a class can have some effect on things.

But I don't mean to argue about that.  My point it: describe a problem, and let's talk about fixing that problem.  What I see above is a solution to I-don't-know-what.

**Comment by altendky** [comment]
Sure, I acknowledged the situation was undefined but sometimes others have experienced it anyways and know I'm going down a silly path.  Smells and all.  But thank you for the comments.  I foresee a place I might use something like this in my own code so if I do try that I'll come back with that concrete scenario for opinions.

**Comment by wsanchez** [comment]
:-) thanks.

(I don't doubt that there's a thing here; just need to be clear about that the thing is.)

**Comment by hynek** [comment]
You are right that attrs used to expose attributes on the class body. But that had some really weird side-effects and went against our promise to leave the class alone. Check the change log for 16.1 where it was deprecated for more info.

For convenience, we added `attr.field_dict()` in 18.1 which may be useful to you.

**Comment by altendky** [comment]
@hynek, thanks for compensating for my apparently failed attempt to backcheck old versions.  I do agree that it is better to not (by default anyways) clutter up the class.

I probably should be usering `attr.field_dict()` in some places where I presently `getattr(attr.fields(cls), 'name')`.  This is a different scenario where the attribute being identified as an attribute rather than a string is nice for both the locality of the validation that it exists and the 'more natural' usage.  Still, if I get to my actual scenario at some point I'll share it for opinions.
