### ISSUE TITLE
Support for generating builders

### ISSUE THREAD

**Issue by rgabbard** [python-attrs/attrs#468]
Builders are a common pattern for initializing complex objects, especially if they are immutable:

```
@attrs(auto_attribs=True, frozen=True)
class Foo:
   some_field: int

   class Builder:
        def some_field(x: int) -> 'Foo.Builder':
             self.x = x
             return self
        def build(self) -> 'Foo':
             return Foo(self.some_field)

foo = Foo.Builder().some_field(5).build()
```

The pattern is much less common in Python than in some other languages since Python supports optional and keyword constructor arguments.  However, it is still useful in some cases.  For example, today I needed to modify a class like this:

```
@attrs(frozen=True, auto_attribs=True)
class Foo:
    core_field: Any

    @staticmethod
    def create_from_X(x: X) -> 'Foo':
        ....

    @staticmethod
    def create_from_Y(y: Y) -> 'Foo':
       ...

    @staticmethod
    def create_from_Z(z: Z) -> 'Foo':
       ...
```

to have several additional optionally-specified fields with defaults `optional_field_1`, ...., `optional_field_n`.  Adding them all as arguments to the factory methods would be cumbersome.  I could make the factory methods pass along `**kw_args`, but then you lose the discoverability and type-checking you get from having them explicitly specified as arguments.  A cleaner design could be to have the factory methods return a `FooBuilder`, rather than a `Foo`, so that the builder could handle all the optional field configuration in one place while maintaining discoverability and type-checking.  But maintaining builders by hand is a pain.  

Would adding support for builder generation be considered in-scope for `attrs`? Or is it too unPythonic?

(for reference, here is how they are handled in `immutables`, a Java cousin of `attrs`: http://immutables.github.io/immutable.html#builder)

**Comment by rgabbard** [comment]
Ah, I should have Googled more thoroughly first. There appears to be an effort in this direction:

https://bfa.readthedocs.io/en/latest/

However, I think an approach more with attrs (if considered in-scope) could be cleaner and more flexible than what BFA appears to do, based on what I see in the documentation.

**Comment by rgabbard** [comment]
hmm - I think this could be done as a third-party project using a decorator + metadata as described at https://www.attrs.org/en/stable/extending.html .  So perhaps that is the best place to start.

**Comment by wsanchez** [comment]
These are pretty common in Java, not so much in Python, but thanks for the link to `bfa`.  Added to [the wiki](https://github.com/python-attrs/attrs/wiki/Extensions-to-attrs).

In general, if it can be done externally, that's preferable, as it keeps `attrs` "lean and mean".

**Comment by hynek** [comment]
I use builders all the time, so I don't think they're un-pythonic (there's even a ClassBuilder in attrs! :)). But a builder generator is def out of scope for core attrs. That seems like a nice project to build *on top of it*.

**Comment by rgabbard** [comment]
@hynek @wsanchez : Thanks - I've played with this a bit and it should be quite doable outside of attrs.  I'll play with it a bit over Christmas break and if I get something working well, I'll add it to the wiki.

**Comment by hynek** [comment]
What exactly would you want such a builder generate? It honestly sounds like a hairy functionality that is basically _cattrs_, but stepwise?
