### ISSUE TITLE
Protect secrets from __repr__

### ISSUE THREAD

**Issue by webknjaz** [python-attrs/attrs#471]
Looking at https://github.com/hynek/environ_config and my internal attrs classes representing a token response from GitHub API etc.

I know about `repr=False` (and I saw [this hack](https://github.com/hynek/environ_config/blob/69b1c8a/src/environ/secrets.py#L114-L124)) but in my case I don't want to "hide" the attr existence. I want to be able to sanitize it's value.
At @Ansible we have this feature where we can mark vars at different levels as `no_log` and they appeared as censored. I assume it's a quite widely used practice.

With that in mind I'm currently thinking of these few ways:
1) full protection
```python
>>> repr(AttrsClass(secret='value'))
AttrsClass(secret=attr.CENSORED_VAL)  # hide everything
```
2) partially sanitized
```python
>>> repr(AttrsClass(secret='value'))
AttrsClass(secret=attr.CENSORED_VAL('va...e'))  # show some helper parts usually sufficient to recognize that token is smth odd when debugging things
```
3) could be also useful to preserve a pattern
```python
>>> repr(AttrsClass(secret='DFJ-3E3-DF83'))
AttrsClass(secret=attr.CENSORED_VAL('XXX-XXX-XXXX'))
```

P.S. I saw #212 and #453 but I believe this use-case should get a first-class support separately from those.

**Comment by wsanchez** [comment]
My feeling is that this feature is too specific to be in attrs proper, especially the partially sanitized and pattern aspects.

**Comment by RonnyPfannschmidt** [comment]
@webknjaz wouldn't this better be served by having a very specific string class and using it to encode secrets? then this would just be a converter as far as attrs is concerned

**Comment by webknjaz** [comment]
Maybe, yes. Just like this hack: https://github.com/hynek/environ_config/blob/69b1c8a/src/environ/secrets.py#L114-L124

**Comment by droserasprout** [comment]
A bunch of dirty hacks to mask secret values conditionally at the runtime:

```python
from inspect import isclass

from attr import dataclass
from attr._make import _add_repr
from typing import NewType, Optional


class Secret:
    def __new__(cls, typ):
        return NewType('Secret', typ)(cls)


@dataclass(kw_only=True)
class SecretClass:
    top_secret: Secret(Optional[str])

    def mask_secrets(self):
        for attrib in self.__class__.__attrs_attrs__:
            if isclass(attrib.type) and issubclass(attrib.type, Secret):
                object.__setattr__(attrib, 'repr', lambda _: '[MASKED]')
        self.__class__ = _add_repr(self.__class__)
```

**Comment by hynek** [comment]
You can pass a callable for `repr` since 19.2 – should't that solve your problem?

**Comment by webknjaz** [comment]
I guess. It may take some time to actually try it out, though. I'll close this issue for now and will get back or create a new one if something won't satisfy my expectations. Thanks :)
