### ISSUE TITLE
converter expected to return a Tuple where perhaps an Iterable should do

### ISSUE THREAD

**Issue by wsanchez** [python-attrs/attrs#474]
After updating `mypy` from `0.630` to `0.650` for Klein, I get this error:

```console
src/klein/_headers.py:172:18: error: Argument "converter" to "attrib" has incompatible type "Callable[[Iterable[Iterable[bytes]]], Sequence[Tuple[bytes, bytes]]]"; expected "Optional[Callable[[Any], Tuple[]]]"
```

If I'm reading this correctly, the provided converter is a `Callable` (OK) and takes one argument (OK) and returns a `Sequence` (not OK: `Tuple` expected).

The converter specified in [src/klein/_headers.py:172](https://github.com/twisted/klein/blob/update-deps/src/klein/_headers.py#L172) is [`normalizeRawHeadersFrozen`](https://github.com/twisted/klein/blob/update-deps/src/klein/_headers.py#L101):

```python
def normalizeRawHeadersFrozen(headerPairs):
    # type: (Iterable[Iterable[bytes]]) -> RawHeaders
    return tuple(normalizeRawHeaders(headerPairs))
```

This implementation does return a `tuple`, but I wanted to limit my commitment to a `Sequence`.  I think that `converter` should be happy with a `Sequence` in practice, so I'd like to lobby for a looser requirement here.

**Comment by wsanchez** [comment]
Hrm.  I'm realizing that there's no way that `attrs` is requiring a `Tuple` here so this has to be in my code…?

**Comment by hynek** [comment]
I suppose the answer is to play with mypy's `reveal_type()`?

**Comment by euresti** [comment]
What version of mypy are you running?  I'm not seeing that error in the latest `master`.

**Comment by wsanchez** [comment]
Oh, great!  Thanks for finding that @euresti.

**Comment by wsanchez** [comment]
Closing here.

**Comment by hynek** [comment]
Yay SEPs. ;)
