### ISSUE TITLE
A slots=False class inheriting from a slots=True class generates incorrect __getstate__

### ISSUE THREAD

**Issue by mooncake4132** [python-attrs/attrs#475]
I understand that this is a fairly uncommon case, but I was expecting the following to work:
```py
import attr
import copy


@attr.s(slots=True)
class A:
    a = attr.ib()


@attr.s
class B(A):
    b = attr.ib()


b = B(1, 2)
print('ver: {}'.format(attr.__version__))
print('b: {!r}'.format(b))
print('b.__getstate__: {!r}'.format(b.__getstate__()))
print('deecopy(b): {!r}'.format(copy.deepcopy(b)))
```
Output
```
ver: 18.2.0
b: B(a=1, b=2)
b.__getstate__: (1,)
deecopy(b): B(a=1, b=NOTHING)
```

**Comment by hynek** [comment]
What would you expect us to do here though? The problem is that the base class has a `__getstate__` and the subclass hasn’t. Automatically clear the method away? That sounds like it might break stuff.

**Comment by mooncake4132** [comment]
Sorry, I didn't really think through the technical difficulties to fix this issue. It seems like there is already a discussion in #512 #513. I'll close this in favor of those.
