### ISSUE TITLE
Can attrs help with giving a user a `Choice("a|b|c")`

### ISSUE THREAD

**Issue by kootenpv** [python-attrs/attrs#479]
I'm wondering if there is a way to use attrs for the situation in which we want to let a user of an object choose between 3 options.

Ideally:

    @attr.s
    class A():
        x = attr.Choice("a", "b", "c")

    >>> A("d")
    ValueError("'x' must be one of 'a', 'b', 'c'")

    Signature:
    A(x=Choice("a|b|c")) or A(x="a|b|c")

Note that the requirements are:

- User should not have to import anything to pass it to `A`
- User will understand the options it has when looking at the signature, and
- User will get an error if passing an invalid choice

Is there already a way to get this using attrs; I think there is no logical way in basic Python either?

**Comment by hynek** [comment]
That sounds very much like an [enum](https://docs.python.org/3/library/enum.html) to me?

You could store it on the class if you want to avoid imports at all cost:

```python
@attr.s
class A:
    class Choice(enum.Enum):
        A = "A"
        B = "B"
    x = attr.ib(converter=Choice)
```

Typed on my phone but I think it should work?

**Comment by kootenpv** [comment]
Thanks for the response Hynek.

I've tried an enum a well, the good thing is that it does the validation, and your syntax (while still quite verbose) is correct.

It does however throw without giving the options:

    ValueError: 'a' is not a valid Choice

What a bad luck :-) 

Also, we do not get anything from the function signature, even when trying something like:

def Choice(x):
    return enum.Enum("Choice", x.split("|"))

@attr.s
class A:
    x = attr.ib(converter=Choice("a|b|c"))

Neither emacs nor pycharm give information while "in" `A()`.

I'm starting to think it would make sense to really think this through, create our own Choice class in `attrs`?

**Comment by kootenpv** [comment]
This works, but is far from pretty:

```
def Choice(x):
    opts = x.split("|")
    class choice():
        def __init__(self, x):
            if x not in opts:
                raise ValueError("'x' must be one of {!r}".format(opts))
            self.x = x
    return choice

class A():
    def __init__(self, x=Choice("a|b")):
        self.x = x
        
>>> A("d")
ValueError: 'x' must be in ['a', 'b']


```

**Comment by wsanchez** [comment]
Absent an actionable suggestion for what to fix in attrs, closing.
