### ISSUE TITLE
Why does `attr.fields` not work on instances?

### ISSUE THREAD

**Issue by rudasoftware** [python-attrs/attrs#490]
I've found myself writing a number of helper functions that generically handle instances of `attr.s` decorated classes, adapting functionality based on their `Attributes`. Some of them don't care if it's an instance or a type, because they only operate on some other input (e.g. filtering a `dict` to remove keys that aren't attribute names). It's really annoying to try/except around `NotAnAttrsClassError` to use the `fields` function.

Internally, the `fields` function is a really simple lookup based on `__attrs_attrs__`, which *is* available on instances. Even if it's not desirable to rely on indirect resolution, `evolve` gets `inst.__class__` to invoke `fields`, so this behavior could be folded into `fields` itself.

`fields` goes out of it's way to check that its argument is a class, so I'm assuming there must be a reason.
Is it simply historical?
Maybe a Python 2/3 thing?

I *love* `attrs`, by the way. It has liberated me from `namedtuple` hell. XD
Making my own `fields`-like function seemed like a smell to me, so I was curious about this design decision

**Comment by hynek** [comment]
Generally speaking, we try to keep the [envelope of APIs as tight as possible](https://www.youtube.com/watch?v=mTj297sGzxw), to prevent people from having stuff work by accident (and blow up into their faces later) and to make it easier to keep the API guarantees.

It's absolutely not a smell to write a function that solves a particular problem you have. :)
