### ISSUE TITLE
Hook into @attr.s between initial assembly and class building

### ISSUE THREAD

**Issue by petergaultney** [python-attrs/attrs#495]
I use `attr.s` classes everywhere. And in every single case where I use them, I want certain behavior that is not enabled by default in attrs, but which I could easily add if there were a way to hook into the class-building process, between the construction of the `attrs` objects and the rest of the class-builder prep, for all classes in my codebase.

Once I understood how `attrs` performs class building at a high level, it wasn't too hard to accomplish. I copy-pasted most of the `attrs` function from inside `attr._make`, and inserted my own hook, like so:

```
def my_attrs(
        maybe_cls=None,
        these=None,
        repr_ns=None,
        repr=True,
        cmp=True,
        hash=None,
        init=True,
        slots=False,
        frozen=False,
        weakref_slot=True,
        str=False,
        auto_attribs=False,
        kw_only=False,
        cache_hash=False,
):
    def wrap(cls):
        if getattr(cls, "__class__", None) is None:
            raise TypeError("attrs only works with new-style classes.")

        builder = _ClassBuilder(
            cls,
            these,
            slots,
            frozen,
            weakref_slot,
            auto_attribs,
            kw_only,
            cache_hash,
        )

        hook_builder_before_doing_anything(builder)  # this is where the hook needs to live

        if repr is True:
            builder.add_repr(repr_ns)

...   # (middle of function removed for brevity)

    if maybe_cls is None:
        return wrap
    return wrap(maybe_cls)


def hook_builder_before_doing_anything(builder):
    for attrib in builder._attribs:
        # do something useful, like add a validator to attributes matching certain types
```

In my specific use case, I wanted to write a universal validator that would guard against 'False-y' values in attributes that did not have defaults defined.  Something like:

```
def nonfalsy_validator(self, attribute, value):
    """Don't allow strings and collections to have empty/False-y values."""
    if attribute.type in (bool, int, float):
        # doesn't make sense to 'validate' a boolean or int against False-ness
        # since 0 or False are perfectly valid 'values' for those types
        return
    if attribute.default == NOTHING:
        if not value:
            raise ValueError(f'Attribute "{attribute.name}" on class {type(self)} '
                             f'with type {attribute.type} '
                             'cannot have an empty/false-y value!')
```

My solution works brilliantly for my use case, and reduces by ~200% the amount of boilerplate that I need to add to the types that face both my API and my database. 

What I imagine would be useful for other people would be two variants on what I've done.

First, add an argument to `attr.s` that accepts a callback function like the one I've defined, so that instead of defining validators on every item in a class individually, I could define validators for an entire class separately from the class definition itself. E.g.:

```
@attr.s(auto_attribs=True, builder_hook=my_builder_func):
class MyClass:
    foo: str
    bar: int = 2
```

Secondly, and more optionally, add a hook to the `attr` module itself - something like `attr.register_global_builder_hook(your_hook)`, for people like me who want to apply this to an entire codebase without mucking up the definitions of each class individually.  

In my actual use case, I have defined a decorator that actually applies the `attr.s` decorator to all my classes, so instead of decorating with `@attr.s` I decorate with `@MyAttrs`, which encapsulates all my defaults and applies the hook internally, such that the global hook isn't really necessary after all.

This would obviously be an API change like adding `cache_hash`, but it would be additive, so it should not affect existing code.  I would be more than happy to submit a PR along with some examples of how it can be used, if the idea were accepted.  I could further envision other hooks being added at different points in the construction process, but I suspect the majority of use cases would be served by the single hook in the single place I've proposed.

**Comment by hynek** [comment]
So `register_global_builder_hook(your_hook)` is not gonna happen, I feel bad enough about having global state in the validator part.

On the other hand I'm partial to the idea of a class build hook because it would probably allow for really cool new stuff. And attrs was originally intended to be a class building kit. It became what it is now by accident. ;)

**But** this idea comes with one **huge** downside that will require some very hard thinking: it would promote `_ClassBuilder` to become public API. IOW: it would heavily impede the way how we can move inside it.

Could you think of a way to avoid that? Maybe passing the class and a list of attributes to the hook and expecting a class and a list of attributes back (in that case, you'd have to move the call into the builder since the class is replaced for slots)?

**Comment by petergaultney** [comment]
I think you're right about not needing (or wanting) global state. If it were my library I wouldn't allow that either, if I'm honest. :) Like I said, I ended up writing my own wrapper decorator that does the trick nicely wherever I actually need the behavior, without requiring a global hook. I might feel differently if I were in a situation where I had a codebase that I couldn't fully control, but then again, there's always monkey-patching if one is really that desperate.

I also agree that exposing the internals of ClassBuilder as an API is a dangerous path to go down.  Of course, one option there is to expose it without necessarily supporting it - in my case I already knew I was hacking around in things I wasn't truly "meant" to touch. But since you agree that the basic concept creates interesting possibilities, then yes, I prefer the idea of it being supported. You would know better than I how stable the 'API' of the Attributes themselves is.

Receiving the class and list of attributes right after their creation by ClassBuilder would work really well for me. All I needed to accomplish was hooking in to the Attributes as `attrs` understands them, before the class itself was built.  

Would it make sense to also provide `base_attrs` and `base_attrs_map` to the callback? Maybe not, since by the time those are provided, the base class, along with all its validators, converters, and its `__init__` have already been created and aren't modifiable in the same way.

**Comment by mentalisttraceur** [comment]
Thinking out loud: what about enabling this by exposing just enough functionality or public interface to make this possible:

```
@attr.s(...)
@some_other_decorator(...)
class my_class(...):
    ...
```

Currently the inner decorator gets to see the `_CountingAttr` objects, and has the opportunity to modify or reassign any of the attributes before `attr.s` picks them up, including by invoking things like `attr.ib` *again* (minding the possible reordering of the counter).

I haven't yet thought through the spectrum of use cases to have a conclusion myself, but seems worth considering if going for that route might allow for a better interface.

**Comment by petergaultney** [comment]
Does this work if you're using `@attr.s(auto_attribs=True)`? I suspect not, but I might be missing something. When I tried this approach near the beginning of my quest, I had just a raw class to work with.

I think what @hynek and I were discussing is effectively the same thing (being able to modify only the `_CountingAttr` objects, before the __init__ builder and everything else runs) you're suggesting, but it would work for the cleaner approach of `auto_attribs` as well.

**Comment by mentalisttraceur** [comment]
@petergaultney With enough work, it would "work" for `auto_attribs=True`, in that you could still achieve everything that you could otherwise, but at that point you've basically reimplemented all of the logic that `attr.s` uses to parse attributes on the class, so I think you're right. The decorator in-between can be ruled out.

**Comment by hynek** [comment]
I think this is very much related to #653.

**Comment by hynek** [comment]
I believe #653 has fixed this.

**Comment by petergaultney** [comment]
@hynek thank you. am i right in thinking that #653 is what provides this functionality? https://www.attrs.org/en/stable/extending.html#automatic-field-transformation-and-modification

**Comment by hynek** [comment]
Yes!
