### ISSUE TITLE
Unexpected evolve behavior when using python 3.6 type hinting

### ISSUE THREAD

**Issue by AlmogCohen** [python-attrs/attrs#496]
As recommended [here](http://www.attrs.org/en/stable/examples.html#types) I've used the built-in type hinting but unfortunately it has some quirky behavior when used together with `attr.evolve`.

I've created a simple pytest example for python 3.6. Please note that the first test fails while the other pass.

```
import attr


@attr.s
class UsingTyping(object):
    attrib: str = ''


@attr.s
class UsingAttrib(object):
    attrib: str = attr.ib(default='')


def test_using_typing():
    v = UsingTyping()
    non_default_value = 'non-default-value'
    v.attrib = non_default_value
    evolved = attr.evolve(v)

    assert evolved.attrib == non_default_value  # evolved.attrib is sequal empty string.


def test_using_attrib():
    v = UsingAttrib()
    non_default_value = 'non-default-value'
    v.attrib = non_default_value
    evolved = attr.evolve(v)

    assert evolved.attrib == non_default_value
```

So right now I had to revert to the usage as demonstrated by the `UsingAttrib` class, which is pretty ugly compared to the other one :)

I'm using `attrs` version `18.2.0` under Mac OSX Mojave. Please let me know if I can further assist in anyway

**Comment by AlmogCohen** [comment]
This is  a very simple example, but even when some changes are passed to `evolve`, the results are the same.

**Comment by euresti** [comment]
You need `@attr.s(auto_attribs=True)` in order for the first version to work.

**Comment by AlmogCohen** [comment]
Oh I see now, I've missed a small thing in the documentation...

**Comment by AlmogCohen** [comment]
Thank you for the quick response! Provided tests pass with the fix you mentioned.
