### ISSUE TITLE
Docs: provide guidance on how to merge / override

### ISSUE THREAD

**Issue by pkch** [python-attrs/attrs#497]
`attrs` seems like a good choice to define (hierarchical) configurations. A "configuration" is an immutable `attrs`-annotated class, whose attribute values are basic scalar types, lists, or other "configuration" instances.

If such a use case is recommended, it may be worth providing some examples of how to do that in the docs. In particular, it would be very helpful to provide a recipe for overriding an existing configuration with some custom configuration:

```
def override(base: MyConfig, custom: MyConfig) -> MyConfig:
  """Returns a new `MyConfig` instance where each element in the hierarchy
   is taken from `custom` if it's set there, or from `base` otherwise.
  """
```

The docs could say:

1. How to specify elements that are not set. (It's not the same as allowing default values, since if `custom.x.y` is set to a default value of `y`, it will override `base.x.y` that was set to something else.) Defining an `UNSET = object()` sentinel is one approach, but maybe there's something already available in `attrs` to do that?

2. How to implement `override` function? There are some obvious solutions from scratch, but perhaps there's a way to reuse some of the existing `attrs` features.

3. Whether it's a good idea, and how, to convert between a configuration and a plain dict.

**Comment by wsanchez** [comment]
While this is an interesting thought exercise, this sounds like something one could built on top of `attrs`, so I don't think that figuring out the internals of a new function in support of it falls to the `attrs` documentation.

FWIW, I suspect that [`attrs.evolve`](http://www.attrs.org/en/stable/api.html?highlight=evolve) does most of this already.

**Comment by pkch** [comment]
Thanks, I missed `attrs.evolve`. It is quite close to what I had in mind for override (except it only allows to override top-level attributes, not values deeper in the hierarchy).
