### ISSUE TITLE
pretty-printing support

### ISSUE THREAD

**Issue by glyph** [python-attrs/attrs#508]
Attrs `repr`s are super useful for debugging.  But super ugly once they get big!  It would be very handy to support pretty-printing that is aware of column-width and indentation.

**Comment by glyph** [comment]
(Sadly, there's no *public* API to support `pprint.pprint`, but you could subclass `PrettyPrinter` and override `.format` to inherit almost all of its useful behavior and that's *almost* like an API.  And if someone were to monkey-patch that on to the base class, well, it's not like the runtime can stop you.)

**Comment by hynek** [comment]
The sad part is that the wonderful singledispatch was originally developed specifically to make pprint extensible.

**Comment by tommikaikkonen** [comment]
You can use [`prettyprinter`](https://github.com/tommikaikkonen/prettyprinter) to do that. I wrote the `attrs` integration for it. After opting in to the integration, it detects values created from `attrs`-defined classes, and looks at the `attrs` field definitions to decide how to prettyprint it. Here's how the output looks like:

<img width="698" alt="screenshot 2019-02-20 at 23 19 58" src="https://user-images.githubusercontent.com/2487359/53150873-83761100-3566-11e9-9728-a86df62c9a6b.png">

**Comment by hynek** [comment]
I think that should be good enough @glyph? I don't see much of a point to duplicate that work (and have to maintain it). Especially since the output format would bring a swath of people asking for formatting options.

(I've added prettyprinter to https://github.com/python-attrs/attrs/wiki/Extensions-to-attrs)

**Comment by glyph** [comment]
I think this is sufficient.

**Comment by glyph** [comment]
Thanks very much for the pointer @tommikaikkonen !

**Comment by isidroas** [comment]
Another option is the `rich` library: https://rich.readthedocs.io/en/stable/pretty.html?highlight=attrs#rich-repr-protocol
It has support for attrs pretty-printing
