### ISSUE TITLE
Support custom __getstate__, __setstate__ for slotted classes (or improve docs)?

### ISSUE THREAD

**Issue by andhus** [python-attrs/attrs#512]
The assertion fails in the following example, but is ok with `slots=False`:
```
import attr, pickle

@attr.s(slots=True)
class MyClass(object):
    a = attr.ib()
    not_picklable = attr.ib()

    def __getstate__(self):
        return self.a, "replacement"

    def __setstate__(self, state):
        self.a, self.not_picklable = state

mc = MyClass("a", "b")
mc_new = pickle.loads(pickle.dumps(mc))
assert mc_new.not_picklable == "replacement"
```
This is clearly because `attrs` auto creates these methods on the new slots-class: https://github.com/python-attrs/attrs/blob/master/src/attr/_make.py#L601

Is there another prefered way to solve this, or would it be possible to support these methods also for slots-classes? If not, it would be good to clarify this in the documentation for [slotted-classes](http://www.attrs.org/en/stable/glossary.html#term-slotted-classes), it says:

> You can support protocol 0 and 1 by implementing `__getstate__` and `__setstate__` methods yourself. Those methods are created for frozen slotted classes because they won’t pickle otherwise. Think twice before using pickle though.

This is confusing to me, since implementing these methods have no effect for slotted classes?

Somewhat related:
https://github.com/python-attrs/attrs/issues/139
https://github.com/python-attrs/attrs/issues/475

**Comment by hynek** [comment]
You have opened this issue in the best possible moment because I'm prototyping a new API right now and this might go in. No promises about timeline and whether it'll be python2-compatible for now tho.

**Comment by andhus** [comment]
Glad to hear! In the meantime, I made this suggestion: https://github.com/python-attrs/attrs/pull/513. I think it makes sense. Maybe I'm missing something, but isn't the docs (referenced above) misleading/inconsistent with current behaviour?

**Comment by andhus** [comment]
Ok, read the docs more carefully and now understand that "You can support protocol 0 and 1 by implementing `__getstate__` and `__setstate__` methods yourself" refers to `__slots__` classes in general but _not_ to `attr.s(slots=True)` classes. Still don't see any downside from making it possible to define these methods in `attr.s(slots=True)` classes.
