### ISSUE TITLE
`RecursionError` in generated `__hash__`

### ISSUE THREAD

**Issue by mentalisttraceur** [python-attrs/attrs#514]
Hashing a class with an attribute whose value is a bound method from itself causes `RecursionError`:

```Python
@attr.s(frozen=True)
class C():
    a = attr.ib()

    @a.default
    def _(self):
        return self._a

    def _a(self, x):
        return x
```

Now calling `hash(C())` will raise a `RecursionError`, I infer because the hash logic for bound methods tries to hash the instance it is bound to as well, so it tries to hash the instance again, so it tries to hash the bound method again, ....

I think it might be possible to handle this similarly to how `__repr__` handles it?

```Python
>>> C()
C(a=<bound method C._a of ...>)
```

Since logic is already in place to detect that the bound method is pointing back at the instance being `repr`ed and using `...` instead, it would just be a matter of finding a reasonable hash value to substitute when hashing detects recursion too, right?

**Comment by hynek** [comment]
Oof! I don't think the solution of repr is adequate here (and it's also causing problems: #458). I suspect this is an edge case, that we can't support in a nice way. Unless someone has better ideas, I think you should write your own `__hash__`.

**Comment by mentalisttraceur** [comment]
Fair enough, and I'm struggling to think of a real situation where this bug is a problem. Maybe if the recursion is nested in a cycle, not direct, it can unexpectedly break code?

For what I was doing I worked around it because the attribute was private (underscore-prefixed, `init=False`), its value was always a logical consequence of other public attributes, and the class was `frozen=True`, so the attribute didn't need to participate in the `__hash__` anyway.

I suspect that not only is "bound method as an attribute" a rare use-case, it's probably even more rare for it to be anything *besides* the kind of thing I was doing.

Because:

1. you can only do it once the instance is already being constructed (can't call `MyClass(..., foo=the_method_on_this_new_instance)`, which means that it has to be pretty intentional by the class maker to make it happen).

2. you can only create an indirect hash-relevant reference cycle by deliberately breaking the natural relationship between hashing and immutability.

So I think I agree, this is an edge case, and isn't even that important to support.

Feel free to close.

**Comment by hynek** [comment]
OK! Good luck with your black magic. 🙈
