### ISSUE TITLE
Feature Request: An elegant way to handle complex members

### ISSUE THREAD

**Issue by officialcryptomaster** [python-attrs/attrs#516]
Right now, it is not possible to do a converter which will automatically convert a dict to a complex type so we have to define a separate converter function to handle the use case:

```
from typing import Optional
import attr

@attr.s
class Inner:
    a: str = attr.ib()

def optional_dict_to_inner(d) -> Optional[Inner]:
    if d is None:
        return None
    return Inner(**d)

@attr.s
class Outer:
    e: Optional[Inner] = attr.ib(converter=optional_dict_to_inner)
    i: Optional[int] = attr.ib(converter=attr.converters.optional(int))

print(Inner("A"))
print(Outer(e=None, i=1))
print(Outer(e={"a": "A"}, i=1))
```

What makes this worse is mypy is not able to handle a decorator to get around this without giving an error. Specifically, I tried to replace the `optional_dict_to_enclosed` to:

```
def optional_dict_to_obj(obj):
    def _optional_dict_to_obj(d) -> Optional[type(obj)]:
        if d is None:
            return None
        return obj(**d)
    return _optional_dict_to_obj

@attr.s
class Outer:
    e: Optional[Inner] = attr.ib(converter=optional_dict_to_obj(Inner))
    i: Optional[int] = attr.ib(converter=attr.converters.optional(int))

```

But that will cause mypy to complain as it requires type annotation on converters...
```
test_mypy.py:23: error: Unsupported converter, only named functions and types are currently supported
```

It would be nice to have an elegant way to tell the `attr.ib` that you are getting a dict you need to convert an object of a specific type without having to work around it like this... It would be something like `attr.objfromdict` and its optional equivalent `attr.optional_objfromdict` (I suppose the optional version is not required as we can just compose the `attr.converters.optional`):
```
@attr.s
class Outer:
    e: Optional[Inner] = attr.ib(converter=attr.converters.optional_objfromdict(Inner))
    i: Optional[int] = attr.ib(converter=attr.converters.optional(int))
```

**Comment by officialcryptomaster** [comment]
Another simple approach is to have a default `.fromdict()` on each class (and handled correctly in mypy) so the above can be written as:
```
@attr.s
class Outer:
    e: Optional[Enclosed] = attr.ib(converter=attr.converters.optional(Enclosed.fromdict))
    i: Optional[int] = attr.ib(converter=attr.converters.optional(int))
```

**Comment by hynek** [comment]
What you're asking for is serialization. :)

There's multiple solutions for that in attrs and we consciously decided to keep it out of attrs core, because it's a complex topic: https://github.com/python-attrs/attrs/wiki/Extensions-to-attrs

FWIW, my code is kinda full of from_dicts or from_rows (for SQLAlchemy) because expressing such dependencies becomes quite complex and nested objects make it even even more complicated.

I personally find something like this more readable and debuggable:

```python
@attr.s(auto_attribs=True)
class Sub:
    x: int

    def from_dict(cls, d) -> Sub:
        return cls(x=d["x"])

@attr.s(auto_attribs=True)
class C:
    y: int
    s: Sub

    @classmethod
    def from_dict(cls, d) -> C:
        return cls(
            y=d["y"],
            s=Sub.from_dict(d),
        )
```

**Comment by wsanchez** [comment]
Out of scope for `attrs` itself.

**Comment by officialcryptomaster** [comment]
@hynek @wsanchez Thanks for the reply. I still think it would have been super useful to allow an option in attr.s constructor to automatically created the class function `from_dict`. There is no sense is explicitly defining this out every time...

**Comment by officialcryptomaster** [comment]
By the way, @hynek the way you have it, if there are converters and validators on the elements, they will not be used in the `from_dict`... that is why in my version I would opt to just call the instance with `cls(**d)` to make sure those are all applied correctly.

**Comment by hynek** [comment]
FWIW, I’m personally not a huge fan of converters except for the simplest cases. And the same is true for automatically generated from_dicts: you run into problems quite fast (e.g. if you don’t control the dict and want different names in your models).

If you really want to, you can quite easily write a from_dict Generator based on attrs’ metadata yourself BTW.
