### ISSUE TITLE
“__attrs_post_init__” is bypassed

### ISSUE THREAD

**Issue by wencan** [python-attrs/attrs#526]
```python
import attr

@attr.s(auto_attribs=True)
class Frozen(object):
    x: int
    y:int = attr.ib(init=False)

    def __attrs_post_init__(self):
        print("__attrs_post_init__")
        object.__setattr__(self, "y", self.x + 1)

f = Frozen.__new__(Frozen)
f.x = 100
f.y = 200
print(f)
```

outoput:
```
Frozen(x=100, y=200)
```

"__attrs_post_init__" not executed

**Comment by Hanaasagi** [comment]
`attrs` will generate `__init__` method dynamically and add to Class.

https://github.com/python-attrs/attrs/blob/de84609505845edc0e05c2ff918a44085816e35e/src/attr/_make.py#L1611-L1612

You call `__new__` directly to create a object, but `__init__` is not. So `__attrs_post_init__` is not executed.

```Python
f = Frozen.__new__(Frozen)
f.__init__(x=100)
```

**Comment by hynek** [comment]
Yep, @Hanaasagi nailed it.

You can try this yourself like this:

```pycon
In [1]: class C:
   ...:     def __init__(self):
   ...:         print("hi")
   ...:

In [5]: C()
hi
Out[5]: <__main__.C at 0x10fc86518>

In [6]: C.__new__(C)
Out[6]: <__main__.C at 0x10fc3ef28>
```

Hope this makes sense.
