### ISSUE TITLE
What is the best way for me to check if an object is attrs decorated class?

### ISSUE THREAD

**Issue by ethanjyx** [python-attrs/attrs#537]
Say I have
```
import attr
@attr.s(kw_only=True, frozen=True)
class A:
    a: int = attr.ib()

obj = A(a=1)
```

Then how do I do something like `isinstance(obj, attrs)` to check if this class is attrs decorated? 

it seems by playing with it we have 
```
>> dir(obj)

['__annotations__',
 '__attrs_attrs__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'a']
```

is it always correct to use `'__attrs_attrs__' in dir(obj)` to check whether obj belongs to a attrs decorated class?

**Comment by hynek** [comment]
Check out `attr.has(A)`

**Comment by brendan-simon-indt** [comment]
That checks if the CLASS in an attrs decorated class.
The OP asked how to tell if an INSTANCE is an attrs class instance.

I tried this.

```python
`isinstance( obj, AttrsInstance )`
```

but `mypy` gave an error:
```
Only @runtime_checkable protocols can be used with instance and class checks
```

**Comment by brendan-simon-indt** [comment]
Actually `attr.has( obj )` does work, but `mypy` doesn't like it because it expects and `AttrsInstance` argument.

Should the argument type be `Union[ AttrsInstance, object ]` or `AttrsInstance | object` or just `object` ?

**Comment by hynek** [comment]
I suspect this might have been fixed by #997?

**Comment by brendan-simon-indt** [comment]
Possibly.  I'm using Debian 10 Buster, which has Python 3.7 installed and attrs `22.1.0` (in a venv).

Looks like a recent merge, so maybe the next attrs release will fix this.  Will it fix it for older pythons too?

**Comment by hynek** [comment]
according to https://github.com/python-attrs/attrs/pull/997#issuecomment-1216181282 it should

**Comment by gtpalmer** [comment]
`attrs.has` is insufficient. For example
```
@attrs.define
class Foo:
  foo: str

class Bar(Foo):
  bar: int

print(attrs.has(Bar)) # Prints True, but Bar does not have an attrs decorator.
```
