### ISSUE TITLE
How should I get an attribute default (including calling a factory)?

### ISSUE THREAD

**Issue by altendky** [python-attrs/attrs#545]
I was helping out in `#python` and there was a question about setting an instance attribute back to default.  I didn't find a way provided by attrs to do that .  Did I miss it?  If not, would that be of interest?  I haven't thought much about how it should be provided but here's the implementation I wrote for them.

https://repl.it/@altendky/UnpleasantUnconsciousPi-1
```python
def get_default(instance, attribute):
    default = attr.fields_dict(type(instance))[attribute].default
    if isinstance(default, attr.Factory):
        if default.takes_self:
            return default.factory(instance)

        return default.factory()
    
    return default
```

**Comment by hynek** [comment]
Yeah that looks about right to me. Not sure this is a common enough thing to document/support in attrs proper?

**Comment by altendky** [comment]
That's fair.  For completeness, here is an adjusted example with handling of no-default situations.

https://repl.it/@altendky/UnpleasantUnconsciousPi-2
```python
get_default_default_sentinel = object()

def get_default(instance, attribute, default=get_default_default_sentinel):
    value = attr.fields_dict(type(instance))[attribute].default
    
    if value is attr.NOTHING:
        if default is get_default_default_sentinel:
            raise Exception('No default set for attribute: {!r}'.format(attribute))
        
        return default
    
    if isinstance(value, attr.Factory):
        if value.takes_self:
            return value.factory(instance)

        return value.factory()
    
    return value
```
