### ISSUE TITLE
attr.Attribute docs don't exclude the factory parameter

### ISSUE THREAD

**Issue by altendky** [python-attrs/attrs#546]
https://github.com/python-attrs/attrs/blob/615054392a18ae5c9c82e845ddaa107f03f160b8/src/attr/_make.py#L1667

except `factory`...

https://github.com/python-attrs/attrs/blob/615054392a18ae5c9c82e845ddaa107f03f160b8/src/attr/_make.py#L80

**Comment by hynek** [comment]
Ah yes, that's because `factory` is just syntactic sugar for `default=Factory(...)`. I've clarified the docs in 06999cda0abc29e761f2476ad4c05dae583406f8. Thanks!
