### ISSUE TITLE
More helpful error from __hash__

### ISSUE THREAD

**Issue by jtrakk** [python-attrs/attrs#547]
Sometimes I try to hash something that I've accidentally made unhashable. Currently, the error message I get doesn't help me debug and find the object at fault. Could it instead give some more helpful diagnostic information when I make these mistakes?

```py
import typing as t

import attr


@attr.dataclass(frozen=True)
class A:
    x: t.Set


@attr.dataclass(frozen=True)
class B:
    x: t.List[A]


b = B(A([1]))
hash(b)


# line 17, in <module>
#     hash(b)
#   File "<attrs generated hash 7d0e09ef201452b6240ec01bd1f683c719ab45bd>", line 4, in __hash__
#   File "<attrs generated hash 5e949f8a620bcc175eb03109de20ae34b1872982>", line 4, in __hash__
# TypeError: unhashable type: 'set'

```

**Comment by hynek** [comment]
This error is not coming from attrs but from the Python runtime so there isn’t anything we really can do without slowing down attrs considerably.

**Comment by jtrakk** [comment]
Could it at least put the class name in, like 'attrs generated hash of B object'?

**Comment by hynek** [comment]
Yes, that will come as part of other work that is in progress (e.g. #492).
