### ISSUE TITLE
enhancement suggestion: regex validator helper

### ISSUE THREAD

**Issue by kurtbrose** [python-attrs/attrs#549]
I find this little snippet to be repeatedly useful:

```python
def _re_validator(pattern):
    regex = re.compile(pattern)
    def validate(instance, attribute, val):
        if not regex.match(val):
            raise ValueError("invalid {}: {} (must match {})".format(
                attribute.name, val, pattern))
    return validate
```

you use it something like this:

```python
name = attr.ib(validator=_re_validator('^[A-Za-z][A-Za-z0-9_]*$'))
```

(that defines "this must be a valid public identifier; letter, followed by letters, numbers, and underscores")

seems like with a little bit more polish on exceptions and docstring, it might be handy for others

**Comment by hynek** [comment]
I think I would merge a PR with that feature.

**Comment by wsanchez** [comment]
+1.  Maybe call it `re_match`?

**Comment by kurtbrose** [comment]
Cool, is that name consistent with other built-in validators of attrs?

**Comment by hynek** [comment]
I suspect `matches_re` would fit better?

**Comment by kurtbrose** [comment]
https://github.com/python-attrs/attrs/pull/552 first cut at it...

it's interesting that there are a bunch of tests asserting that e.g. `__repr__()` and the text of exceptions are what they are

I think that could make sense in case people are checking text of exception messages and you want to make sure nobody is updating them perhaps?  but there is no comment to that effect; also if the goal was making it easier for users of the library to parse out specific exceptions, having a class hierarchy would probably make sense?

```
AttrError(Exception)
AttrValidationValueError(AttrError, ValueError)
AttrValidationTypeError(AttrError, TypeError)
# etc...
```

**Comment by energizah** [comment]
My experience is that for regex checks I almost always want `re.fullmatch` or `re.search`, and pretty much never `re.match`. The problem of course is that Python 2 doesn't have `re.fullmatch`. I am not wild about embedding an `re.match` API into attrs, since it has unexpected behavior in common cases (principally, not anchoring at the string start). If `import attrs` will be Python 3-only, that might be a good opportunity to introduce this feature, using `re.fullmatch`.

The above snippet is also missing a way to enable the useful `re.MULTILINE` flag, though that's independent of the choice of `re` function.

**Comment by kurtbrose** [comment]
@energizah good point -- there's a lot of freedom in the design space for passing through flags and selecting different underlying functions; I'll fiddle with that a little

re: "not anchoring at the string start" -- this is very easy to check, and it does anchor at the start of the string

```python
>>> re.match('a', 'ba')
>>>
```

you probably meant does not anchor at string end, which is true:

```python
>>> re.match('a', 'ab')
<_sre.SRE_Match object at 0x0000000002CEF2A0>
>>>
```

however, this is easy to emulate by using the `"\Z"` token (https://stackoverflow.com/a/30212799)

**Comment by hynek** [comment]
Fixed long time ago. :)
