### ISSUE TITLE
Feature request: Add validation option to `auto_attribs`

### ISSUE THREAD

**Issue by qpwo** [python-attrs/attrs#550]
This is just an idea. Some users of a library I work on use static analysis and other users don't, so we use both type hinting and validation on the attributes. We have several classes like this:

```python
from attr.validators import instance_of
@attrs
class C:
    x: str = attrib(validator=instance_of(str))
    y: str = attrib(validator=instance_of(str))
    z: int = attrib(validator=instance_of(int))
```

And in this [search](https://github.com/search?q=%22validator%3Dinstance_of%22&type=Code) you can see that most users of `instance_of` stick it on every attribute when they use it at all.

It would be nice if `attrs` had a kwarg like `auto_attribs_with_validation` that would convert the below class to the above class:

```python
@attrs(auto_attribs_with_validation=True)
class C:
    x: str
    y: str
    z: int
```

Then of course if you executed `c = C("foo", "bar", "baz")` you would get a `TypeError`.

I'm aware that it may not be worth adding another kwarg to attrs.

If this is a good idea, then I can probably write the PR.

**Comment by qpwo** [comment]
@rgabbard pointed out to me that some types cannot be fully instance-checked, e.g. all subscripted generics from `typing`, like `List[int]`. So `auto_attribs_with_validation` could do a few things:

Option A: Error out at class definition if there are any un-checkable types

Option B: Strip the subscripts off the generics, so
```python
@attrs(auto_attribs_with_validation=True)
class C:
    nums: List[int]
```
would become
```python
@attrs
class C:
    nums: List[int] = attrib(validator=instance_of(List)) # no [int]
```
and other sorts of un-checkable types would still error out.

Option C: Do nothing and let the user discover that their types are un-checkable.

**Comment by rgabbard** [comment]
@qpwo : This appears to basically be https://github.com/python-attrs/attrs/issues/301 updated for the existence of `auto_attribs` and type annotations.

**Comment by wsanchez** [comment]
Sounds like we agree this is a dup. I'm going to close this out as such.
