### ISSUE TITLE
init unique_filename is problematic for exception aggregation

### ISSUE THREAD

**Issue by belm0** [python-attrs/attrs#558]
We had a case where a custom converter was often failing due to an app issue.  The traceback will include a line with a unique ID based on the initial attr values in the class:

```
File "<attrs generated init 81db48c8801f50d1c320ad1b8d1e0028320432b2>", line 3, in __init__
```

Having a unique ID in the traceback in turn causes problems for exception fingerprinting (e.g. by Sentry).  I'm not thrilled about doing custom traceback filtering for such cases, and would like to explore other options.

I wonder what the full rationale is for ensuring the unique filename, and whether it could be made optional.

Including a hash of the attribute values is essentially like dumping the values of all attributes of a class instance as part of the traceback whenever there is a constructor error regarding a single attribute-- which is less than precise error reporting.

https://github.com/python-attrs/attrs/blob/dc1b5a01e98a9ba49d45ad07ba6ae0ee2d9c1b8e/src/attr/_make.py#L1268

**Comment by hynek** [comment]
> I wonder what the full rationale is for ensuring the unique filename, and whether it could be made optional.

The rationale is that we need a unique but fake file name to feed into linecache so you you pdb step through the generated methods.  I’m very much open to change some of this behavior (there’s been a few related issues) but debuggability of generated methods is a non-negotiable property.

**Comment by belm0** [comment]
To clarify, this problem came up when using a lambda for an attrib converter, causing each program to end up with a different hash.

What exactly is the uniqueness requirement in this case?  The hash should ideally reflect the source code (i.e. static, deterministic) and not beyond.  Would using `cls.__module__` and `cls.__qualname__` be sufficient?

**Comment by hynek** [comment]
> To clarify, this problem came up when using a lambda for an attrib converter, causing each program to end up with a different hash.
> 
Are you sure it’s the _same_ class? I can’t check right now but the hash should be over the definition of the method so it _should_ be stable? I would like to make it nicer/human readable, I just didn’t get around to it.

**Comment by euresti** [comment]
I see this whenever our server restarts.  And I've been wondering what causes it.  

So it's the **same** class but it ends up with a different hash because of the ids of the functions used. Here's a minimal example:

```
import attr

def to_int(x):
    return int(x)

@attr.dataclass
class Foo:
    x: int = attr.ib(converter=to_int)

    def __attrs_post_init__(self) -> None:
        raise Exception("Foo")

Foo(6)
```

On each run you get a different traceback:
```
Traceback (most recent call last):
  File "foo.py", line 16, in <module>
    Foo(6)
  File "<attrs generated init ffbad27a615cd941c6e78e9521839574191a5a83>", line 3, in __init__
  File "foo.py", line 12, in __attrs_post_init__
    raise Exception("Foo")
Exception: Foo
```

The hash is generated from the `repr(attrs)` but in this case it changes:
```
[Attribute(name='x', default=NOTHING, validator=None, repr=True, cmp=True, hash=None, init=True, metadata=mappingproxy({}), type=<class 'int'>, converter=<function to_int at 0x1086cf0d0>, kw_only=False)]
```
And here's another run:
```
[Attribute(name='x', default=NOTHING, validator=None, repr=True, cmp=True, hash=None, init=True, metadata=mappingproxy({}), type=<class 'int'>, converter=<function to_int at 0x101f2f0d0>, kw_only=False)]
```

**Comment by hynek** [comment]
Yeah should be definitely fixed then.

**Comment by belm0** [comment]
I notice that in tracebacks the python interpreter will only show the names of functions, not the address.  Presumably Attribute repr needs to filter function values this way.

**Comment by hynek** [comment]
So just for posterity, this is the reason why we can't just use `__module__` and `__qualname__`:

```python
class C:
    pass

D = C

class C:
    pass


print(f"{ D.__module__ }.{ D.__qualname__ }")
print(f"{ C.__module__ }.{ C.__qualname__ }")
```

What we need is an id that is unequivocal per class, but stable over restarts. Removing the id from the function reprs doesn't help here, because of the same reason: it could be different functions with the same name.

Ideas?

**Comment by belm0** [comment]
Which problem is worse: nondeterministic tracebacks, or some outlier case where all attrs are identical except for a function param with overloaded name, affecting pdb debugging?

**Comment by hynek** [comment]
That depends on your use-case. FWIW, one of the most common FUD arguments against `attrs` is/was that you can't properly debug generated code.

I guess we could lower the probability by using qualnames/modules as part of the function repr?

**Comment by euresti** [comment]
Here's a proposal:

Generate the filename from the qualified name (e.g. `__attrs__generated_{__module__}_{__qualname__}.py`. Check the `linecache` to see if that file exists.  If it does, then modify the filename (append a number e.g. "`_2`")  Repeat until you find an unused filename.

Tools like sentry might get confused if you rearrange this code.  But I believe having repeated classes like this might be rare enough that this is good enough.

If this sounds like a decent solution I can work on a PR.  

Oh and for the record it appears that sentry uses the following information to determine a "fingerprint"  

>Depending on the information available, the following data can be used for each stack trace frame:
> 
> * Module name
> * Normalized filename (with revision hashes, etc. removed)
> * Normalized context line (essentially a cleaned up version of the sourcecode of the affected line, if provided)

From https://docs.sentry.io/data-management/rollups/?platform=python#grouping-by-stacktrace

**Comment by hynek** [comment]
Sounds great! I guess we have to take care about thrradsafety here?

**Comment by belm0** [comment]
I suspect `__qualname__` is sufficient for the common case-- and it's desirable for being the most readable and not subject to change when files are moved around in the project.

Please consider the variant where `__qualname__` is the default, and append `__module__N` on collision.

**Comment by hynek** [comment]
That would lead to more unpredictable name churn though. I think it's quite common that you have the same classname in different packages/modules. Depending on import order and other randomness, the numbers could change wildly.

Making the module part of the file name is coherent with how it's work with non-attrs classes, so I think that's the best way forward overall.

**Comment by euresti** [comment]
Question: What does this mean in the code:

    # We cache the generated init methods for the same kinds of attributes.

I can't find any cache aside from the linecache.  And we don't look up anything in that.

**Comment by hynek** [comment]
I think it means the linecache, that it gets re-used for the identical class? I really want to get rid of all that crap, especially so we maybe can put the name of the class into the docstring.
