### ISSUE TITLE
attr for functions?

### ISSUE THREAD

**Issue by peteroconnor-bc** [python-attrs/attrs#569]
I was wondering if there's been any thought towards extending `attr` to functions.  I was thinking it could be useful to deal with the frequent duplication of defaults and types that happens in most codebases.  e.g.: 

    def func_1(a: int = 1, b: float = 2.5) -> float:
        return a*b

    def func_2(c:float=3.4, d: bool =True) -> float:
        return c if d else -c

    def main_function(a: int = 1, b: float = 2.5, d: bool = True) -> float:
        return func_2(func_1(a=a, b=b), d=d)

.. has defaults and types defined in multiple places, which easily leads to bugs.  Alternatives like **kwargs and dependency-injection, tend to cause obfuscation.  With attrs, it could become something like:

    @attrs
    def func_1(a = attrib(default=1, type=int), b = attrib(default=2.5, type=float) -> float:
        return a*b

    @attrs
    def func_2(c = attrib(default=3.4, type=float), d=attrib(default=3.4, type=bool)) -> float:
        return c if d else -c

    @attrs
    def main_function(a = func_1.args.a, b = func_1.args.b, d = func_2.args.d) -> func2.return.type:
        return func_2(func_1(a=a, b=b), d=d)

Which gets rid of all duplicated types and defaults.  All the validators, factory-constructors, and converters already built into attrs could also be useful.  If only defining types and defaults, we could even just simplify that to:

    @attrs
    def func_1(a: int = 1, b: float = 2.5) -> float:
        return a*b

    @attrs
    def func_2(c:float=3.4, d: bool =True) -> float:
        return c if d else -c

    @attrs
    def main_function(a = func_1.args.a, b = func_1.args.b, d = func_2.args.d) -> func2.return.type:
        return func_2(func_1(a=a, b=b), d=d)

This arose from an unloved [Python-Ideas proposal](https://mail.python.org/pipermail/python-ideas/2019-April/056452.html) which basically proposes this, plus attribute-documentation [which would be nice too](https://github.com/python-attrs/attrs/issues/357#issuecomment-378807967), as a built-in language feature.  

Bonus is that this could easily evolve into a better means of enforcing [function contracts](https://andreacensi.github.io/contracts/)

**Comment by RonnyPfannschmidt** [comment]
This looks like a job for a completely new library, why burden attrs with that

**Comment by arnimarj** [comment]
I believe typeguard can do something similar

**Comment by hynek** [comment]
Yeah this is out of scope. You may want to look at https://smarie.github.io/python-makefun/ talk to @smarie whether your needs could be met.

**Comment by smarie** [comment]
Thanks hynek for the redirect ! Yes `makefun` coud certainly help to implement one of the ideas proposed in the discussion you mention (proposal for a `@functools.passes_args(f)` decorator). It can easily be experimented in the library if you wish to. In that case please open an issue with a bit more detailed spec, and even a PR if you feel tempted :)
 
However I agree with your opinion that this will not be sufficient.

For the record, I am currently working on this topic of type/default/doc definition reusability for classes **again** (so like `attrs`, `pydantic` and like my previous attempt `autoclass`+`valid8`) but this time trying to stick to bare minimal functionality (so only fields and init, nothing more). It does not and probably will not cover the scope you mention, but in case you're interested you can simply follow the repo :) Note that right now it is done inside a repository about "mix-ins" named [`mixture`](https://smarie.github.io/python-mixture/) but I might make it independent. Warning: this is early early stage (no validator or convertors support yet, planned next week).

**Comment by smarie** [comment]
Follow-up on this discussion: the library I was mentioning above is now independent and released. It is named [`pyfields`](https://smarie.github.io/python-pyfields/). @hynek , @RonnyPfannschmidt  I would love to get your objective feedback if you have a minute or two to test it :)

It was greatly inspired by giants (`attrs` in particular) and proposes an alternative where field-related code is entirely segregated in the field (not in `__init__`, not in `__setattr__`). The field definition is an object that we can manipulate and therefore maybe think about reusing in function signatures as @peteroconnor-bc you suggest (actually I already do it when generating the signature of the `__init__`, but we could extend this to "filling function signatures"). If we manage to do it for fields, then doing it for "any arg" will be a piece of cake, although the question will soon arise about "should it remain in pyfields or move away in a pyargs lib".

Best,
Sylvain

**Comment by peteroconnor-bc** [comment]
Thanks @smarie for the pyfields link.  Looks like there's some competition in the market now!

**Comment by smarie** [comment]
You're welcome. I would not call this "competition" though, just an alternative with a different design philosophy (strong field segregation). We're all in the same pythonic boat :)
