### ISSUE TITLE
Errors in stub files

### ISSUE THREAD

**Issue by euresti** [python-attrs/attrs#578]
I ran mypy on the .pyi files and found the following errors:

```
src/attr/validators.pyi:17: error: Type variable "attr.validators._T" is unbound
src/attr/validators.pyi:17: note: (Hint: Use "Generic[_T]" or "Protocol[_T]" base class to bind "_T" inside a class)
src/attr/validators.pyi:17: note: (Hint: Use "_T" in function signature to bind "_T" inside a function)
src/attr/validators.pyi:20: error: String argument 1 '_V' to TypeVar(...) does not match variable name '_M'
src/attr/validators.pyi:20: error: "object" not callable
src/attr/validators.pyi:34: error: Unexpected '...'
src/attr/validators.pyi:43: error: Variable "attr.validators._M" is not valid as a type
src/attr/validators.pyi:44: error: Variable "attr.validators._M" is not valid as a type
```

I believe most of these errors get masked by turning the signature in question in `Any` however I was surprised that the CI didn't catch them.  So I looked into what's happening.  I think mypy will not display errors in installed stub files.  (It's not like you as a user of an installed library can fix it so why bother)  

I thought the easy fix would be to change the tox run line to :

```
[testenv:typing]
basepython = python3.7
deps = mypy
commands = mypy src/attr/*.pyi tests/typing_example.py
```

But it seems tox doesn't do file globbing.  
```
mypy: can't read file 'src/attr/*.pyi': No such file or directory
```

Is there another solution?  I'm no tox expert.

**Comment by hynek** [comment]
> I ran mypy on the .pyi files and found the following errors:

Oops! I kinda wondered if they're somehow checked implicitly!

> Is there another solution? I'm no tox expert.

Honestly, it's just five files I don't think it's worth trying to come up with hacks. We don't add files that often:

```ini
commands = mypy tests/typing_example.py src/attr/__init__.pyi src/attr/converters.pyi src/attr/exceptions.pyi src/attr/filters.pyi src/attr/validators.pyi
```

**Comment by euresti** [comment]
I worry a little about a new file being added.  But that's probably for another day.

**Comment by hynek** [comment]
Yeah, screw Future-Hynek and Future-David! ;)

If it makes you feel better: I'd welcome an entry to the PR checklist that reminds us to fix that line if files have been added?

**Comment by wsanchez** [comment]
How about something like:
```sh
commands = sh -c 'mypy tests/typing_example.py $(find src -name "*.pyi")'
```

**Comment by hynek** [comment]
I thought about something like that but we’ve just made the dev env work on Windows, I’d prefer to to not break it again. :|
