### ISSUE TITLE
Support for singletons

### ISSUE THREAD

**Issue by perkinslr** [python-attrs/attrs#579]
When writing applications, I often have several singletons in the main file.  Python doesn't have a clean way to create singletons, which leads to lots of code like

    class A(object):
        ....

    a = A()

much like functions in the pre-decorator days.  I can work around it with something like

    def single(x):
        return x()

    @single
    class A(object):
        ....

but I haven't found a clean way to do that.  It would be nice if there was a flag to pass to `attr.s` to either default-construct the class and bind it to the top level name, or to insert an instance attribute.  This would make it obvious when reading the code that there is only one copy of it expected.  I'm more inclined toward the instance attribute, since that shouldn't interfere with code reading tools as much.

    @attr.s(instance="a")
    class A(object):
        ...

    print(A.a) # prints A()

**Comment by RonnyPfannschmidt** [comment]
In python modules are singletons

**Comment by hynek** [comment]
I think you a word here Ronny. :)

**Comment by glyph** [comment]
A good rule for metaprogramming is to never specify the name of an attribute via a string; this makes it super difficult for tools to inspect, and for humans to read.  So a better way to express this, if for some reason we wanted to, is:

```python3
@attr.s()
class A:
   a: "A" = attr.singleton()
```

But, that raises the question - why?  And how is this related to attrs?  It seems like it should be a different library.  My vote would be to reject this feature and put it in a different library if the OP so desires.

**Comment by nicoddemus** [comment]
I agree with @glyph that this feature wouldn't be a good fit for `attrs`.

Also, IMHO the definition of a "singleton" should never be in the class: using a class as a singleton is a *client* decision, not a decision that should be made when a class is defined. If an application wants to use a certain class as a singleton, it is the application's call, so it can just create a global instance and stuck that somewhere accessible. Using a class instance as a singleton shouldn't really be *forced* upon all users of that class.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus for the singleton pattern the "client decision" happens at implementation time, hence my suggestion to just use a module

**Comment by nicoddemus** [comment]
> @nicoddemus for the singleton pattern the "client decision" happens at implementation time, hence my suggestion to just use a module

Yeah I agree completely with that (sorry if it seemed I was disagreeing somehow).

**Comment by wbolster** [comment]
i think there's consensus this can be closed as ‘won't fix’?
