### ISSUE TITLE
Increase prominence of python3/dataclass "style" in intro materials

### ISSUE THREAD

**Issue by quicknir** [python-attrs/attrs#587]
I looked at attrs at some point when evaluating how to solve certain issues. I looked at pages like this: https://www.attrs.org/en/latest/overview.html and probably a couple of others. On a lot of prominent documentation what you mostly see is the python 2 "style" where you have `attr.b` on every single line. I thought that this was mostly the only way to use it; then I flip over to dataclasses and I see how it works much more cleanly with the type annotations, and it's in the standard, so I start using dataclasses.

Fast forward a bit and the limited dataclass API is not meeting my use case, I was on the verge of monkey-patching it when someone told me to take a second look at attrs. This time I dig deeper in and I realize that you can have something just as nice as `@dataclass` if you simply do `@attr.s(auto_attribs=True)` and use type annotations in just the same way.

I'd suggesting adding prominent examples into the docs of this approach. Having to use `attri.b` for more advanced use cases is of course fine but having it on every single line feels like boilerplate. And the type annotations are very nice as well and it's not immediately obvious at least to a relative beginner that these are usable just as cleanly with attrs. Basically, somebody coming to attrs from dataclasses should immediately see that attrs can do everything that dataclasses can do, just as well/cleanly, in common use cases. It's my fault of course for not reading the docs more carefully but when you're in a rush this can easily happen; if this were more obvious I probably would have gone with attrs from the beginning. In the past you probably had more people who just needed to be introduced to the overall idea, but with dataclasses in the standard and more and more awareness I think you'll see more people landing on the attrs home page already knowing dataclasses.

Anyway, just a thought! Thanks for the kw_only option, can't believe dataclasses dropped it. Cheers.

**Comment by hynek** [comment]
Yes, this is something that rather irks me too. The reason why we haven't changed it yet is because I want to introduce a nice syntax first. Which is taking longer, and longer.

One thing though which I keep forgetting myself: to some people the charm of attrs is that they specifically don't have to deal with static types in Python. While _I_ really like them, there is no general consensus on them and sometimes it's nice to just hack together a quick class.

**Comment by wsanchez** [comment]
I agree that the docs should default to Py3 syntax and better showcase type support, though this may be a dup of #553.  It's related, in any case.

**Comment by hynek** [comment]
This has been fixed in #863
