### ISSUE TITLE
attrs.org does not redirect to https url

### ISSUE THREAD

**Issue by wbolster-eiq** [python-attrs/attrs#588]
currently, `http://www.attrs.org/` (http) is a working website. and so is `https://www.attrs.org/` (https).

the website should only be reachable over https, and the http version should redirect.

(noticed this via some search results hits that somehow poiinted to the plain http site.)

**Comment by hynek** [comment]
The domain is served through RTD and i have set the https-only option, but I believe it doesn't work. Alex Gaynor had an issue open with them. 😐

**Comment by hynek** [comment]
Looks like RTD fixed it.
