### ISSUE TITLE
Deprecated attrs mypy plugin mentioned in docs

### ISSUE THREAD

**Issue by droserasprout** [python-attrs/attrs#594]
I am getting `Unexpected keyword argument` mypy errors for my slightly modified attrs' dataclasses on latest attrs 19.3.0 and mypy 0.740. It took me some time lurking docs and github issues to realize there's no plugin I forgot to add, just mypy fails to recognize attr.s after I've wrapped it like this:
```
def dataclass(cls):
    cls = attr.s(kw_only=True, auto_attribs=True)(cls)
    cls.__attrs_post_init__ = _fix_attrs_nothing
    return cls
```
There's no mypy errors using plain attr.s. So maybe add exact versions which use a separate attrs plugin? By the way, how to wrap attr.s correctly without breaking static typing? Sorry for off-topic, I'm not sure if this question deserves a separate ticket.

**Comment by hynek** [comment]
This seems to be the currant 'official' workaround: https://github.com/python/mypy/issues/5406#issuecomment-490545167

**Comment by droserasprout** [comment]
No luck neither with TYPE_CHECKING (no way to pass kw_only=True) nor with mypy.plugins.attrs dicts workaround.

**Comment by euresti** [comment]
Hi. Yeah currently setting the kw_only=True  must be done on the class itself not on a helper.  (This is true for pretty much every other default value except for `auto_attribs` and that's only because `attr.dataclass` existed.   Only thing I can think of doing is:

```
_T = TypeVar("_T")
def fixed(cls: Type[_T]) -> Type[_T]:
    cls.__attrs_post_init__ = _fix_attrs_nothing
    return cls

@fixed
@attr.dataclass()
class Foo:
    ...
```

I think that might work.

**Comment by droserasprout** [comment]
Thanks for your participation. Some of our classes will have more decorators LOC than declaration itself that way but it's a nice solution otherwise :)

Also since mypy plugin exists and being actively developed this ticket's title is incorrect. Something like "Docs should indicate there's no action required to activate mentioned mypy plugin".

**Comment by hynek** [comment]
I believe this is not an issue anymore. Expanding attrs decorators is covered in <https://www.attrs.org/en/stable/extending.html>.
