### ISSUE TITLE
Use validator/default as decorator in inherited class

### ISSUE THREAD

**Issue by ahelm** [python-attrs/attrs#603]
Hello,

I was recently trying to play with attrs and decided to have a class-specific validators for attributes. Something like this:

```python
import attr


@attr.s
class Foo:
    prop = attr.ib(validator=attr.validators.instance_of(str))

    @prop.validator
    def _check_prop_in_Foo(self, attribute, value):
        valid_strings = ("foo", "bar", "baz")
        if not value in valid_strings:
            raise TypeError(f"Props can only be one of {valid_strings}")


@attr.s
class Bar(Foo):
    @prop.validator
    def _check_prop_in_Bar(self, attribute, value):
        valid_strings = ("bar",)
        if not value in valid_strings:
            raise TypeError(f"Props can only be one of {valid_strings}")


Bar(prop="bar")
```

This raises obviously a `NameError`.

I am not sure if it would make sense as a feature as you can use a function for validation or rewrite a few things. But it would be interesting in making it cleaner.

**Comment by ahelm** [comment]
I also just realized. This applies also for `default`  as well. The following will raise `NameError` as well.

```python
import attr


@attr.s
class Foo:
    prop = attr.ib()


@attr.s
class Bar(Foo):
    @prop.default
    def _default_for_prop(self):
        return "default prop in Bar"


print(Foo())
print(Bar())
```

**Comment by hynek** [comment]
It is AFAIK consistently throughout attrs, that if you want to change the property of an attribute, you have to re-define it and I think that's a good thing. attrs allows for redefinition of attributes in subclasses just fine.

**Comment by ahelm** [comment]
Thanks for the reply. As said, it was more like a thought experiment. Even if it might be repetitive, I think changing the attribute is a good idea.
