### ISSUE TITLE
Is Python 3.4 support being dropped?

### ISSUE THREAD

**Issue by altendky** [python-attrs/attrs#606]
Looks like the tests are failing, should I PR to remove 3.4 support or is it intentionally being kept around?  A quick search for 3.4 didn't turn up any other issues.

**Comment by hynek** [comment]
Ugh yeah, I don't want to deal with that.

Please use something like https://www.structlog.org/en/stable/changelog.html#backward-incompatible-changes as the newsfragment – thanks!

**Comment by hynek** [comment]
Fixed by #608

**Comment by altendky** [comment]
Thanks.
