### ISSUE TITLE
Despite attrs having relevant stubs. There is unresolved attribute reference error in the docstring !

### ISSUE THREAD

**Issue by akarsh1995** [python-attrs/attrs#609]
Look at the image a snapshot in PyCharm.  

There's linting error *unresolved attribute reference* in the docstring. Whereas defining classes with `__init__` method gives no such error.  

Look at the underlined attribute `attribute_with_attr`.

<img width="488" alt="image" src="https://user-images.githubusercontent.com/25827628/71879608-7a793880-3154-11ea-979c-a257f6f6d8f1.png">

```python
import attr


@attr.s
class UsingAttrs:
    """
    class created using attrs shows linting error.

    Attributes
    ----------
    attribute_with_attr : str
    """
    attribute_with_attr: str = attr.ib(default='some_string_value')


class NotUsingAttrs:
    """
    class created normally does not show linting error.

    Attributes
    ----------
    attribute_without_attr : str
    """
    attribute_without_attr: str

    def __init__(self, param='some string value'):
        self.attribute_without_attr = param

```

**Comment by euresti** [comment]
I believe PyCharm does its own type hinting outside of mypy.  https://www.jetbrains.com/help/pycharm/type-hinting-in-product.html

**Comment by wsanchez** [comment]
Should we open a ticket for somehow supporting PyCharm so we can dup this sort of ticket to that, or do we just want to say we don't support PyCharm and close this?  I suspect this will come up again…

**Comment by akarsh1995** [comment]
> Should we open a ticket for somehow supporting PyCharm so we can dup this sort of ticket to that, or do we just want to say we don't support PyCharm and close this? I suspect this will come up again…

I Posted same issue on SO, @hynek answered it as well : https://bit.ly/2N4KXV2. Looks like he wants it to be closed @wsanchez.

**Comment by wsanchez** [comment]
OK, closing
