### ISSUE TITLE
Converter says: TypeError: string argument without an encoding

### ISSUE THREAD

**Issue by mozesa** [python-attrs/attrs#610]
Hello,

I bumped into the below error msg.

```text
Traceback (most recent call last):
  File "C:/Users/mozesa/PycharmProjects/V316-Production-Line/mvc_v316_prod_line/ehh.py", line 40, in <module>
    test = Test("StrinG", "ByteS")
  File "<attrs generated init __main__.Test>", line 3, in __init__
TypeError: string argument without an encoding
```

It happens whenever I try to convert str to bytes.

```python
import attr


@attr.s
class Test:
    string: str = attr.ib(converter=str)
    byte: bytes = attr.ib(converter=bytes)


test = Test("StrinG", "ByteS")
```

The root cause of the problem is that `bytes` awaits for an `encoding` parameter.
So a workaround...

```python
import attr


@attr.s
class Test:
    string: str = attr.ib(converter=str)
    byte: bytes = attr.ib(converter=lambda x: bytes(x, encoding="utf-8"))


test = Test("StrinG", "ByteS")
```

I search through the issues but I couldnt find it.
Sorry If it has been posted.

Thanks for your help.

**Comment by wsanchez** [comment]
You workaround is correct.  This isn't an `attrs` bug; a converter is a callable that takes a single argument, and `bytes` does not do that.

**Comment by mozesa** [comment]
Thanks for you to make it clear.
