### ISSUE TITLE
``__ne__`` dunders changing?

### ISSUE THREAD

**Issue by botant** [python-attrs/attrs#626]
I found that ``__ne__`` dunders are changing during the lifetime of a class. 

I'm using Python 3.7 on Ubuntu and the latest version of ``attrs``.

To reproduce the issue, try this:
```
import attr
A = attr.make_class('A', [], eq=True)
print((id(A.__eq__), A.__eq__.__module__, A.__eq__.__qualname__, id(A.__ne__), A.__ne__.__module__, A.__ne__.__qualname__))
B = attr.make_class('B', [], eq=True)
print((id(A.__eq__), A.__eq__.__module__, A.__eq__.__qualname__, id(A.__ne__), A.__ne__.__module__, A.__ne__.__qualname__))
```

I believe this is happening because ``_make_eq`` returns the module-defined ``__ne__``:

```python
def __ne__(self, other):
    """
    Check equality and either forward a NotImplemented or return the result
    negated.
    """
    result = self.__eq__(other)
    if result is NotImplemented:
        return NotImplemented

    return not result


def _make_eq(cls, attrs):
   ...
    return local_vars["__eq__"], __ne__
```

This should be easy to solve. If someone can confirm whether this is indeed unintended, I'll create a PR this weekend.

Thanks!

**Comment by hynek** [comment]
Ah yes, changing qualnames are unfortunate!

**Comment by botant** [comment]
Can I submit a PR for this?

**Comment by hynek** [comment]
sure!

**Comment by hynek** [comment]
This has been fixed.
