### ISSUE TITLE
__attrs_post_init__ is not called on the derived class instances

### ISSUE THREAD

**Issue by deeagle001** [python-attrs/attrs#628]
Hello,

I have a problem, while I would like to derive from an `attrs` class. The derived class does not add any field, just overwriting custom methods and implementing the `__attrs_post_init__` method. For this reason, I did not apply the `attr.s` decorator to the derived class as no new field was added.
Unfortunately, instances from this derived class did not call the `__attrs_post_init__` method.
I assumed, this behavior was also inherited from the base class, as this is rather a metaclass feature than a pure inheritance one, but it seems this is not the case.

Example code:

```python
import attr

@attr.s(auto_attribs=True)
class MyBaseClass:
    my_field : str

class MyInheritedClass(MyBaseClass):
    def __attrs_post_init__(self):
        my_field = "hardcoded"
        print("I am not called!")

obj = MyInheritedClass('field_val')
assert obj.my_field == "hardcoded"
```

I cannot even check, whether the inherited class has applied `attr.s` on it to fix manually, as the `attr.has()` returns `True`, even if it was not applied (because the base class has fields.).

Can this be an inheritance friendly feature or have an inheritance friendly equivalent?

**Comment by hynek** [comment]
This is on purpose: `attrs` writes _all_ its code when assembling the class for performance reasons.

Applying `@attr.s` indeed fixes it (if you add `self.` before `my_field` that is :)).
