### ISSUE TITLE
Access to Attribute (attr.filters examples)

### ISSUE THREAD

**Issue by bruchar1** [python-attrs/attrs#636]
I'm not sure if the bug is in documentation or in attrs itself, but the example about include and exclude filters, given in http://www.attrs.org/en/15.0.0/examples.html#converting-to-dictionaries, does not work.

```
@attr.s
class User(object):
    login = attr.ib()
    password = attr.ib()
    id = attr.ib()
attr.asdict(User("jane", "s33kred", 42), filter=attr.filters.exclude(User.password, int))
```
gives me `AttributeError: type object 'User' has no attribute 'password'`

**Comment by bruchar1** [comment]
Oups! I was in the wrong version for the documentation...

**Comment by hynek** [comment]
May I ask _how_ you ended up in such an old version fo the docs?

**Comment by bruchar1** [comment]
https://www.google.com/search?client=firefox-b-d&q=attrs+filter
