### ISSUE TITLE
Request: Allow access to class attributes

### ISSUE THREAD

**Issue by peteroconnor-bc** [python-attrs/attrs#639]
Sometimes it would be nice to be able to access an attribute from a class to inspect it.  Currently, there seems to be no way to do it.  Suppose I want to access the "intercept" attribute of AffineFunc: e.g. 

    from attr import attrs, attrib
    
    @attrs
    class AffineFunc(object):
        slope = attrib(default=1.)
        intercept = attrib(default=0.)
    
        def __call__(self, x):
            return self.slope*x + self.intercept
    
    print(AffineFunc.intercept)  # Gives error, but expect: '_CountingAttr(counter=20, _default=1.0, repr=True, eq=True, order=True, hash=None, init=True, metadata={})'

Gives you: 

```
Traceback (most recent call last):
  File "/opt/shining_software/code_examples/attr_request.py", line 16, in <module>
    print(AffineFunc.intercept)
AttributeError: type object 'AffineFunc' has no attribute 'intercept'
```
One example is in unit-tests where you want to inspect the default value to compute what the expected result of something should be.  Is there a good reason why this is not allowed?  And would it be difficult to enable?

**Comment by Tinche** [comment]
Use [`attr.fields`](https://www.attrs.org/en/stable/api.html#attr.fields) or [`attr.fields_dict`](https://www.attrs.org/en/stable/api.html#attr.fields_dict) my friend, and rejoice!

**Comment by peteroconnor-bc** [comment]
I do rejoice at fields.

But still, it seems like it should be possible to just do `AffineFunc.slope.default` instead of `fields_dict(AffineFunc)['slope'].default`.  Is there a reason for the first syntax not working?

Also - it does not get at the thing I really wanted - to use one class's attribute to define an attribute for another class.  Lets stretch the example (sorry if it seems contrived):

    @attrs
    class AffineFunc(object):
        slope = attrib(default=1.)
        intercept = attrib(default=0.)

        def __call__(self, x):
            return self.slope * x + self.intercept

    @attrs
    class AffineMultiInterceptFunc(object):
        myslope = AffineFunc.slope  # <-- Here we just reuse the field from AffineFunc
        offsets = attrib(type=Sequence[float], default=np.linspace(0, 1, 10))

        def __call__(self, x):
            return [AffineFunc(slope=self.myslope, intercept=b)(x) for b in self.offsets]

You cannot do this using `fields` either, because there appears to be a distinction between `_CountingAttr` and `Attribute`.

**Comment by Tinche** [comment]
This used to be the case actually, but was removed because:
1) it was a source of bugs
2) can't work for slot classes anyway

So we, the attrs maintainers, concluded this should be removed.

Also note that `attr.fields` returns named tuples, so you could do `fields(AffineFunc).slope.default`.

Also, as you've noted, `_CountingAttr`s get transformed into Attributes when the class is processed by `@attrs`. You could write a function yourself to turn `Attribute` into `_CountingAttr` though, easily.

If it's just the default you're after, this isn't too horrible:
```
from attr import fields as f

@attrs
class AffineFunc(object):
    slope = attrib(default=1.)
    intercept = attrib(default=0.)

    def __call__(self, x):
        return self.slope * x + self.intercept

@attrs
class AffineMultiInterceptFunc(object):
    myslope = attrib(default=f(AffineFunc).slope.default)
    offsets = attrib(type=Sequence[float], default=np.linspace(0, 1, 10))

    def __call__(self, x):
        return [AffineFunc(slope=self.myslope, intercept=b)(x) for b in self.offsets]
```
If you really want this functionality, you can wrap `@attrs` yourself and post-process the class to your hearts desire - it's not too complicated.
