### ISSUE TITLE
Support auto-conversion for annotated attributes

### ISSUE THREAD

**Issue by xlotlu** [python-attrs/attrs#644]
To me this was unexpected behaviour:

```python-console
>>> @attr.s(auto_attribs=True)
... class Moo(): 
...     price: float 
...     quant: int 
... 
>>> Moo("12", "5")                                                      
Moo(price='12', quant='5')
```

this being, of course, redundant:

```python-console
>>> @attr.s(auto_attribs=True) 
... class Moo(): 
...     price: float = attr.ib(converter=float) 
...     quant: int = attr.ib(converter=int) 
```

Another argument to `attrs` would do the trick, e.g. `auto_converters=True`. My personal expectation is for it to be implied by `auto_attribs=True`, but it does make sense to default to `False` at least in the beginning (and maybe go through a transition period later).

Later edit: `auto_converters` need not apply only to `auto_attribs`. This could be a valid use-case as well:

```python-console
>>> @attr.s(auto_converters=True) 
... class Moo(): 
...     price = attr.ib(type=float) 
...     quant = attr.ib(type=int) 
```

**Comment by hynek** [comment]
That works for only a very narrow number of types tho.

You could probably write yourself a converter that uses the type information to convert?

**Comment by xlotlu** [comment]
> That works for only a very narrow number of types tho.

@hynek that caused me a repeated parse error, until I read into the API and discovered that optional and default are implemented using converters as well.

Coming from other tools, this seems like a very strange design decision. In fact, not having values converted by default was a total surprise (leaving values unconverted isn't even an option elsewhere).

> You could probably write yourself a converter that uses the type information to convert?

Sorry to turn this into a support forum. Wouldn't that still mean I'd have to attach it to all fields manually? I couldn't find a way to apply one class-wide.

Only now did I entirely process the meaning of this line from the docs under Extending -> Types:

> Currently, attrs doesn’t do anything with this information but it’s very useful if you’d like to write your own validators or serializers!

Thank you.

**Comment by hynek** [comment]
The thing that seems to confuse you is that Python type hints (regardless of what `attrs` does or not) are just that: meta information.

What I meant with my sentence is that your approach would only work with types that take exactly one argument like `int` or `str` (and even str falls apart the moment you put in bytes with w.g. your name). In real world code that's not very common. You're gonna have things like `List[int]`, `Tuple[int, str]` or classes like `Optional[SomeOtherClass]`. There is nothing we could do with this information automatically.

**Comment by xlotlu** [comment]
> The thing that seems to confuse you is that Python type hints (regardless of what `attrs` does or not) are just that: meta information.

Well, I know what type hints are in the context of Python. I was indeed confused, but by something deeper: my own assumptions about what `attrs` is.

I came here looking to find something that does data loading and validation like `marshmallow`, and does object creation like `django`'s ORM / `sqlalchemy`'s declarative mode. I was blinded by my own expectations well enough to fail to parse what's right there in the title: "Classes Without Boilerplate". Nothing less, nothing more. :)

Stumbling across annotation support and `auto_attribs` only added to my bias. In my head it was "look, it also works like `pydantic`". So then, imagine my stupor when discovering that `type` is only metadata, and that you need a `converter` to do what *I* expected it to do. In that haze I came here and submitted this issue.

> What I meant with my sentence is that your approach would only work with types that take exactly one argument like `int` or `str` (and even str falls apart the moment you put in bytes with e.g. your name). In real world code that's not very common. You're gonna have things like `List[int]`, `Tuple[int, str]` or classes like `Optional[SomeOtherClass]`. There is nothing we could do with this information automatically.

Well, `pydantic` does handle all this. But although I would love to see a new contender, it makes sense you may not want to take the library in this direction. If that is so, do close the issue. I'll leave it open in case... just.. maybe.

**Comment by hynek** [comment]
pydantic is validation framework, attrs is a class toolkit. You could build something like pydantic **on top of attrs** (and some have: https://github.com/python-attrs/attrs/wiki/Extensions-to-attrs) but attrs is a different layer of abstraction.
