### ISSUE TITLE
all instances updated when updating default dict

### ISSUE THREAD

**Issue by furlongm** [python-attrs/attrs#651]
Not sure if this is a bug or if it's the expected behaviour?

```
import attr

@attr.s
class D(object):
    m = attr.ib(default={'a': 1})

x = D()
y = D()
print(x.m)
print(y.m)
y.m.update({'a': 2})
print(x.m)
print(y.m)
```

Output
```
{'a': 1}
{'a': 1}
{'a': 2} <-- Was not expecting this one to change
{'a': 2}
```

**Comment by hynek** [comment]
This is expected Python behavior. A dict is a mutable datastructure and the way you use it, there's only one instance of it (common mistake is to use them as default arguments `def f(x={})`).

Use `factory=dict` instead.

**Comment by furlongm** [comment]
Ok, thanks for the explanation. This worked as expected:

```
@attr.s
class D(object):
    m = attr.ib()
    @m.default
    def m_default(self):
        return {'a': 1}
```
