### ISSUE TITLE
TypeError when using properties, super(), and slots=True

### ISSUE THREAD

**Issue by radugrosu** [python-attrs/attrs#652]
Below is an almost exact replica of issue 102, which is persisting in 19.3.0.

```python
import attr


@attr.s(slots=True)
class A:
    @property
    def f(self):
        pass


@attr.s(slots=True)
class B(A):
    
    @property
    def f(self):
        super().f()


B().f()
```
produces 

`TypeError: super(type, obj): obj must be an instance or subtype of type`.

**Comment by hynek** [comment]
This doesn't seem to be an issue anymore? I'm getting `TypeError: 'NoneType' object is not callable` which makes sense because you're trying to call a property that returns a None. Feel free to ping if I'm missing something.
