### ISSUE TITLE
[RFC] Drop support for older Python versions (2.7 and 3.5)

### ISSUE THREAD

**Issue by sscherfke** [python-attrs/attrs#654]
I propose that we end support for Python 2.7 and Python 3.5.

Python 2.7 is already EOL and the last patch for 3.5 will be released [this July](https://www.python.org/dev/peps/pep-0478/) (if I interpret the PEP correctly).

According to [pypistats.org](https://pypistats.org/packages/attrs), the share of py27 is approx. 11% and declining.  Py35 has approx. 7%.

Setting py36 as minimum version would allow us to use these features:

- [f-Strings](https://www.python.org/dev/peps/pep-0498/)
- [dict ordered](https://www.python.org/dev/peps/pep-0468/)
- [type annotation syntas](https://www.python.org/dev/peps/pep-0526/)

These features would in turn allow us to:

- Use f-Strings everywhere. =)
- Make `auto_attribs=True` the default (and deprecate this kwarg altogether) (#487)
- Implement (optional) auto-convertion/-validation based on type annotations (#424, #649)
- Write test with attrs classes that directly use type annotations (auto_attrs) w/o worrying about syntax errors on older versions
- Use inline type annotations and get rid of the pyi files which could increase readability and maintainability of the code.
- Get rid of compatibilty code which would also increase maintainability.

This would require a new major release. The next one will be v20 which is, as chance would have it, a nice round number. ;-)

**Comment by wsanchez** [comment]
Per `pypistats python_minor attrs --last-month`:

```console
| category | percent | downloads  |
|----------|--------:|-----------:|
| 3.7      |  38.26% |  9,540,224 |
| 3.6      |  27.61% |  6,882,498 |
| 2.7      |  13.54% |  3,376,839 |
| 3.8      |  12.10% |  3,017,537 |
| 3.5      |   8.00% |  1,993,390 |
| null     |   0.31% |     76,454 |
| 3.4      |   0.14% |     35,484 |
| 3.9      |   0.04% |      9,089 |
| 3.10     |   0.00% |        295 |
| 3.3      |   0.00% |        139 |
| 2.6      |   0.00% |         81 |
| 3.1      |   0.00% |          1 |
| Total    |         | 24,932,031 |

Date range: 2020-05-01 - 2020-05-31
```

**Comment by hynek** [comment]
I'm afraid 2.7 support is one of our main advantages over dataclasses and I don't want to leave those users in the rain (I'd have to lie if I said, that I have zero Python 2.7 apps in prod).

We've made this statement so we won't reverse course anytime soon: https://www.attrs.org/en/stable/python-2.html

I hope that our hand is gonna get forced sooner than later.

---

That said, I'm intend to make the new `attrs` namespace 3.6+ and allow for more 3.6+-only modules.

**Comment by wsanchez** [comment]
Given the above, is there any value in keeping this open?

**Comment by hynek** [comment]
I guess not. We should open a fresh one once our hand is forced.

**Comment by wsanchez** [comment]
| category | percent | downloads  |
| -------- | ------: | ---------: |
| 3.7      |  45.25% | 24,490,529 |
| 3.6      |  19.08% | 10,326,905 |
| 3.8      |  17.87% |  9,673,213 |
| 3.9      |   5.29% |  2,864,858 |
| null     |   4.58% |  2,476,303 |
| 2.7      |   4.03% |  2,179,034 |
| 3.5      |   3.82% |  2,066,489 |
| 3.4      |   0.05% |     26,575 |
| 3.10     |   0.03% |     17,305 |
| 2.6      |   0.00% |         53 |
| 3.3      |   0.00% |         40 |
| 3.2      |   0.00% |          3 |
| 3.1      |   0.00% |          1 |
| Total    |         | 54,121,308 |

Date range: 2021-04-01 - 2021-04-30

**Comment by hugovk** [comment]
![image](https://user-images.githubusercontent.com/1324225/119543270-2696e000-bd99-11eb-8bb7-d46a7819454b.png)

**Comment by sscherfke** [comment]
What I do not understand is why we have to support py27 in *new feature* releases?

Why can’t we declare the current (or an upcoming) major versions as last version supporting 2.7 and only provide bug fixes for it?

**Comment by hynek** [comment]
> Why can’t we declare the current (or an upcoming) major versions as last version supporting 2.7 and only provide bug fixes for it?

That's what we more or less do. The credo is that if it's hard/complicated in Python 2, don't bother. If it's trivial, why not? I'm sure there's grateful people out there for it.

---

I draw the line when CI becomes a pain and/or Tidelift goes to 0 (I'm constantly at $50.77 which is just barely above minimal payout).
