### ISSUE TITLE
mypy's stubgen not generating stubs __init__ properly for @attrs classes

### ISSUE THREAD

**Issue by cazador481** [python-attrs/attrs#665]
I am not sure if this is the write place to put this, or if it should goto mypy issues.   

When I generate stubs using mypy's stubgen I find that I am forced to use the attrib = attr.ib(...) to get the stub for __init__ to have the attributes in them.   Even then the typing information for the attributes are wrong.

When I do 
```
@attr.s(auto_attribs = True)
class Dummy:
  var: str
```
and run stubgen against it.
The stub I get looks like
```
def __init__(self)->None
```
I expect
```
def __init__(self, var: str)->None
```

If I do
```
@attr.s()
class Dummy:
  var: str = attr.ib()
  var2 = attr.ib(type:str)
```
I get closer to the expected output, but it is missing the type information
```
def __init__(self, var: Any, var2: Any)->None
```

**Comment by hynek** [comment]
This looks very much like a mypy issue to me. At least I wouldn't know what to do about it.
