### ISSUE TITLE
Multiple inheritance error when using slots

### ISSUE THREAD

**Issue by jacobg** [python-attrs/attrs#667]
The following classes definitions causes an error:
```python
    @attr.s(auto_attribs=True, frozen=True, slots=True, collect_by_mro=True)
    class Foo:
        foo: str

    @attr.s(auto_attribs=True, frozen=True, slots=True, collect_by_mro=True)
    class Bar:
        bar: str

    @attr.s(auto_attribs=True, frozen=True, slots=True, collect_by_mro=True)
    class Baz(Foo, Bar):
        baz: str
```

```
>       class Baz(Foo, Bar):
E       TypeError: multiple bases have instance lay-out conflict
```

Note that this error occurs on master with a commit that seems to purport to fix this problem:
https://github.com/python-attrs/attrs/pull/635

Removing the `slots` decorator kwargs resolves the error.

Is there a workaround that supports slots?

**Comment by hynek** [comment]
To be clear: #635 has nothing to do with this problem and the problem exists in 19.3 too.

I suspect it's related to the way we create slotted classes in https://github.com/python-attrs/attrs/blob/b02335f59dbd441397d190942ee603bc1d5d9a98/src/attr/_make.py#L711

Since slots become True by default in NG, we should have a look if we can fix this.

**Comment by Tinche** [comment]
An even smaller test case:
```
import attr


@attr.s(slots=True)
class A:
    a = attr.ib()


@attr.s(slots=True)
class B:
    b = attr.ib()


@attr.s(slots=True)
class C(A, B):
    pass

```

**Comment by Tinche** [comment]
Actually, C doesn't even have to be an attrs class:

```
import attr


@attr.s(slots=True)
class A:
    a = attr.ib()


@attr.s(slots=True)
class B:
    b = attr.ib()


class C(A, B):
    pass
```

In fact, browsing the Python docs (https://docs.python.org/3/reference/datamodel.html#notes-on-using-slots):

> Multiple inheritance with multiple slotted parent classes can be used, but only one parent is allowed to have attributes created by slots (the other bases must have empty slot layouts) - violations raise TypeError.

So this is a Python limitation.

**Comment by hynek** [comment]
Thank you for the research Tin! I will add an entry to the glossary.

**Comment by jacobg** [comment]
@Tinche @hynek Thank you for looking into this issue!
