### ISSUE TITLE
attrs logo is blurry on https://www.attrs.org/en/stable/ on a fractional scaled monitor

### ISSUE THREAD

**Issue by graingert** [python-attrs/attrs#674]
I think an SVG logo would fix it, or a [hidpi alternative image](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#Resolution_switching_Same_size_different_resolutions)

**Comment by hynek** [comment]
ISTM like it's impossible to achieve with the RTD theme. :(

- If I add a small version you get what you described.
- If I add a big version, it's huge in low-res.
- I don't see a way to define a srcset for RTD.
- If I set it to an SVG version, it doesn't show anything and I suspect I run into this: https://stackoverflow.com/questions/59215996/how-to-add-a-logo-to-my-readthedocs-logo-rendering-at-0px-wide: 
![Screenshot 2020-08-24 at 08 24 37](https://user-images.githubusercontent.com/41240/91010708-466b5e80-e5e3-11ea-9d87-b764b1ac8735.png)

If there is some trick to make the SVG version work, I'd love to hear it.

**Comment by graingert** [comment]
using an SVG in Furo would allow dark theme support: @pradyunsg

**Comment by pradyunsg** [comment]
I'm open to it -- if it doesn't work already, please go ahead and file an issue over on Furo's tracker and I'll come around to it after the upcoming pip release. :)

**Comment by hynek** [comment]
Yay, look how pretty the logo is in SVG!

Now the only problem is the night mode but that's not relevant to _this_ bug.
