### ISSUE TITLE
Constants without boilerplate

### ISSUE THREAD

**Issue by hindman** [python-attrs/attrs#683]
Naturally, I use attrs all the time for classes without boilerplate. But I also
use it for constants.

A common situation:

    # I need some constants to get the magic strings out of my code.

    KING = 'king'
    QUEEN = 'queen'
    ROOK = 'rook'
    BISHOP = 'bishop'
    KNIGHT = 'knight'
    PAWN = 'pawn'

    WHITE = 'w'
    BLACK = 'b'

    # But I also want to group the constants up in various ways.

    PIECES = (KING, QUEEN, ROOK, BISHOP, KNIGHT, PAWN)
    COLORS = (WHITE, BLACK)

I could bundle them inside trivial classes:

    class Pieces:
        KING = 'king'
        etc

    class Colors:
        etc

But that won't give me an easy way to iterate over the collections. And it
won't have as many conveniences as attrs-based classes.

So I wrote a utility function to create an attrs class and return an instance of it.

    Pieces = constants('Pieces', 'KING QUEEN ROOK BISHOP KNIGHT PAWN')

    if p == Pieces.KING:
        ...

By default, that instance is frozen, so it's a good vehicle for constants.

    Pieces.KING = 'foo'   # Fails.

It's informative when printed:

    Pieces(KING='KING', QUEEN='QUEEN', ROOK='ROOK', BISHOP='BISHOP', KNIGHT='KNIGHT', PAWN='PAWN')

It is directly iterable and convertable to other collections:

    pairs = list(Pieces)
    d = dict(Pieces)

    for name, val in Pieces:
        ...

It supports various aesthetic/naming styles:

    NAMES = 'KING QUEEN ROOK BISHOP KNIGHT PAWN'
    names = NAMES.lower()

    Pieces = constants('Pieces', names, value_style='upper')  # Pieces.king = 'KING'
    Pieces = constants('Pieces', NAMES, value_style='lower')  # Pieces.KING = 'king'
    pieces = constants('pieces', NAMES, value_style='lower')  # pieces.KING = 'king'

It supports enum-like behavior:

    Pieces = constants('Pieces', names, value_style='enum')   # king = 1, queen = 2, ...
    Pieces = constants('Pieces', names, value_style=(25, -5)) # king = 25, queen = 20, ...

The user can control the constant values precisely by supplying a dict:

    Pieces = constants('Pieces', dict(king=0, queen=9, rook=5, bishop=3, knight=3, pawn=1))

Or by supplying a callable taking an INDEX and NAME:

    f = lambda i, name: '{}-{}'.format(name, 10 - i)
    Pieces = constants('Pieces', names, value_style=f)

If this functionality is of interest to the attrs developers I will submit a
proper PR, with code, tests, and docs.

Thanks for taking a look at this.

**Comment by wsanchez** [comment]
Why not use Enum from stdlib?

**Comment by wsanchez** [comment]
Well, that's by design… if you are using constants, you want all code to use the constants and not the underlying values, which, if changed, would make the code more fragile.

I've written a fair bit (de-)serialization code (or other code that interoperates with some external thing) where you are constantly converting to/from values, and even in that case, it's useful (especially with typing) to ensure you are using the constants internally and values only when crossing a boundary.

Of course you might think that's all a waste of time, but I'm not sure addressing that is in Attrs' problem domain.  Or I'm not thinking of your use case well.  A Chess game isn't good example, I'm pretty sure…

**Comment by hindman** [comment]
Thanks for taking the time to consider this. I published the [short-con](https://pypi.org/project/short-con/) library separately. Closing the issue.
