### ISSUE TITLE
A field with defaultdict default retains value between instances

### ISSUE THREAD

**Issue by berislavlopac** [python-attrs/attrs#689]
Perhaps I'm doing something wrong, but this is not what I expected:

Setup:
```python
>>> from collections import defaultdict
>>> import attr
>>> @attr.s
... class Foo:
...     a: dict = attr.ib(default=defaultdict(lambda: ""))
... 
>>> f = Foo()
>>> f.a
defaultdict(<function Foo.<lambda> at 0x7f903511aef0>, {})
>>> f.a["bla"] = "boo"
>>> f.a
defaultdict(<function Foo.<lambda> at 0x7f903511aef0>, {'bla': 'boo'})
```
Action:
```python
>>> g = Foo()
>>> g.a
```

Expected result:
```python
defaultdict(<function Foo.<lambda> at 0x7f903511aef0>, {})
```

Actual result:
```python
defaultdict(<function Foo.<lambda> at 0x7f903511aef0>, {'bla': 'boo'})
```

**Comment by berislavlopac** [comment]
Using `attr.Factory` helps, but requires an extra `lambda`:

```python
>>> @attr.s 
... class Foo:
...     a: dict = attr.ib(default=attr.Factory(defaultdict(lambda: ""))) 
... 
>>> f = Foo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<attrs generated init __main__.Foo>", line 5, in __init__
TypeError: 'collections.defaultdict' object is not callable
```

```python
>>> @attr.s 
... class Foo:
...     a: dict = attr.ib(default=attr.Factory(lambda: defaultdict(lambda: ""))) 
... 
>>> f = Foo()
>>> f.a
defaultdict(<function Foo.<lambda>.<locals>.<lambda> at 0x7f0ff6ed2ef0>, {})
>>> f.a["bla"] = "boo"
>>> f.a
defaultdict(<function Foo.<lambda>.<locals>.<lambda> at 0x7f0ff6c52680>, {'bla': 'boo'})
>>> g = Foo()
>>> g.a
defaultdict(<function Foo.<lambda>.<locals>.<lambda> at 0x7f0ff6c52050>, {})
```

**Comment by euresti** [comment]
This is the same problem as doing 

```
def foo(y = {}):
   return y
```

See for more details: https://towardsdatascience.com/python-pitfall-mutable-default-arguments-9385e8265422

So you do need the Factory with the lambda.

```
@attr.s 
class Foo:
    a: dict = attr.ib(default=attr.Factory(lambda: defaultdict(str))) 
```

You can also replace the `lambda : ""`   with just `str` since `str()` gives you `""`

**Comment by berislavlopac** [comment]
Of course it's the same problem; my point is that it shouldn't be. :roll_eyes:

**Comment by berislavlopac** [comment]
It's not quite the same, but I see why it's easier to leave it like this.

**Comment by hynek** [comment]
What in your opinion makes it different? A function is called at import time that returns an object that is then used as a default?

If I’m not mistaken, we‘d have to special case default dicts with isinstance checks or something?

**Comment by berislavlopac** [comment]
Well, I'd actually suggest raising an error on a mutable default, just as like `dataclass` does.

**Comment by berislavlopac** [comment]
In fact you could go a step further -- `dataclass` checks only against `list`, `dict` and `set`, so it misses `collections.deque`; checking against `MutableSequence`, `MutableMapping` and `MutableSet` would be more complete. ;)

**Comment by Tinche** [comment]
1) ew, we'd have to maintain a list of everything that's mutable? I think mypy might be better here?
2) sometimes mutable dicts as default argument values are fine if the function uses them read-only

**Comment by berislavlopac** [comment]
1. Well, those three protocols should cover pretty much all the key cases. No need to be more pedantic (as opposed to more _complete_) than `dataclass`.
2. Possibly, but that's quite an edge case, and I wouldn't rely on that too much.

In any case, this is starting to veer strongly into bikeshedding territory. As far as I'm concerned, there are two ways to go about it: a) leave is as it is, or b) follow the `dataclass` example (with the option of being more complete); I'll leave it to @hynek to decide.
