### ISSUE TITLE
attrs class object shared between processes

### ISSUE THREAD

**Issue by BrendanSimon** [python-attrs/attrs#690]
I would like to share a class object (or even a plain dict) between processes.

I came across a project called `datafiles` on PyPi, which uses python 3.7 dataclasses and transparently stores/updates the file and registered objects if anything changes.

https://pypi.org/project/datafiles/

Is there anything similar for attrs, where I can transparently sync shared attrs object between processes?

**Comment by hynek** [comment]
Given how similar attrs and dataclases are internally, I would assume it shouldn't be too much work to make datafile work with both?

**Comment by wsanchez** [comment]
I suspect this feature would be out of scope for Attrs proper… I suggest you look into adding support for Attrs to `datafiles` or something similar, as @hynek suggests, and then let us know so we can add the result to the [wiki](https://github.com/python-attrs/attrs/wiki/Extensions-to-attrs).

**Comment by wbolster** [comment]
closing since this does not belong in `attrs` proper as stated above
