### ISSUE TITLE
Calling non-default super init function

### ISSUE THREAD

**Issue by ItayGoren** [python-attrs/attrs#695]
I'm having troubles with the following classes:
- Having a class `A` with non default constructor.
- Class `B` with a default constructor doesn't call the constructor of `A` but rather initialise his members in a default way.
```python
@attr.dataclass(init=False)
class A:
   x: int
   def __init__(self, x):
    print('A constructor')
    self.x = x

@attr.dataclass
class B(A):
    y: int
```
Now, running the line `B(3, 4)` doesn't print `A constructor`.
From looking inside the code, the constructor of B is generated by `_make_init` and `_attrs_to_init_script` which set all the attributes in the class and his parents. Yet, I expected it to call the constructor of each parent.

Is it on purpose? What are the guidelines for such cases?

**Comment by hynek** [comment]
`attrs` always writes the whole class according to its attributes for performance reasons. If you need to run `super` for some reason, you can currently only do it from within `__attrs_post_init__`.

**Comment by ItayGoren** [comment]
shouldnt it be a parameter in the decorator? i might accept the performance issue if i have to do some logic in the parent ctor before calling the son one

**Comment by hynek** [comment]
Please note we'll have `__attrs_pre_init__` and `__attrs_init__` in the next release.
