### ISSUE TITLE
Positional arguments in `__init__`

### ISSUE THREAD

**Issue by ItayGoren** [python-attrs/attrs#696]
Looking at the following class:
```python
@attr.s
class A:
    x: int
    y: int
    z: int = attr.ib(default=4)
```
(EDIT - fix the example)
```python
@attr.dataclass
class A:
    x: int
    y: int
    z: int = attr.ib(kw_only=True)
```
I see it generates the following `__init__`:
```
def __init__(x: int, y: int, *, z: int) -> None
```
Thus, I can not create an instance using the following `A(x=3, y=4, z=5)`.
Why are the first arguments are positional arguments and not regular one?
I would expect the signature to be:
```
def __init__(x: int, y: int, z: int) -> None
```
Thanks

**Comment by hynek** [comment]
Class A is not an attrs class. The way it's written attrs does nothing at all.

**Comment by ItayGoren** [comment]
i forgot adding the decorator in the question, did it now

**Comment by hynek** [comment]
This will result in

```
Revealed type is 'def (self: t.A, z: builtins.int =)'
```

because attr.s doesn't look at types by default.

If you use `define` or `dataclass`, you get:

```
Revealed type is 'def (self: t.A, x: builtins.int, y: builtins.int, z: builtins.int =)'
```

which is correct AFAICT.

**Comment by ItayGoren** [comment]
Ok i found my mistake, it happens when there is a kw_only argument
For example in the following:
```python
@attr.dataclass
class A:
    x: int
    y: int
    z: int = attr.ib(kw_only=True)
```
gives `Signature: A.__init__(self, x: int, y: int, *, z: int) -> None`
Why is x and y positional?

**Comment by hynek** [comment]
I think you might be mixing up "positional" and the new "positional-only" arguments (`/`)?

**Comment by ItayGoren** [comment]
i mean both directions. Both `A(3, 4, 5)` doesn't work and `A(x=3, y=4, z=5)` doesn't work

**Comment by hynek** [comment]
`A(x=3, y=4, z=5)` totally works, I've just tested it with your example.

`A(3, 4, 5)` doesn't work, because z is `kw_only=True`.
