### ISSUE TITLE
Better defaults for asdict/astuple

### ISSUE THREAD

**Issue by hynek** [python-attrs/attrs#705]
- Would it be acceptable to change the default value for `retain_collection_types` to `True`? This would reduce the likelihood of this issue to appear unexpectedly. It is not a full fix though.

- Would it be ok to use `tuple` as default collection type, when `retain_collection_types=False`? I would expect this to completely resolve the issue.

_Originally posted by @tovrstra in https://github.com/python-attrs/attrs/issues/646#issuecomment-682167908_

**Comment by petergaultney** [comment]
I think retain=True makes a lot of sense. 

As much as I love tuples (and immutable data in general), it seems risky to (essentially) auto-convert lists to tuples. I imagine there's too much code out there that relies on the Python-wide "default" of mutable container types. It would work fine for my use cases, though.
