### ISSUE TITLE
collect_by_mro is missing in the typed signature

### ISSUE THREAD

**Issue by raabf** [python-attrs/attrs#711]
Although the parameter `collect_by_mro` is implemented in

https://github.com/python-attrs/attrs/blob/48157a574185a476fce31a8ddfc92ec490a102f4/src/attr/_make.py#L994-L1017

it is missing it the typed signature of the pyi file

https://github.com/python-attrs/attrs/blob/48157a574185a476fce31a8ddfc92ec490a102f4/src/attr/__init__.pyi#L257-L303

As a consequence, type checkers such as `mypy` would never allow to use `collect_by_mro`, since the signature cannot match, although in runtime it would work because the actual implementation of the function has the parameter.

**Comment by hynek** [comment]
Thanks, should be fixed.

**Comment by raabf** [comment]
Thank you @hynek  :smile:, but didn’t you miss the type annotation?
i.e. `collect_by_mro: bool = ...,` instead of `collect_by_mro = ...,`?

**Comment by hynek** [comment]
Waaat. Why does the test pass then. 🤔 Probably implicit Any?

**Comment by hynek** [comment]
Should be fixed _now_. Thanks for double-checking!

**Comment by raabf** [comment]
Thanks! Regarding the test which passes:
I did not find any mypy configuration for the attrs repository. The think the default configuration of mypy allows untyped elements, and just checks those which are typed. To detect such errors like missing types, you should make mypy more restrictive such as with `disallow_untyped_defs = True` and `check_untyped_defs = True`, which I think is good when you want to be serious regarding full compatibility with mypy.

**Comment by hynek** [comment]
You're right, that's how I run my own projects too. `attrs`'s typing setup is a bit more special but this we should add. See 6b4a1f1ce65162afe54e7101b263859bf8b2177e
