### ISSUE TITLE
Using attr.asdict incorrectly converts tuples to lists

### ISSUE THREAD

**Issue by exhuma** [python-attrs/attrs#715]
When an attrs class has a field of type tuple, then converting it to a dict using `attr.asdict` will convert that data-type to a `list`.

Here is a simple code example:

```
import attr
@attr.s
class Foo:
    x = attr.ib(type=tuple, factory=tuple)

instance = Foo()
assert isinstance(instance.x, tuple)  # <- succeeds
dictified = attr.asdict(instance)
assert isinstance(dictified["x"], tuple)  # <- fails
```

This happens for both empty tuples, and tuples containing items.

**Comment by hynek** [comment]
Try setting `retain_collection_types=True`

**Comment by exhuma** [comment]
Oh. I was not aware of this. This works. Thanks. I will close this. But as a follow-up question for my curiosity: Why is this not the default? Is it for backwards-compatibility with older versions of `attr` or is there a more important detail to know about that I should be aware of?

**Comment by hynek** [comment]
Yes, backward compat…see also #705.
