### ISSUE TITLE
Python 3.10 compatibility

### ISSUE THREAD

**Issue by frenzymadness** [python-attrs/attrs#716]
Hello.

We have already started testing RPM packages in Fedora with Python 3.10a2 and attrs is currently not compatible.

The problem is caused by the implementation of [PEP 563](https://www.python.org/dev/peps/pep-0563/#abstract) — type annotations are now stored as strings which cause asserts like this one to fail:

```python
class TestAnnotations:
    """
    Tests for types derived from variable annotations (PEP-526).
    """

    def test_basic_annotations(self):
        """
        Sets the `Attribute.type` attr from basic type annotations.
        """

        @attr.s
        class C:
            x: int = attr.ib()
            y = attr.ib(type=str)
            z = attr.ib()

        assert int is attr.fields(C).x.type
```

The value stored in `attr.fields(C).x.type` is a string "int" instead of a class int.

It seems it was discussed before in https://github.com/python-attrs/attrs/issues/424

**Comment by Tinche** [comment]
Do we need to call `attr.resolve_types` first in the test?

**Comment by frenzymadness** [comment]
Do I understand it correctly that we are waiting for https://github.com/python-attrs/attrs/issues/593 here?

**Comment by hynek** [comment]
Yes. :(

**Comment by frenzymadness** [comment]
FTR, when issue 593 is fixed now, I can use `attr.resolve_types(C)` in the `test_basic_annotations` and that makes the previously mentioned `assert int is attr.fields(C).x.type` pass but the last assert in the test:

```python
assert C.__init__.__annotations__ == {
    "x": int,
    "y": str,
    "return": None,
}
```

still complains about `{'x': 'int'} != {'x': <class 'int'>}`. I'm not sure how much you want to make the attrs behave the same under Python 3.10. If that's the goal, we should probably keep tests untouched.

**Comment by hynek** [comment]
The test needs to be changed to get_type_hints I'm afraid. There's a bunch more stuff breaking that I'm working on rn.

**Comment by frenzymadness** [comment]
Great movement. Can we expect a new release soon?

**Comment by hynek** [comment]
We/I need to write some narrative docs about new features and this issue uncovered that our hooks system is very hard to use with Python 3.10/string types, so we'll have to write some kind of `attr.resolve_type()` that can convert `"str"` to `str`.
