### ISSUE TITLE
FR: Allow custom equality function for attributes

### ISSUE THREAD

**Issue by rhofour** [python-attrs/attrs#724]
Motivation: I have some classes that contain floats and when I compare them I'd like to check if they're close enough rather than exactly equal.

Right now I can do this by writing my own __eq__ method, but this can get to be a bit tedious with several classes with many attributes on each. This also means every time I add a new attribute I have to update my __eq__ method or my code can silently do the wrong thing.

What I'm proposing is instead to have the attr.ib eq method accept a comparison function for that individual attribute. This would then be used in the automatically generated __eq__ function to compare that attribute. This would get rid of all the tediousness of manually defining an __eq__ function that's almost identical to the generated one while also protecting me from mistakes such as not including new attributes in the __eq__ function.

**Comment by rhofour** [comment]
And immediately after I submitted this I saw #627 which appears to be adding something rather similar.

**Comment by wsanchez** [comment]
Yeah, I'm gonna call this a duplicate, though as #627 progresses you should verify whether it ends up addressing your need (I agree it seems like it would).
