### ISSUE TITLE
Feature Request: Concise way of using `attr.evolve` to set an attribute to its default value

### ISSUE THREAD

**Issue by huzecong** [python-attrs/attrs#730]
Thanks for developing and maintaining this awesome package! Here's my feature request:

I want to set an attribute's value back to its default value. For example:
```python
@attr.s
class Foo:
	a: int = attr.ib(default=1)
	b: str = attr.ib(default="string")

foo = Foo(a=2, b="new_string")
```
Now I want to create a new `Foo` instance based on `foo`, but replacing `a` with its default value of 1. The only way I can think of is:
```python
foo_default = attr.evolve(foo, a=attr.fields_dict(Foo)["a"].default)
```
which is awfully verbose.

Would it be possible to add something like `attr.DEFAULT` to indicate we want the default value? So that:
```python
foo_default = attr.evolve(foo, a=attr.DEFAULT)
```
would work the same way as above.

**Comment by sscherfke** [comment]
You can also do `attr.fields(Foo).a.default` which is a bit shorter. And maybe even short enough? 👼

**Comment by Tinche** [comment]
Another option is `from attr import fields as f` to shorten it that way.

**Comment by huzecong** [comment]
Haha yeah that's definitely shorter, thanks for the tip! I understand that this feature probably isn't too useful. Will close for now.
