### ISSUE TITLE
ruamel.yaml loading quirks

### ISSUE THREAD

**Issue by TMiguelT** [python-attrs/attrs#735]
I have a YAML dump of a class, which is missing certain fields because it was dumped based on an old version of that class:

```yaml
!Command &id001
command:
  - samtools
```
```python
@yaml_object(yaml)
@attr.s(auto_attribs=True)
class Command:
    command: typing.List[str]
    docker_image: typing.Optional[str] = None
```

When you load YAML using `ruamel.yaml`, it chooses between two code paths: https://github.com/pycontribs/ruyaml/blob/71b30f6e837781969ba9732a6f80d5fd359db507/lib/ruyaml/constructor.py#L723-L728.

By default, we don't have `__setstate__` defined, so `ruamel` first creates an instance of the class using `__new__()` (at this point all the class fields are set to `NOTHING`), then tries to `data.__dict__.update()`. However, since the YAML state is actually incomplete (it's missing the field `docker_image`), the missing field gets deleted from the `attrs` class, and trying to access it causes an error.

If, on the other hand, I `getstate_setstate=True`, then it gets even worse, because the resulting class now has the field *values* set to the field *names* in a very weird and confusing way.

I feel like both of these behaviours are bugs, but the most important one is that a `__dict__.update()` can delete fields, instead of just setting them to their default. This is a breaking change with `dataclasses`, which I originally used, and passed my unit test. It was only after porting to `attr` that the missing field error started happening.

**Comment by Drino** [comment]
Hello. Unfortunately, I don't have any good solution for the problem, but I would like to clarify two points here:

> creates an instance of the class using __new__() (at this point all the class fields are set to NOTHING),

> the most important one is that a __dict__.update() can delete fields, instead of just setting them to their default

What actually happens here is:
1. `__new__`  creating an empty instance (without any fields set)
2. `__repr__` does `getattr(self, attrib_name, NOTHING)` for all the fields. As all fields are missing - 
3. `__dict__.update()` updates instance dict (it has nothing to do). 

```
In [1]: import typing, attr                                                                                                                                                                                

In [2]:  
   ...: @attr.s(auto_attribs=True) 
   ...: class Command: 
   ...:     command: typing.List[str] 
   ...:     docker_image: typing.Optional[str] = None 
   ...:                                                                                                                                                                                                    

In [3]: c = Command.__new__(Command)                                                                                                                                                                       

In [4]: c                                                                                                                                                                                                  
Out[4]: Command(command=NOTHING, docker_image=NOTHING)

In [5]: c.command                                                                                                                                                                                          
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-69efc766ad27> in <module>
----> 1 c.command

AttributeError: 'Command' object has no attribute 'command'
```

For `dataclasses` this works, because the generated class has classvar equal to default: 
```
In [6]: from dataclasses import dataclass                                                                                                                                                                  

In [7]: @dataclass 
   ...: class Command: 
   ...:     c: int = 5 
   ...:                                                                                                                                                                                                    

In [8]: Command.c                                                                                                                                                                                          
Out[8]: 5
```
Note, that this approach will break as soon as `default_factory` will be involved:
```
In [3]: @dataclass 
   ...: class C: 
   ...:     a: list = field(default_factory=list) 
   ...:                                                                                                                                                                                                    

In [4]: C.a                                                                                                                                                                                                
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-7cf4d8ab5a46> in <module>
----> 1 C.a

AttributeError: type object 'C' has no attribute 'a'
```

Seems like this is the principal flaw of `ruamel.yaml` - it basically ignores the whole `__init__` section of the class.

**Comment by TMiguelT** [comment]
Thanks for your comprehensive answer, I appreciate the clarifications. It does indeed seem like my dataclasses were working by a fluke and I should really have a custom solution for this. On the other hand, I thought that `getstate_setstate` *was* the correct way to implement custom object loading, but the autogenerated ones don't seem to work in this situation.

**Comment by hynek** [comment]
Closing since there doesn't seem to be anything we can really do about this. It might be worth raising with ruamel.yaml tho.

**Comment by TMiguelT** [comment]
Did you not see my concerns regarding the setstate implementation?
