### ISSUE TITLE
accessin attribute from class (not instance) fails

### ISSUE THREAD

**Issue by dz0** [python-attrs/attrs#736]
```python
from attr import dataclass

@dataclass
class A:
    x:int =4

print(A.__attrs_attrs__)
print(A.x) # <- AttributeError: type object 'A' has no attribute 'x'
```

while standardt classes do OK
```py
from dataclasses import dataclass

@dataclass
class D:
    x:int=4

print(D.__dataclass_fields__)
print(D.x)
```

- py 3.7.5
- attrs 20.2.0

**Comment by dz0** [comment]
could do via `ClassVar` -- but then not available for instance

how can I get same behaviour as standardt `dataclass`?

ps.: now I am develpoing on py37, and want it to be compatible with py36 via attrs

**Comment by Tinche** [comment]
Use `fields(A).x` instead. Dataclasses will also have to remove this if they ever support slot classes.

**Comment by dz0** [comment]
Is there s param to make nonslots class?

2020-12-18, pn 14:12, Tin Tvrtković <notifications@github.com> rašė:

**Comment by Tinche** [comment]
Yes, but the API is the same, for consistency. You will have to use `fields`.

**Comment by Drino** [comment]
Note, that you can use a custom [field_transformer](https://www.attrs.org/en/stable/extending.html#transform-fields) hook to add defaults as classvars. 
Please, note that the dataclass behavior is pretty quirky - e.g. it works strange with default_factories.

**Comment by hynek** [comment]
So this behavior goes back to #253 in 2017, closing since workarounds have been posted.
