### ISSUE TITLE
asdict recursion with value_serializer

### ISSUE THREAD

**Issue by blthayer** [python-attrs/attrs#745]
Hello, and thanks for `attrs`!

The docs for [asdict](https://www.attrs.org/en/stable/api.html#attr.asdict) state the following for the `recurse` argument:

> Recurse into classes that are also `attrs`-decorated.

However, when using a `value_serializer` with `asdict` it's clear that the recursion also happens for non `attrs`-decorated objects. Here's a simple example:
```python
from typing import List

import attr


@attr.s()
class MyClass:
    a: List[int] = attr.ib()


def serialize(inst, field, value):
    print(f'inst: {inst}')
    print(f'field: {field}')
    print(f'value: {value}')
    print('')
    return value


if __name__ == '__main__':
    mc = MyClass(a=[1, 2, 3])
    attr.asdict(inst=mc, recurse=True, value_serializer=serialize)

```
And here's the resulting output:

> inst: MyClass(a=[1, 2, 3])
field: Attribute(name='a', default=NOTHING, validator=None, repr=True, eq=True, order=True, hash=None, init=True, metadata=mappingproxy({}), type=typing.List[int], converter=None, kw_only=False, inherited=False, on_setattr=None)
value: [1, 2, 3]
> 
> inst: None
field: None
value: 1
>
> inst: None
field: None
value: 2
> 
> inst: None
field: None
value: 3

This behavior is not expected considering the documentation for `asdict`. While I haven't done any bench marking, this seems like it could also add a performance hit for attributes that contain a lot of data.

With the contrived/simple example out of the way, here's my "real world" use case:

I'm using `attrs` to create dataclasses that hold large amounts of data. The data comes in as JSON, and `attr.ib` converters are used to convert lists of lists to `numpy` arrays for mathematical operations.

After my program's computations are complete, it's time to send the results back. Since `numpy` arrays do not directly serialize to JSON, they must first be converted to a list. This seemed like the perfect opportunity to use `attr.ib` + `metadata` combined with `asdict` + `value_serializer`. However, I don't want my `value_serializer` function called for every element in a huge array!

**Comment by hynek** [comment]
Hm, let's pull in @sscherfke but I wouldn't consider calling a serialization hook "recursing"? My gut feeling tells me that the current behavior is necessary for advanced features.

Your problem can probably be solved using the `filter` argument?

**Comment by blthayer** [comment]
Thanks, @hynek for your response. I agree that calling the serialization hook itself is not "recursing," but rather when `recurse=True` and a `value_serializer` is provided, the `value_serializer` gets called for every recursive call to `asdict` (and by looking at the source, also for every recursive call to `_asdict_anything`, which always recurses for `tuple`, `list`, `set`, `frozenset` and `dict` instances).

As a user I expected my `value_serializer` to be called _once_ for each attribute of my `attrs` class, but instead it's being called recursively for every sub-item in the attribute until primitive types are hit (well, technically until an object that is not a `tuple`, `list`, `set`, `frozenset` or `dict` is hit).

As to your suggestion: I agree - I can solve my problem by using a `filter` so that my arrays (lists of lists (... of lists of lists...)) do not have `value_serializer` called for each element recursively. Unfortunately, this will require me to call `asdict` twice during serialization, which doesn't seem as ergonomic as calling it once with a `value_serializer` that is only called once per attribute.

Whether the resolution to this issue is to improve the docs, update the code, or do nothing, thanks for maintaining this great package.

**Comment by wsanchez** [comment]
Sounds like we think the behavior is correct, but some clarification in the documentation would help.
