### ISSUE TITLE
what is the expected behavior of resolve_types

### ISSUE THREAD

**Issue by skarchmit** [python-attrs/attrs#751]
```py
@attr.resolve_types
@attr.dataclass
class A:
   a: int
```

```py
a1 = A(a=5)
# no error thrown; great!
```

```py
a1 = A(a='A')
# no error thrown; bad?
```

I would assume that this would also attach a validator? Is there a way to attach type validators automatically? 

The same applies to `@attr.s`

**Comment by hynek** [comment]
The resolve_types has nothing to do with validators etc but about resolving string annotations into real annotations.

E.g.

```pycon
>>> import attr
>>> @attr.define
... class A:
...     x: "str"
...
>>> attr.fields(A).x.type
'str'
>>> A = attr.resolve_types(A)
>>> attr.fields(A).x.type
<class 'str'>
```

This is especially interesting if you run in from `__future__ import annotations`. That was supposed to become the default in 3.10 but might change after all (see [PEP 649](https://www.python.org/dev/peps/pep-0649/)).

---

As for automated adding of validators etc, we've recently added the concept of [field hooks](https://www.attrs.org/en/stable/extending.html#automatic-field-transformation-and-modification) to get that underway.

The relevant bug to follow is #649 (what were the odds!?).

**Comment by wsanchez** [comment]
I think there's not further action here. Please re-open if you disagree.

**Comment by skarchmit** [comment]
Thank you @hynek and @wsanchez !
