### ISSUE TITLE
mypy not recognising attr.setters.convert

### ISSUE THREAD

**Issue by chrisbeardy** [python-attrs/attrs#758]
related to #757 

I have the following:

```python
    test_mode: Union[str, TestModes] = attr.ib(
        init=False,
        default=TestModes.NONE,
        converter=test_mode_to_string,
        on_setattr=attr.setters.convert,
    )
```

mypy is giving me the following error:

![image](https://user-images.githubusercontent.com/20585410/107667931-ffa01c80-6c87-11eb-9992-3a724622d7f9.png)

I am assuming this is a mypy error but I thought I would put it here to check?

Python 3.6 attrs 20.3.0 mypy 0.790

**Comment by hynek** [comment]
Please update mypy to its latest version (as of writing 0.800) and see if it helps

**Comment by chrisbeardy** [comment]
upgrading does not fix it, I have opened an issue in mypy's repo too.

**Comment by chrisbeardy** [comment]
for reference I got the following reply from a contributor of mypy: https://github.com/python/mypy/issues/10084#issuecomment-778393303 suggesting it may be a problem with the bundled stubs. I have had a look at the setters.pyi and convert is in there.

**Comment by euresti** [comment]
Hi.  Do you have the `attrs` package installed on the virtual env from which you run mypy?  Because otherwise you're using the stubs shipped with `mypy` which are fairly old.

**Comment by chrisbeardy** [comment]
> Hi. Do you have the `attrs` package installed on the virtual env from which you run mypy? Because otherwise you're using the stubs shipped with `mypy` which are fairly old.

Thank you for this pointer,  I realise now that as I am running mypy from a isolated virtualenv, I had not installed attrs into that venv, therefore was using the stubs still bundled with mypy. This was my mistake and after installed attrs into the mypy venv, these errors are not shown.
