### ISSUE TITLE
What distinguishes attrs from PEP 557 dataclasses?

### ISSUE THREAD

**Issue by scravy** [python-attrs/attrs#761]
Since we have `@dataclass` in our batteries, a document distinguishing `attrs` from PEP-557 dataclasses would be good; possibly enumerating differences, features available in both, only attrs, only dataclasses, etc.

https://www.python.org/dev/peps/pep-0557/

**Comment by hynek** [comment]
There are a few in https://www.attrs.org/en/stable/why.html#data-classes

I guess especially after the past few releases, the differences skyrocketed though.

**Comment by henryiii** [comment]
Slots is being added to data classes in 3.10, as well as kwonly (both big reasons to use attrs before). https://docs.python.org/3.10/library/dataclasses.html#dataclasses.dataclass

You still have a _lot_ more power with attrs, like the ability to do slots and kwonly in older Python versions, as well as features like validators.

**Comment by hynek** [comment]
Oh well, all the more important to get 21.1 out as long it's correct. 21.2 is due for some documentation overhaul. But it's gonna be complicated…I guess we'll need tables or something. 😳
