### ISSUE TITLE
Issue with pythonista

### ISSUE THREAD

**Issue by RXVAN** [python-attrs/attrs#769]
Only having this issue on Pythonista, basically, it keep saying that attr has no attribute ‘s’ and it’s really annoying. 
![FE481C64-A1E8-48B8-B906-17137C73CA7F](https://user-images.githubusercontent.com/58669904/109157160-94ffde00-7769-11eb-8f8b-022341e485f6.jpeg)
 I’m kinda new to this so yah

edit: trying to use Aiohttp and getting the error in helpers.py :/
![A2257F9D-4530-4829-9FDA-D3B753AFE6D1](https://user-images.githubusercontent.com/58669904/109157574-17889d80-776a-11eb-8b80-42802552af35.jpeg)
Not sure if this helps but just in case

**Comment by Tinche** [comment]
Wouldn't that be a Pythonista issue though?

**Comment by RXVAN** [comment]
> Wouldn't that be a Pythonista issue though?

_That’s what I’m asking..._

**Comment by hynek** [comment]
I don't know how you've installed aiohttp within Pythonista, because it doesn't come with it?

In any case, _if_ attrs is somehow installed, it looks like it's being shadowed by an other module called attr.

Since neither is pre-installed in Pythonista, I'm not sure how to help you.

**Comment by RXVAN** [comment]
> I don't know how you've installed aiohttp within Pythonista, because it doesn't come with it?
> 
> In any case, _if_ attrs is somehow installed, it looks like it's being shadowed by an other module called attr.
> 
> Since neither is pre-installed in Pythonista, I'm not sure how to help you.

There is a thing called Stash which is PIP for Pythonista, it’s a direct plugin for it, that’s how I installed it. Also, ATTR and ATTRS is the same thing afaik.

**Comment by hynek** [comment]
Depends how you define "thing". `attrs` is the package you install and `attr` is the package you import (that will change eventually and `attrs` will also be importable as `attrs` but that's not relevant to your problem).

Try running `import attr; print(attr)` to see what it is and where it's coming from.
