### ISSUE TITLE
MyPy rejects `isinstance(x, attr.Factory)`

### ISSUE THREAD

**Issue by dargueta** [python-attrs/attrs#778]
### The issue

**Expected:** I can check if an attribute's default is a Factory using `isinstance()`
**Result**: MyPy throws an error, saying `Function` is an invalid second argument

This is because the [annotation for Factory](https://github.com/python-attrs/attrs/blob/main/src/attr/__init__.pyi#L60-L69) defines it as a function.

### To reproduce

Given this file:

```py
import attr

@attr.dataclass
class Test:
    x: int

[x_def] = attr.fields(Test)
assert not isinstance(x_def.default, attr.Factory)
```

Running MyPy with all default options (aside from `--show-error-codes`) yields the following result:

```
dargueta@tux:~/Desktop$ mypy --show-error-codes test.py 
test.py:10: error: Argument 2 to "isinstance" has incompatible type overloaded function; expected "Union[type, Tuple[Union[type, Tuple[Any, ...]], ...]]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

### Environment

* CPython 3.8.5
* `attrs`: 20.3.0
* `mypy`: 0.812
* OS: Ubuntu 20.04.2 LTS

### Potential fixes

I understand the necessity for this and am not sure how to work around it aside from adding an `ignore[arg-type]` directive in my code, but I'd rather not if there's a way to change the annotations in a backwards-compatible way. So far all my ideas would require turning `Factory` into a class and messing with `default`, which seems risky to me.

**Comment by euresti** [comment]
I just saw how https://github.com/Shoobx/mypy-zope handles it, but it requires the plugin to do it.  Essentially `Factory` would be a class until you call it, then the return value is an `int` instead of an instance of the class.

**Comment by dargueta** [comment]
So `Factory` _is_ a class in its implementation but is declared as a function in the .pyi file. I see the logic for why it needs to lie about the return type, and if it were left to me I would probably do it that way myself. However, this approach also angers MyPy, and rightly so.

**Comment by euresti** [comment]
You can always tell mypy the truth:
```
from typing import cast
assert not isinstance(x_def.default, cast(type, attr.Factory))
```

You can even save it:
```
FactoryType = cast(type, attr.Factory)
assert not isinstance(x_def.default, FactoryType)
```

**Comment by dargueta** [comment]
I can't believe this didn't occur to me at all 🤦

**Comment by hynek** [comment]
Is there anything left to be done here?

**Comment by dargueta** [comment]
I don't think so.
