### ISSUE TITLE
auto_attribs + Factory + validator doesn't work

### ISSUE THREAD

**Issue by belm0** [python-attrs/attrs#788]
```python3
import attr
from functools import partial
import numpy as np

@attr.attrs(auto_attribs=True)
class Foo:
    position: np.ndarray = attr.Factory(partial(np.zeros, 3))
    #position: np.ndarray = attr.attrib(default=attr.Factory(partial(np.zeros, 3)))  # this works

    @position.validator
    def check_position(self, attribute, value):
        if value.size != 3:
            raise ValueError
```

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<input>", line 6, in Foo
AttributeError: 'Factory' object has no attribute 'validator'
```

version: 20.2.0

**Comment by hynek** [comment]
The decorator syntax only works with attr.ibs: https://www.attrs.org/en/stable/init.html#decorator

We could technically fudge it into factories, but that wouldn't fix all other use cases and would only cause more confusion.

**Comment by belm0** [comment]
the docs for `auto_attribs`:
> If you assign a value to those attributes (e.g. x: int = 42), that value becomes the default value like if it were passed using attr.ib(default=42). Passing an instance of Factory also works as expected.

Yet passing a Factory instance did not work as expected.  Please document the decorator limitation here.
