### ISSUE TITLE
Cannot use __attrs_pre_init__ method

### ISSUE THREAD

**Issue by winn-cui** [python-attrs/attrs#790]
Hello,

According to #750, `__attrs_pre_init__` has been merged into main. However, as of v20.3.0, the method is not found when I pip install the attrs package. 

As an example, in #750, you can see `_has_pre_init_` has been added.
![image](https://user-images.githubusercontent.com/10666125/114447451-48d8f380-9b87-11eb-8686-459b63ac31e8.png)

In my Python project, attrs v20.3.0 does not have `_has_pre_init_` added.
![attrs_pre_init](https://user-images.githubusercontent.com/10666125/114448254-298e9600-9b88-11eb-8439-d64a3d46fe69.PNG)

Any thoughts as to why this code discrepancy exists?

**Comment by hynek** [comment]
Unfortunately, there was no release with #750 yet. I hope to be able to make one soon, but would like to merge #787 first.

**Comment by winn-cui** [comment]
Wow, thank you for the quick response! Will patiently watch for its release then.
