### ISSUE TITLE
auto_detect in mypy

### ISSUE THREAD

**Issue by hynek** [python-attrs/attrs#793]
Opening here for discussion, before moving into mypy's bug tracker.

It just painfully occurred to me that mypy doesn't support `auto_detect=True` which is True by default in NG.

E.g. in

```python
@attr.define
class SortableTableHeaders:
    headers: dict[str, str]
    default: str

    def __init__(self, names: tuple[str, ...]) -> None:
        def normalize(s: str) -> str:
            return s.replace(" ", "-").lower()

        self.default = normalize(names[0])
        self.headers = {normalize(n): n for n in names}
```

it forces you to pass `init=False` to `define`. Has that been raise to mypy? Would it be hard to implement? I think that's a really nice feature and am surprised myself, I didn't notice it before. @euresti any ideas?

**Comment by euresti** [comment]
I implemented the auto_detecting of attribs.  But nothing else.  You can file it there, but they'll probably just ping me about fixing it.  Unless someone else is excited about learning the mypy plugin code.  :)
