### ISSUE TITLE
PEP 563 postponed to Python 3.11

### ISSUE THREAD

**Issue by frenzymadness** [python-attrs/attrs#803]
Hello.

Deferred evaluation of type annotations has been postponed to Python 3.11: https://mail.python.org/archives/list/python-dev@python.org/thread/CLVXXPQ2T2LQ5MP2Y53VVQFCXYWQJHKZ/

Currently, I see only two test failures with the latest Python 3.10b1 (for the latest attrs release) and they are both already fixed in https://github.com/python-attrs/attrs/commit/03d3fc7a71fe770e1f86b9c3ad8588586e5ea63b but there are more changes than that so I don't know whether the compatibility with Python 3.10 needs any more work or not.

Could you please add Python 3.10 to CI? It should be pretty stable in the beta phase.

**Comment by hynek** [comment]
What makes you think that 3.10 is not part of the CI? We've just had to pin 3.10 to alpha7 due to the beta1 & pytest breakage but it's been there for a while.

**Comment by frenzymadness** [comment]
I'm sorry, I saw a commit message saying "Disable 3.10 until it stops breaking" and assumed that this part of the CI is disabled now. I should check it.

Do you think that the current master is compatible with the 3.10 beta?

**Comment by hynek** [comment]
Yes, I've re-enabled b1 while responding to you. To circle back to your original message: attrs was passing on 3.10 deferred evaluation; we just had to disable 3.10 for a while it due to breakage with (I think) typed-ast that wasn't our fault.

**Comment by hynek** [comment]
(also 21.1 is going out _this_ week. i'm just tying up loose ends atm)

**Comment by hynek** [comment]
Closing this since I don’t think there is anything to do.
