### ISSUE TITLE
Pipenv warehouse version is abnormal

### ISSUE THREAD

**Issue by timwang-ai** [python-attrs/attrs#808]
pipenv.patched.notpip._vendor.requests.exceptions.ConnectionError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/20/a9/ba6f1cd1a1517ff022b35acd6a7e4246371dfab08b8e42b829b6d07913cc/attrs-21.2.0-py2.py3-none-any.whl (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))

**Comment by Tinche** [comment]
Looks like a PyPI issue?

**Comment by hynek** [comment]
Yeah that's a network problem on your side, or a PyPI issue. Either way, nothing _we_ can do about.
