### ISSUE TITLE
typing error in combination with pylance for factory=list

### ISSUE THREAD

**Issue by matt-the-midnight-hacker** [python-attrs/attrs#810]
Hello I'm very excited that attrs now allows to show constructor parameters when used with pylance.
I'm using `attrs-21.2.0`
However I have a problem when using a class with factory, the factory appears to be not recognized as default value. For example:
```
@attr.s(auto_attribs=True)
class A:
    my_i: int = 42
    my_list: List[str] = attr.ib(factory=list)
```
If I try to instantiate this class with `a = A()` I get error from pylance: 'Argument missing for parameter "my_list"'.
And for the class definition I get the error "Fields without default values cannot appear after fields with default values".
I noticed it works somehow when I use `my_list: List[str] = attr.Factory(list)` but with this the type is set to Factory and I get problems if I want to use the list `a.my_list.append('fu')` will then lead to "Instance of 'Factory' has no 'append' member".

**Comment by hynek** [comment]
Yes, this has been raised in https://github.com/python-attrs/attrs/issues/795#issuecomment-833958298 . I hope the pyright team sees it our way…

**Comment by matt-the-midnight-hacker** [comment]
Sadly not, maybe pylance could do? Seems like that there is some trouble in finding a aggreement which project will handle default_factory (https://github.com/python-attrs/attrs/issues/795#issuecomment-843409923). Maybe supporting `attr.Factory(list)` in pylance is an option?

**Comment by hynek** [comment]
Great news, they added `factory`!
