### ISSUE TITLE
Weird behavior when patching an attrs class (slots=True vs False)?

### ISSUE THREAD

**Issue by alonme** [python-attrs/attrs#811]
I am noticing a behavior which i didn't expect.
when moving from a slotted class to a non slotted my test broke and i found out that when mocking 

is this expected? why does it happen? how can i user autospec on a nonslotted attr class?

Following is a reproducible example:

```python
In [1]: import attr
   ...: from typing import Optional
   ...: from unittest.mock import patch
   ...:
   ...: import sys
   ...:
   ...: print(f"python version: {sys.version}")
   ...: print(f"attr version: {attr.__version__}")
   ...:
   ...:
   ...: print("++++++++++++++++++++++++++++")
   ...:
   ...:
   ...: @attr.mutable(slots=False)
   ...: class Foo:
   ...:     bar: Optional[int] = attr.ib(
   ...:         init=False,
   ...:         default=None,
   ...:         validator=attr.validators.optional(attr.validators.instance_of(int)),
   ...:     )
   ...:
   ...:
   ...: @attr.mutable(slots=True)
   ...: class SlottedFoo:
   ...:     bar: Optional[int] = attr.ib(
   ...:         init=False,
   ...:         default=None,
   ...:         validator=attr.validators.optional(attr.validators.instance_of(int)),
   ...:     )
   ...:
   ...:
   ...: p1 = patch("__main__.Foo", autospec=True).start()
   ...: p2 = patch("__main__.SlottedFoo", autospec=True).start()
   ...:
   ...:
   ...: print("\n\nchecking non-slotted")
   ...: try:
   ...:     print(p1.bar)
   ...: except Exception as e:
   ...:     print("non-slotted failed with error:")
   ...:     print(e)
   ...:
   ...: print("\n\nchecking slotted")
   ...: try:
   ...:     print(p2.bar)
   ...: except Exception as e:
   ...:     print("slotted failed")
   ...:     print(e)
   ...:
python version: 3.7.9 (default, May  2 2021, 10:57:00)
[Clang 12.0.5 (clang-1205.0.22.9)]
attr version: 20.3.0
++++++++++++++++++++++++++++


checking non-slotted
non-slotted failed with error:
Mock object has no attribute 'bar'


checking slotted
<MagicMock name='SlottedFoo.bar' id='4541344272'>
```

**Comment by hynek** [comment]
I don't think autospec looks at type annotations? If I read the docs correctly, you could pass in an instance and that should do the trick.

Slotted works because it's possible to find the attributes via introspection.

**Comment by alonme** [comment]
Not sure i understand how are type annotations related, is this concerning how attrs is implemented?
removing the type annotations does not change anything in my code example.

regarding passing an instance - yes, using `spec` and passing an instance does work, however this is different then using `autospec`

I did look deeper into the documentation of mock and found this

_A more serious problem is that it is common for instance attributes to be created in the __init__() method and not to exist on the class at all. autospec can’t know about any dynamically created attributes and restricts the api to visible attributes._
(https://docs.python.org/3/library/unittest.mock.html#autospeccing)

I am not familiar with attrs internals so i don't know if this may be our problem in this case

**Comment by hynek** [comment]
That's what I meant: if you only define the types and mock doesn't look at type annotations, there's no way for mock to know that the attributes exist – until they are set in `__init__`. You can verify that yourself by looking at the class in a repl. It should be noted, that that's a feature.

I guess mock should learn about type annotation a to infer the existence of attributes.

**Comment by alonme** [comment]
OK, now i get it.

Thanks for the prompt and helpful response
