### ISSUE TITLE
Support match case destructuring in Python 3.10 using __match_args__

### ISSUE THREAD

**Issue by tirkarthi** [python-attrs/attrs#814]
In Python 3.10 match/case syntax was added that also has destructuring syntax. dataclass supports this feature and has option to disable this. The current logic is at https://github.com/python/cpython/blob/366c69f3f63a2a1cce57dabe8f7c2e67d1df625d/Lib/dataclasses.py#L374 where init and kw_only are checked.

dataclass had some discussion and added support where `__match_args__` generation can be disabled if needed : https://bugs.python.org/issue43764

I have a patch locally working. I can write some tests. But I will be happy to know if a PR is accepted and if an option to disable matching is needed like dataclasses.

attrs

```python
# /tmp/attrs_match.py    
import attr

@attr.s
class AttrPerson:
    name = attr.ib()

person = AttrPerson(name="Kate")

match person:
    case AttrPerson(name):
        print(f"Found {name}")
    case _:
        print("Not found")
```

```
python /tmp/attrs_match.py
Traceback (most recent call last):
  File "/tmp/attrs_match.py", line 10, in <module>
    case AttrPerson(name):
TypeError: AttrPerson() accepts 0 positional sub-patterns (1 given)
```

Dataclasses

```python
# /tmp/dataclass_match.py 
from dataclasses import dataclass

@dataclass
class Person:
    name: str

    
person = Person(name="Kate")

match person:
    case Person(name):
        print(f"Found {name}")
    case _:
        print("Not found")
```

```
$ python /tmp/dataclass_match.py 
Found Kate
```

**Comment by tirkarthi** [comment]
An implementation with tests : https://github.com/tirkarthi/attrs/commit/452b09af33ed15843ae3a38eaf742d46b0d5832a

**Comment by wsanchez** [comment]
@tirkarthi Thanks for working on this.  I suspect that a PR would be welcome here.

**Comment by tirkarthi** [comment]
Thanks @wsanchez , I have created https://github.com/python-attrs/attrs/pull/815 for review.
