### ISSUE TITLE
Using field transformer breaks integration with hypothesis

### ISSUE THREAD

**Issue by jakub-borusewicz** [python-attrs/attrs#821]
Adding field transformer according to [documentation](https://www.attrs.org/en/stable/extending.html#automatic-field-transformation-and-modification) (i.e. as a function of type `Callable[[type, list[attr.Attribute[Any]]], list[attr.Attribute[Any]]]`)
breaks `attrs` integration with hypothesis, because attributes transformed with such function are not casted to generated `AttrsClass`, but remains just an list of attributes ([here](https://github.com/python-attrs/attrs/blob/9709dd82e1cc0f5b783f4127e87498dfdd6a224a/src/attr/_make.py#L602))

This causes error in hypothesis [here](https://github.com/HypothesisWorks/hypothesis/blob/3d5761ed9254b39260f39cf52bad1293ccf733ab/hypothesis-python/src/hypothesis/strategies/_internal/attrs.py#L33), because `fields` is an list, not an `AttrsClass` instance, and therefore `getattr(fields, name)` raises an `AttributeError`.

Easy workaround for that is just to create an `AttrsClass` again inside field transformer, like so:

```
def transformer(cls: type, fields: list[attr.Attribute[Any]]) -> list[attr.Attribute[Any]]:
    attr_names = [f.name for f in fields]
    AttrsClass = _make_attr_tuple_class(cls.__name__, attr_names)
    
    ... do something with fields ...

    return AttrsClass(fields)
```

...but it's not very handy nor pretty, and messes with typing. So, I would very thankful if it could be resolved within `attrs` (it would be quite easy, I guess).

BTW. I love your package, awesome job! Cheers!

**Comment by hynek** [comment]
@sscherfke? 😇

**Comment by sscherfke** [comment]
I will take a look, but I can’t tell when. I’m currently quite busy with work. :)
