### ISSUE TITLE
Changing order of attributes with inheritance

### ISSUE THREAD

**Issue by hydrobeam** [python-attrs/attrs#827]
Hello! I'm trying to see if it's possible to recreate the following style of inheritance with attrs, such that it's possible to create a `Line` class with `Line(<start>, <end>)` as args, not kwargs

```py
class Line(TipableVMobject):
    def __init__(self, start=LEFT, end=RIGHT, buff=0, path_arc=None, **kwargs):
        self.start = start
        self.end = end
        self.dim = 3
        self.buff = buff
        self.path_arc = path_arc
        super().__init__(**kwargs)
```

With the implementation below, the `__init__` order is the reverse of what I'd like it do be, since args are passed all the way up to the base class instead of to `Line`. So I'd have to do `Line(start = <start>, end = <end>)`.
```py
@attrs(hash=False)
class Line(TipableVMobject):
    start = attrib(LEFT)
    end = attrib(RIGHT)
    dim = attrib(3)
    buff = attrib(0)
    path_arc = attrib(None)
```

I realize that there's the ability to override the `__init__` class but this forces me to essentially do what I was already doing  beforehand. I read through the docs and many other websites but couldn't find a solution to this problem, please let me know if you have any ideas

**Comment by hynek** [comment]
I'm a bit confused what you mean. Could you share `TipableVMobject` too please?

**Comment by hydrobeam** [comment]
Sorry for the confusion! I probably should have started with a simpler example since the inheritance is a little complicated in my case. Here's a simpler example:

```py
from attr import attrs, attrib

@attrs
class Base:
    a= attrib()
    b= attrib()

@attrs
class BasePlus(Base):
    c= attrib()
    d= attrib()
   
a = BasePlus(1, 2, 3, 4)

# what it currently is
>>> a
BasePlus(a=1, b=2, c=3, d=4)

# what I'd like it to be
>>> a
Baseplus(c=1, d=2, a=3, b=4)
    
```

Hopefully that's a little clearer

**Comment by sscherfke** [comment]
Maybe you can implement a [field transfomrer](https://www.attrs.org/en/stable/extending.html#automatic-field-transformation-and-modification) that modifies the order of the attributes.

**Comment by hynek** [comment]
if you want strict control over the parameters, you can also use:


```python
@attr.define
class Base:
    a = attr.field()
    b = attr.field()

@attr.define
class BasePlus(Base):
    c = attr.field()
    d = attr.field()

    def __init__(self, c, d, a, b):
        self.__attrs_init__(a=a, b=b, c=c, d=d)

```

gives you:

```pycon
>>> BasePlus(1,2,3,4)
BasePlus(a=3, b=4, c=1, d=2)
```
