### ISSUE TITLE
Alternative implementation for ‘frozen’

### ISSUE THREAD

**Issue by orent** [python-attrs/attrs#833]
This old recipe shows a different way to implement immutable classes that does not have any performance penalty:

https://code.activestate.com/recipes/578233-immutable-class-decorator

It works by assigning another  \_\_class\_\_ after \_\_init\_\_ is done that has read-only descriptors for all members.

It has some visible effects that theoretically make it not 100% backward compatible,  but I don’t think they are likely to be a problem in practice.

I am opening this issue here for discussion and might go all the way to a PR if there is interest.

**Comment by Tinche** [comment]
That's an interesting approach, but my feeling is it's going to be slower for attribute access since it essentially adds another layer with properties. I'd be curious to see benchmarks first.

**Comment by orent** [comment]
This does not add another layer. Descriptors are the mechanism python uses under the hood to implement slots. Check the recipe to see how it modifies the descriptors already there.  It uses the original descriptor’s _\_\get\_\_ but skips the \_\_set\_\_ and \_\_del\_\_.

**Comment by oakkitten** [comment]
so according to `%timeit foo.bar` where `foo` is an instance of a class, on my rpi3/py10,

* plain old python class without any freezing: 525 ns ± 2.34 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
* same but with a slot: 507 ns ± 3.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
* `@attr.frozen`: 523 ns ± 2.51 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
* same but with `slots=True`: 505 ns ± 0.912 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
* `@immutable`: 982 ns ± 1.61 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

**Comment by Tinche** [comment]
@orent Ah, I see you're the author of the snippet from 2012.

You're wrong about not having an additional layer though. What this does is essentially this:

```
class T:
    __slots__ = ('_a')
    def __init__(self, a):
        self._a = a
    @property
    def a(self):
        return self._a
```
(except you're being clever with using `property` directly on `T._a.__get__`)

Avoiding an additional layer is really hard. Our best bet is probably using Cython to simply make it insignificant: https://groups.google.com/g/cython-users/c/QaQDNLE-76Y

**Comment by hynek** [comment]
Looking at @oakkitten's benchmarks, I think this is less about performance and more about possible convenience within initialializers?

Unless someone can show me benchmarks that it's significantly faster, I think we can close this issue because I already smell the edge cases coming at as. That decorator seems to work stand-alone so people can can apply it to mutable `attrs` classes – no?
