### ISSUE TITLE
Detecting if user has customized __eq__?

### ISSUE THREAD

**Issue by nicoddemus** [python-attrs/attrs#834]
Hi,

In pytest, when `assert d1 == d2` fails and `d1` and `d2` are attrs-classes, we detect that and inspect the attributes so we can show a detailed error:

```python
    def test():
        d1 = Data(1, 2)
        d2 = Data(1, 3)
>       assert d1 == d2
E       AssertionError: assert Data(x=1, y=2) == Data(x=1, y=3)
E
E         Omitting 1 identical items, use -vv to show
E         Differing attributes:
E         ['y']
E
E         Drill down into differing attribute y:
E           y: 2 != 3
``` 

However, when the user defines a custom `__eq__`, that logic might be incorrect because the custom `__eq__` might use completely different logic than comparing the attributes. It might even be customized to handle objects which don't compare normally with `==`, such as `numpy` arrays.

So we would like to *skip* our custom introspection that generates the detailed message when the user has implemented their own `__eq__` method (https://github.com/pytest-dev/pytest/issues/8930#issuecomment-885539032).

One idea would be to access the parameters passed to `attr.s`/`@define`, however looking at the docs I couldn't find a way to do it. Also tried introspecting the class with a debugger, but couldn't find anything related to that either.

So the question is if there's a way to detect if a user has supplied their own custom `__eq__` method?

Ref: https://github.com/pytest-dev/pytest/issues/8930

**Comment by hynek** [comment]
If I’m not mistaken (on phone rn), that’s related to #602 that kinda fell off the horizon?

**Comment by nicoddemus** [comment]
> If I’m not mistaken (on phone rn), that’s related to #602 that kinda fell off the horizon?

🤦 

I swear I did browse the tracker, seems I completely missed that one.

Thanks! I subscribe to that issue then.

**Comment by hynek** [comment]
No it’s good you brought it up. I’ve completely forgotten about it and since we want to provide our users with all kinds of meta introspection powers, it’s a painful gap!
