### ISSUE TITLE
PyPy2 tests running?

### ISSUE THREAD

**Issue by alexomics** [python-attrs/attrs#837]
Are your PyPy2 tests running?

I've been getting started with tox for running my tests so I've been looking at what other projects do. 
I really liked/got what was going on here so I've used it as a starting point for my project.
When I first ran tox using GitHub actions I noticed my pypy2 test finished instantly when it used to take >6mins.

So I came back here to take a look if I was doing anything wrong and noticed the same issue, for example [on this recent action](https://github.com/python-attrs/attrs/runs/3053357978?check_suite_focus=true). This is the log and it completes in `0s`:

```none
Run python -m tox
  python -m tox
  shell: /usr/bin/bash -e {0}
  env:
    USING_COVERAGE: 2.7,3.7,3.8,3.10.0-beta - 3.10
    pythonLocation: /opt/hostedtoolcache/PyPy/2.7.18/x64/bin
___________________________________ summary ____________________________________
  congratulations :)
```

I'm not sure why/what is going wrong but thought you'd want to know!

**Comment by hynek** [comment]
Ugh, yes thanks! Fixed in https://github.com/python-attrs/attrs/commit/2ca7aada707167cda9b3c8bbc2fd195e4f1aa422
