### ISSUE TITLE
a way to check if attrs class is frozen?

### ISSUE THREAD

**Issue by anthrotype** [python-attrs/attrs#853]
Hello,
I'd like to check at runtime if an instance of an attrs class is frozen or not. Currently the way I do this is by checking if `cls.__setattr__.__name__ == "_frozen_setattrs"`, which is the name of the attrs' defined custom setattrs method when frozen=True.  But it feels a bit hacky. I could also simply try to set an attribute and check TypeError, but then I need to know the name of the attribute in advance.

Would it be possible to add a function (e.g. `attr.is_frozen`, or `attr.has(frozen=True)`) that checks whether the attrs class is also frozen?

Thanks

**Comment by hynek** [comment]
Looks like a special case of #602?

**Comment by anthrotype** [comment]
Yes, thanks, I'll follow the other issue
