### ISSUE TITLE
Heads up! Black has deprecated Python 2 formatting support since 21.10b0

### ISSUE THREAD

**Issue by ichard26** [python-attrs/attrs#862]
Hello! I'm a co-maintainer of psf/black and I wanted to pop by and let y'all know that Black has deprecated Python 2 since 21.10b0. Assuming things go to plan the support will be dropped sometime in January of 2022 along side the first stable release[^1] of Black :tada: I noticed that this project is still relying on Black's support for Python 2 as I was formatting attrs via some development tooling I'm building[^2]. I don't know how much this will be an issue for y'all but hopefully this won't be a surprise at least :)

---

Also Hynek if you're reading this, big thanks for your all of your Python posts! They've been a valuable resource, in particular the inheritance one.

[^1]: it was unideal that [Łukasz's tweet](https://twitter.com/llanga/status/1455496802812239876) about the importance of 21.10b0 didn't mention this deprecation :/
[^2]: the gist of it is it runs black over a bunch of projects to both make sure black doesn't crash and that any formatting changes (both of the project code and between versions of black) are expected

**Comment by ichard26** [comment]
Actually it turns out the version of black I was using had a bug, running with a unmodified install of 21.10b0 nets me no warnings about Python 2. Sorry for the noise!

**Comment by hynek** [comment]
Thank you for your kind words! I have seen that warning and we'll just pin Black, once the day comes. The big q is also, if it doesn't just mean Python-2 specific code, that we don't have (e.g. `print` statement)…guess time will show.

**Comment by sscherfke** [comment]
We could also just remove py2 support and let users of old apps pin an old attrs version instead.  Just sayin’ … 😛
