### ISSUE TITLE
If its not hard could you re-enable generation of PDF & epub docs on readthedocs.org

### ISSUE THREAD

**Issue by mattaw** [python-attrs/attrs#865]
If its not hard could you re-enable generation of PDF & epub docs for your https://readthedocs.org/projects/attrs/ builds? It helps with poor internet and working on flights a lot. (Great project by the way - I consider it essential to any python project now, along with mypy typing.)

**Comment by hynek** [comment]
Oh I thought it was active because that’s what the web said, but it looks like the config file overrode it.

it’s active now (https://github.com/python-attrs/attrs/commit/ad5da29d664a2846bff6aa53fdc7041c97f55a87) and latest docs can be downloaded. I should probably fill out the meta data tho.

**Comment by hynek** [comment]
Oh and BTW: for offline API docs I'm a big fan of tools like https://kapeli.com/dash or https://zealdocs.org/

I wrote https://github.com/hynek/doc2dash to convert Python docs to their format.
