### ISSUE TITLE
Dict-like attrs classes

### ISSUE THREAD

**Issue by blthayer** [python-attrs/attrs#879]
Sometimes it's desirable to have an `attrs` class quack like a `dict`. A couple use cases off the top of my head:
- Refactoring an application whose API was initially built to work purely with `dict`s, but now it's desirable to use stricter "contracts" (via `attrs` classes)
- Serialization of attrs classes (to, say, `json`)

Perhaps an argument to `attr.s`/`attr.define` like `dict_like=True` or `dict_quack=True`?

Here's an example of a mixin class I whipped up to get my `attrs` classes to masquerade as dictionaries when it's convenient and makes sense:

```python
from collections.abc import MutableMapping
from typing import Any, Iterable, NoReturn

import attr


class MutableMappingMixin(MutableMapping):
    """Mixin class to make attrs classes quack like a dictionary (well,
    technically a mutable mapping). ONLY use this with attrs classes.

    Provides keys(), values(), and items() methods in order to be
    dict-like in addition to MutableMapping-like. Also provides pop(),
    but it just raises a TypeError :)
    """

    __slots__ = ()  # May as well save on memory?

    def __iter__(self) -> Iterable:
        for field in attr.fields(self.__class__):
            yield field.name

    def __len__(self) -> int:
        return len(attr.fields(self.__class__))

    def __getitem__(self, k: str) -> Any:
        """
        Adapted from:
        https://github.com/python-attrs/attrs/issues/487#issuecomment-660727537
        """
        try:
            return self.__getattribute__(k)
        except AttributeError as exc:
            raise KeyError(str(exc)) from None

    def __delitem__(self, v: str) -> NoReturn:
        raise TypeError("Cannot delete fields for attrs classes.")

    def __setitem__(self, k: str, v: Any) -> None:
        self.__setattr__(k, v)

    def pop(self, key, default=None) -> NoReturn:
        raise TypeError("Cannot pop fields from attrs classes.")

    def keys(self) -> Iterable:
        return self.__iter__()

    def values(self) -> Iterable:
        for key in self.__iter__():
            yield self.__getattribute__(key)

    def items(self) -> Iterable:
        for key in self.__iter__():
            yield key, self.__getattribute__(key)

```

Now if only I could get `orjson` to not do an explicit `isinstance(obj, dict)` check or [natively support attrs classes](https://github.com/ijl/orjson/issues/92)...
(The `isinstance` check is also an issue in the standard library and other `json` serialization libraries AFAIK)

I'm all ears for suggestions as to why this `dict_like` approach might be problematic or helpful :smile:

**Comment by hynek** [comment]
While I sympathize with your struggle, this is not a core concern that should have an API within attrs – I mean `asdict()` exists. 😅

Three things:

- I usually use singledispatch to teach orjson about attrs until they add proper support.
- the canonical way in Python to fake a dict is to subclass [UserDict](https://docs.python.org/3.10/library/collections.html#collections.UserDict)
- I don't think there's a way to fake yourself into an `isinstance(x, dict)` without actually subclassing dict. :( You'd hope that maybe Python/orjson grows a more generic approach to this eventually; ideally including a Protocol.

**Comment by Tinche** [comment]
Or you could use https://github.com/python-attrs/cattrs which was built for this purpose. There's even a preconfigured converter for orjson: https://github.com/python-attrs/cattrs/blob/main/src/cattr/preconf/orjson.py

**Comment by Tinche** [comment]
@blthayer cattrs is essentially a giant, very advanced singledispatch. In practice the singledispatch implementation from the standard library is inadequate for a bunch of use cases so there's more logic, but in spirit that's it.
