### ISSUE TITLE
attr._cmp stub uses undefined name

### ISSUE THREAD

**Issue by JelleZijlstra** [python-attrs/attrs#883]
The `attr/_cmp.pyi` stub imports the name `_CompareWithType` (https://github.com/python-attrs/attrs/blob/main/src/attr/_cmp.pyi#L3), but that name doesn't exist anywhere else in the repo.

I found this while doing an integration test on installed stubs with [pyanalyze](https://github.com/quora/pyanalyze); I'm guessing it doesn't matter too much because the file is private.

**Comment by hynek** [comment]
It looks like it happened in https://github.com/python-attrs/attrs/pull/787/commits/6f5c5ce42f5c406e446dd3d4863c17f61c7254a7 by accident. 🤔

**Comment by hynek** [comment]
I've opened #884 to fix that
