### ISSUE TITLE
Dataclass fields not being fetched for `resolve_types`

### ISSUE THREAD

**Issue by praateekmahajan** [python-attrs/attrs#901]
Disclaimer : This might be a [cattrs issue](https://github.com/python-attrs/cattrs) (please let me know if I should close this and repost there).

Raising here since after my limited investigation it seems like it might be solvable within `_funcs.py` (might break other things). Per my understanding, **the issue primarily stems from [PEP 563](https://www.python.org/dev/peps/pep-0563/)**. So the behavior changes based on if you use `from __future__ import annotations` in your code.

```python
from __future__ import annotations # comment this line and rerun for success
from dataclasses import dataclass
from cattr import structure


@dataclass
class Foo:
    bar: int


print(structure({"bar": 123}, Foo))
```

This seems to be the code flow
1. `gen_structure_attrs_fromdict` is called https://github.com/python-attrs/cattrs/blob/20ca64405944ea81ac207e070e180d2d805c8fd1/src/cattr/converters.py#L730-L734
2. That calls `fields` in `_compat.py` in `cattr`. This `fields` **works as expected**. https://github.com/python-attrs/cattrs/blob/20ca64405944ea81ac207e070e180d2d805c8fd1/src/cattr/_compat.py#L49-L56
3. For each of the field above `if isisntance(field, str)` then `resolve_types` is called in `_funcs.py` in attr. https://github.com/python-attrs/attrs/blob/3df7bbe089658ecf1dcc21308926bfd9133b12e1/src/attr/_funcs.py#L413
4. The `resolve_types` calls the `fields` in `_make.py` which **raises `NotAnAttrsClassError`** https://github.com/python-attrs/attrs/blob/3df7bbe089658ecf1dcc21308926bfd9133b12e1/src/attr/_make.py#L2029-L2054

To me it seems like the fields in step 2 and 4 could/should be the same? I might be missing context, happy to work on this given some general guidance.

Thank you for the two powerful libraries!

**Comment by Tinche** [comment]
Does it work with cattrs 1.10?

**Comment by euresti** [comment]
Did you mean to do `from dataclasses import dataclass`?  Because then it's not an attrs class.

**Comment by praateekmahajan** [comment]
@Tinche Just saw https://github.com/python-attrs/cattrs/issues/195 and tried 1.10 out, seems like that works. 

@euresti dataclasses was intentional, opened the issue in `attr` since seemed like a generic solution might belong in `attr` but seems like its being taken care of in `cattrs`.

Thanks, will close the ticket!
