### ISSUE TITLE
Unexpected argument warning from pycharm

### ISSUE THREAD

**Issue by Bohdan-Ilchyshyn** [python-attrs/attrs#902]
Pycharm indicates unexpected arguments but code work without problems

My code:
```python
from attrs import define

@define
class Property:
    name: str
    value: Any

    @classmethod
    def from_dict(cls, data: dict):
        return cls(
            name=data['name'], #  Unexpected argument
            value=data['value'] #  Unexpected argument
        )
```

**Comment by Tinche** [comment]
That's a PyCharm bug ;)

They probably haven't added support for `import attrs` (vs `import attr`) yet. You can keep using `from attr import define` until they do, it's the same.
