### ISSUE TITLE
Why need pytest for dev?

### ISSUE THREAD

**Issue by m-wvj** [python-attrs/attrs#908]
Hi guys! Could someone explain to me, whether this was a negligence or an intentional move, to put pytest in the "dev" tag? 

https://github.com/python-attrs/attrs/blob/9727008fd1e40bc55cdc6aee71e0f61553f33127/setup.py#L69-L71

This is not yet a complaint, I try to understand why this happened :)

**Comment by hynek** [comment]
We run our tests using pytest, hence you need pytest to develop on `attrs`.

**Comment by hynek** [comment]
no. dev. dependencies are dependencies needed to develop the module.

attrs has no dependencies at all to run.
