### ISSUE TITLE
Question: How to declare non-int attributes ? 

### ISSUE THREAD

**Issue by UGuntupalli** [python-attrs/attrs#911]
Hello, 

I just stumbled across ```attrs``` package. As I try to get familiar with it, I think what I could not find in the documentation (apologies if I am missing it) is how to define a non-init attribute in a class. 

As I tried to read around, I saw several examples (https://towardsdatascience.com/probably-the-best-practice-of-object-oriented-python-attr-d8c26c0e8a4) of using ```attrib(init=False)``` but this seems to be phased out. 

Can you please explain how to achieve this or point me to where I can find this in the documentation ? 

Here is an example: 

```
# Traditional Class 
class Example: 

         def __init__(self, a: int, b: int): 
               self.a = a 
               self.b = b 
               self.sum = None 


# Class using Attrs ? 
from attires import define 


@define
class ExampleAttrs: 
          a: int
          b: int 
          sum: int(init=False)   # This is raising a warning that "Generics should be specified through square brackets  
```

Thanks for your help in advance

**Comment by UGuntupalli** [comment]
It looks like I could be doing this 

```
from attrs import define, field 


class ExampleAttrs: 
          a: int
          b: int 
          sum: field(default=None, init=False) 

```

However, where or how would the type be specified in this approach ?

**Comment by UGuntupalli** [comment]
I guess, the answer is: 

```
from attrs import define, field 


class ExampleAttrs: 
          a: int
          b: int 
          sum: int = field(default=None, init=False) 
```

If anyone knows of a better way, please let me know. 

Cheers

**Comment by Tinche** [comment]
Nope, you got it right: ```sum: int = field(default=None, init=False) ```.

But if the variable is annotated `int`, `None` is technically not an appropriate default.

**Comment by UGuntupalli** [comment]
@Tinche, 

One question if I may is how to include the doc strings for the class ? Could you please provide an example or point me to an existing one ? 

BTW thanks for this amazing package. 

Cheers 
Uday
