### ISSUE TITLE
How can I call `evolve()` inside a classmethod?

### ISSUE THREAD

**Issue by nathan-deng-ai** [python-attrs/attrs#928]
```python
@frozen
class Context:
    text: str
    index: int = 0

    def set(self, index) -> Context:
            return evolve(self, index=min(max(0, index), len(self.text)))
```

This code is fine during Runtime, but prompted `'attr.evolve' method should be called on attrs instances` in IDE.

How can I fix it?

**Comment by hynek** [comment]
Talk to you IDE vendor I suppose. `self` is clearly an attrs class.

**Comment by nathan-deng-ai** [comment]
It's weird, I will report a bug to PyCharm
在 2022年3月9日 +0800 PM6:22，Hynek Schlawack ***@***.***>，写道：
