### ISSUE TITLE
[bug, typing] MyPy doesn't like attrs.converters

### ISSUE THREAD

**Issue by henryiii** [python-attrs/attrs#930]
In MyPy, using `attrs.converters` gives:

```
error: Module has no attribute "converters"  [attr-defined]
```

Adding an `import attrs.converters` (not needed at runtime) gives:

```
error: Module has no attribute "optional"
```

I think part of the problem is the `__init__.pyi` isn't synced with `__init__.py` for importing submodules. Not sure why the star import isn't working inside converters.py, though.

**Comment by hynek** [comment]
Ugh, looks like our import tests in typing_examples are NOPs.

Each symbol has to be explicitly "re-exported". We've missed `filters` too.

#931 should fix it.

**Comment by henryiii** [comment]
Fantastic, thanks!

I think * imports don't need to be explicitly reexported inside .pyi files, but they do in .py files.

**Comment by hynek** [comment]
I mean then your bug wouldn't have happened? :) And yes, the fixed examples triggered the error too.

I'm somewhat OK with being explicit, but in this case it's very annoying. :-/

**Comment by danjac** [comment]
I'm seeing the same issue with mypy 0.961 and attrs 21.4.0:

```python

import attrs

@attrs.define(kw_only=True)
class Item:
    length: int | None = attrs.field(
        converter=attrs.converters.optional(
            attrs.converters.pipe(float, int),
        ),
        default=None,
    )
```

Running in mypy, getting these (possibly related?) errors:

`Unsupported converter, only named functions and types are currently supported`

`error: Module has no attribute "converters"  [attr-defined]`

**Comment by hynek** [comment]
Yes, sorry there hasn't been a release since this has been fixed yet.
