### ISSUE TITLE
RuntimeWarning: coroutine 'Y.attrs_post_init' was never awaited

### ISSUE THREAD

**Issue by carlosplanchon** [python-attrs/attrs#935]
```
# attrs == 21.4.0.
import attrs
# attrs-strict==1.0.0 
from attrs_strict import type_validator


@attrs.define
class DecoratedClass:
    x: str = attrs.field(validator=type_validator())
    Y: ClassY = attrs.field(
        validator=type_validator())

    async def __attrs_post_init__(self):
        self.fooresult = await self.Y.foo()


Y_obj = ClassY()

ALICE = await users.User(
    x="x",
    Y=Y_obj
)
```
This code throws the following warning:
 \<attrs generated init Y\> :8: RuntimeWarning: coroutine 'Y.__attrs_post_init__' was never awaited

__attrs_post_init__ doesn't work with async code on the conditions described above.

**Comment by hynek** [comment]
You can’t use async functions as part of object initialization in Python. `__init__` is always synchronous and therefore can’t await async methods.

It’s also considered bad engineering to do any I/O in general, when instantiating objects.

**Comment by carlosplanchon** [comment]
Okay. Thx for you answer 💪🏻 . I didn't know about that last part.
