### ISSUE TITLE
Inconsistent documentation around Validator argument naming

### ISSUE THREAD

**Issue by vedantpuri** [python-attrs/attrs#958]
While implementing callable validators for attrs classes, we used the following syntax (which is how attrs [documentation](https://www.attrs.org/en/stable/examples.html#validators) uses in the example, also suggests these kwargs [here](https://www.attrs.org/en/stable/init.html#decorator)):

```
def my_custom_validator(instance, attribute, value):
...
```

However we have a framework where we need to invoke the validators on our attrs classes (which contain both custom validators and attr native validators), and when invoking we tried to use kwargs (`instance`, `attribute`, `value`) which resulted in an error since attr native validators use `inst`, `attr`, `val` argument naming instead.

This issue is to just to call out the inconsistency on naming, either we should:
- Update the documentation to reflect examples using the abbreviated naming OR
- We should change the internal naming to also follow the ones that were documented.

**Comment by hynek** [comment]
I'm sorry but I'm not quite comfortable to make these kinds of details a public API, but I've clarified in the docs, that the arguments are passed as positinal arguments which should at least make the current state of affairs less confusing.
