### ISSUE TITLE
`Frozen` is not completely immutable.

### ISSUE THREAD

**Issue by Harmouch101** [python-attrs/attrs#962]
A while ago, I tried to invent a [god-tier immutable dictionary](https://github.com/Harmouch101/frozndict). Thought for a while, it is the ultimate immutable dictionary out there. Later on, I discovered that it is also mutable because of the `object.__setattr__` method. Then tried it out on the `frozen` decorator of this package, and it turned out that it is also affected by this method. I am not sure if the implementation of the built-in method `object.__setattr__` is buggy, or maybe because everything in python is an object which makes that function run on any python object. Therefore, it is either a bug in `attrs.frozen` or `object.__setattr__`. Most likely the latter. But in case to reproduce the error, consider the following listing:

```python
>>> from attrs import frozen
>>> @frozen
... class Foo:
...   bar: str
... 
>>> foo = Foo("bar")
>>> foo["bar"] = 'foo'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'Foo' object does not support item assignment
>>> object.__setattr__(foo, 'bar', 'foo has been pwned')
>>> foo
Foo(bar='foo has been pwned')
```

Looking forward to your response to confirm whether it is a bug in this package or the built-in `object.__setattr__` method.

**Comment by hynek** [comment]
Our immutability is documented in <https://www.attrs.org/en/stable/how-does-it-work.html#immutability>  and also in our API docs:

<img width="781" alt="Screenshot 2022-05-25 at 11 37 33@2x" src="https://user-images.githubusercontent.com/41240/170232029-1a213236-a892-491b-bccd-2d9bf03721be.png">

There's also a non-significant amount of issues being opened asking about escape hatches form frozen classes, so all works as designed.
