### ISSUE TITLE
Converting the SQLAlchemy example of using attrs with imperative table declarations to the new api way of annotating a class with @define fails due to different defaults

### ISSUE THREAD

**Issue by do3cc** [python-attrs/attrs#964]
This is not really a bug in attrs but I hoped to find this information in this bugtracker.
SQLAlchemy has an example for using attrs with SQLAlchemy: https://github.com/sqlalchemy/sqlalchemy/blob/cec5709a2cc8f4888660a0c0abcb0625d58af7a6/doc/build/orm/declarative_styles.rst#example-three---attrs-with-imperative-table
and it uses the old  style syntax that I am familiar with. I have switched to `@define` in a new project and it looked like SQLAlchemy lost support for attrs and can only handle dataclasses. 
The real reason it did not work was that `@define` by default activates slot behavior which breaks SQLAlchemy in handling attrs annotated classes.
Using 
```
define(slots=False)
```
Fixes this.

**Comment by do3cc** [comment]
My PR on SQLAlchemy for doc change: https://github.com/sqlalchemy/sqlalchemy/pull/8072

**Comment by do3cc** [comment]
Please close as you see fit, I am not sure if you'd get notifications of quickly closed tickets  and I want to give you the chance to see the PR for SQLAlchemy, maybe you want to change something.

**Comment by hynek** [comment]
do you think there's a chance to fix SQLA to support slots? DCs added slots in 3.10 too, so it seems likely people are gonna complain

**Comment by do3cc** [comment]
Using slots is not the default for dataclasses.
There was some discussion over at SQLAlchemy with some minimal sample code:
https://github.com/sqlalchemy/sqlalchemy/issues/7802
When running the samplecode and making it a dataclass, I must remove the __slots__ defined on the class altogether and I get a RecursionError.
When trying the same with ``@define`` I must add some __slots__ arguments, but I end up at the RecursionError.
I know what RecursionError  means, but I don't understand why a recursion is happening.
The original example shows that in general, SQLAlchemy works with slots.

I am at a dead end here :-(
```
Traceback (most recent call last):
  File "/home/do3cc/projects/homo/test.py", line 28, in <module>
    a1 = A(id=5, data="asdf")
  File "<string>", line 2, in __init__
  File "/home/do3cc/projects/homo/lib/python3.10/site-packages/sqlalchemy/orm/instrumentation.py", line 448, in _new_state_if_none
    )._new_state_if_none(instance)
  File "/home/do3cc/projects/homo/lib/python3.10/site-packages/sqlalchemy/orm/instrumentation.py", line 448, in _new_state_if_none
    )._new_state_if_none(instance)
  File "/home/do3cc/projects/homo/lib/python3.10/site-packages/sqlalchemy/orm/instrumentation.py", line 448, in _new_state_if_none
    )._new_state_if_none(instance)
  [Previous line repeated 989 more times]
  File "/home/do3cc/projects/homo/lib/python3.10/site-packages/sqlalchemy/orm/instrumentation.py", line 446, in _new_state_if_none
    return self._subclass_manager(
  File "/home/do3cc/projects/homo/lib/python3.10/site-packages/sqlalchemy/orm/instrumentation.py", line 267, in _subclass_manager
    return register_class(cls, finalize=False)
  File "/home/do3cc/projects/homo/lib/python3.10/site-packages/sqlalchemy/orm/instrumentation.py", line 573, in register_class
    manager = manager_of_class(class_)
  File "/home/do3cc/projects/homo/lib/python3.10/site-packages/sqlalchemy/orm/base.py", line 238, in manager_of_class
    return cls.__dict__.get(DEFAULT_MANAGER_ATTR, None)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by do3cc** [comment]
I missed that one, doh. Have to look into this

**Comment by do3cc** [comment]
Yay, I can make it work. But it is probably not useful:
```
# Both dataclass and define work similar
# Order is important. After attrs or dataclass created the slots, sqlalchemy can't add more attributes.
@dataclass(slots=True)
# @define
@reg.mapped
class A:
    __tablename__ = "a"
    id = Column(Integer, primary_key=True)
    data = Column(String)

    __dict__: dict  # SQLAlchemy overrides attributesetting. This code could be changed not to use __dict__, but it would then just use another dictionary, not sure if this helps
    __weakref__: object # only needed for @dataclass @define of attrs creates it automatically by default

# Because SQLAlchemy must wrap the class first, the SQLAlchemy class_manager can't have a reference to the new class with __slots__, so we must make it awae  of that.
A._sa_class_manager.class_ = A
```
Changing SQLAlchemy to support __slots__ based objects looks like a big project. Nothing which could be done with a  quick PR.

**Comment by hynek** [comment]
yeah it's not practical, but thanks for looking into it! seems like this is an sqlalchemy implementation detail that is now documented on their side, so we can close this i think.
