### ISSUE TITLE
attrs.define made methods readonly?

### ISSUE THREAD

**Issue by haolian9** [python-attrs/attrs#970]
#### reproduce:

```
import attrs
import attr


# # the old way
# @attr.s
# class Connection:
#     _sock: str = attr.ib()

# the new way
@attrs.define
class Connection:
    _sock: str

    def round_trip(self):
        raise NotImplementedError('say hello first!')

    def hello(self):
        def round_trip(self):
            return "ok"

        self.round_trip = round_trip


def test_dynamic_method():
    conn = Connection('sock')
    conn.hello()
```

python: 3.10.4

#### errors:
```
E       AttributeError: 'Connection' object attribute 'round_trip' is read-only
```

the old way works well, but the new way will raise an exception, and i failed to find a doc mentions this change. so i think that's a bug.

**Comment by hynek** [comment]
That's a side-effect of slots=True and documented in the fourth point in https://www.attrs.org/en/stable/glossary.html#term-slotted-classes

You can fix it with `slots=False` if you need that behavior.

**Comment by haolian9** [comment]
wow, thanks for your quick reply! then sorry for the noise.
