### ISSUE TITLE
mypy: Unexpected keyword argument using @define(kw_only=True)

### ISSUE THREAD

**Issue by danjac** [python-attrs/attrs#974]
```python

from attrs import define

@define(kw_only=True)
class Item:
     title: str = ""

item = Item(title="x")
```

mypy reports error  `error: Unexpected keyword argument "title" for "Item"`

Python 3.10.5
attrs 21.4.0
types-attrs 19.10

**Comment by danjac** [comment]
Removing types-attrs:

```
error: Library stubs not installed for "attr" (or incompatible with Python 3.10)
note: Hint: "python3 -m pip install types-attrs"
```

Also, same error as above.

**Comment by Tinche** [comment]
What's your Mypy version? Works for me on 0.950.

**Comment by danjac** [comment]
Same, 0.950.

**Comment by Tinche** [comment]
Something's funky with your environment, works for me (and properly, if I pass in an int it generates an error).

**Comment by danjac** [comment]
It's very likely in that case due to running mypy inside pre-commit. Running mypy separately works OK, but within pre-commit it breaks.

Looks like attrs isn't compatible with the pre-commit version of mypy, I'll raise issue there.

**Comment by danjac** [comment]
OK, so: pre-commit just required attrs (not typed-attrs, which is suggested for some reason):

```
  - repo: https://github.com/pre-commit/mirrors-mypy
         rev: 'v0.961'
         hooks:
             - id: mypy
               additional_dependencies:
                   [
                       attrs==21.4.0,
                   ]
```

**Comment by hynek** [comment]
I'm a bit confused by concept of a MyPy pre-commit plugin.

To use MyPy properly, you need your project and all its dependencies installed, such that it has access to all necessary stubs?

**Comment by danjac** [comment]
It depends: if you are adding type checking to an existing project you might just want rudimentary checks on commit. But yeah, at some point you would want checks on all dependencies.

**Comment by hynek** [comment]
Either way, I’m closing this since I understand it’s not an attrs issues. Pipe up if you disagree.
