### ISSUE TITLE
Slotted classes inheritance question

### ISSUE THREAD

**Issue by ivasylenko** [python-attrs/attrs#989]
Seems Child slots reset Parent slots in such test. Maybe it's expected behaviour but was little confusing to me ..
In the following scenario I would expect `Child` class to have slots `a, b`, but it has only `b`.
Is this expected ? 

```
def test_slotted_classes_inheritance():
    @attr.s(slots=True)
    class Parent:
        a = attr.ib(default=None)


    @attr.s(slots=True)
    class Child(Parent):
        b = attr.ib(default=None)

    assert 'b' in Child.__slots__
    assert 'a' in Child.__slots__
```

attrs versions checked:

```
attrs==20.3.0
attrs==21.2.0
```

**Comment by Tinche** [comment]
Hm, and you'd expect 'a' to only be in `Parent.__slots__`?

**Comment by hynek** [comment]
Unless I'm misunderstanding, this is very much expected and a common bug out there. Child's `__slots__` should _not_ include Parent's slots. Parent should have `("a",)` and Child should have `("b",)`. We even have a unit test for that:

https://github.com/python-attrs/attrs/blob/06ce35459453e7c2964b0e0e25794a6af9aeb976/tests/test_slots.py#L269-L302

**Comment by Tinche** [comment]
Ah, I misunderstood the OP. Yeah, I think we're good here.

**Comment by ivasylenko** [comment]
Thanks @hynek and @Tinche

We happen to use this kind of logic for various conversions, which apparently is not working in this scenario:
```
if hasattr(obj, '__slots__'):
     return {k: fast_to_dict(getattr(obj, k)) for k in obj.__slots__}
```

I am thinking whether to switch to `__dict__` for such cases or use `attr.fields` with `attr.has` to specifically handle attrs classes, e.g.
```
if attr.has(type(obj)):
    return {k.name: fast_to_dict(getattr(obj, k.name)) for k in attr.fields(type(obj))}
```
Anyway, thanks
