### ISSUE TITLE
passing-parameters-to-frozen-super-dataclass

### ISSUE THREAD

**Issue by OrenGitHub** [python-attrs/attrs#992]
Hello guys,
I get a mypy error with `attrs` and not with `dataclass` - 
any chance you can take a look at this SO question:
https://stackoverflow.com/questions/73208921/passing-parameters-to-frozen-super-dataclass
Thanks !

**Comment by hynek** [comment]
Please don't open issues about StackOverflow questions. We're monitoring SO ourselves and do our best to answer all questions.
